# generated by datamodel-codegen:
#   filename:  mlinference.yaml

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class MLModelConfig(BaseModel):
    """
    Deployment-level settings for one issued model. The bundle itself — weights, handler binding, default params — is staged in the workspace and self-described by its manifest.yaml; only what the deployment decides appears here. Empty is valid and usual: it declares the model must load, nothing more.
    """

    params: dict[str, Any] | None = None
    """
    Deployment overrides merged over the bundle manifest's params. Precedence, lowest to highest: manifest params, these, then a request's params.
    """


class InferRequest(BaseModel):
    """
    A generic inference request. `model` picks which loaded model runs. `binary` carries an opaque binary input (e.g. an encoded image); `tensors` carries named numeric tensors (nested arrays) for non-vision models. Supply whichever the selected model's handler expects — one, the other, or both.
    """

    model: str
    """
    Name (id) of the loaded model to run — must match a loaded bundle (a sub-folder of the models repository). See /metadata for valid names.
    """
    binary: bytes | None = None
    """
    Opaque binary input (e.g. an encoded image). Read and decoded by the model's handler.
    """
    tensors: dict[str, Any] | None = None
    """
    Named numeric tensors as nested arrays, for models whose input is not a binary blob. The handler maps these onto the model's input feeds.
    """
    params: dict[str, Any] | None = None
    """
    Free-form per-request overrides (e.g. detection thresholds). Merged over the manifest's params by the handler.
    """


class InferResult(BaseModel):
    """
    A generic inference result. `result` is the handler-produced structured object; its shape is defined by the model's handler, not by this contract.
    """

    model: str
    """
    Name of the model that produced this result.
    """
    result: dict[str, Any]
    """
    Handler-produced structured result. Shape depends on the model's handler; opaque to this contract.
    """


class ModelMetadata(BaseModel):
    """
    Descriptive metadata for one loaded model.
    """

    name: str
    """
    Name (id) of the model — the value to pass as the /infer `model` selector.
    """
    handler: str
    """
    Handler driving the model: `builtin:<name>` or `file:handler.py`.
    """
    modelVersion: str | None = None
    """
    Optional model/bundle version string.
    """


class Health(BaseModel):
    """
    A simple health-probe response.
    """

    status: str
    """
    Probe status (e.g. ok, loading).
    """


class Error(BaseModel):
    """
    A structured error response.
    """

    message: str
    """
    Human-readable error description.
    """


class MLInferenceConfig(BaseModel):
    """
    The ml-inference component's boot config: the models this component is issued. Authoritative — the component loads exactly these bundles from its workspace repository, so a declared bundle that is missing or unloadable is a permanent boot failure and an undeclared sub-folder is ignored. A projection of the deployment's device-located ML models, not an authored artifact: the renderer writes it, the component reads it at boot from the contracted config path. A cross-language seam. Not on the HTTP wire; carried here so the renderer (producer) and component (consumer) share one generated shape. Says WHICH models load and what the deployment overrides — never how a model is driven, which stays in the bundle's own manifest.yaml beside the weights.
    """

    models: dict[str, MLModelConfig]
    """
    Models to load, keyed by model id — the bundle sub-folder name in the workspace repository, and the /infer `model` selector.
    """


class RepositoryMetadata(BaseModel):
    """
    The set of models the component currently has loaded.
    """

    models: list[ModelMetadata]
    """
    Every model loaded into the repository.
    """
