# generated by datamodel-codegen:
#   filename:  ml.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, Field, RootModel


class MLModelConfig(BaseModel):
    """
    Deployment-level settings for one issued model. The bundle itself — weights, handler binding, default params — is staged in the workspace and self-described by its manifest.yaml; only what the deployment decides appears here. Empty is valid and usual: it declares the model must load, nothing more.
    """

    params: dict[str, Any] | None = None
    """
    Deployment overrides merged over the bundle manifest's params. Precedence, lowest to highest: manifest params, then these.
    """


class Task(StrEnum):
    """
    What a model does, and therefore the shape of its result. The unit of normalization across implementations: two object-detection models return the same shape whatever their architecture. `tensor` is the general escape — raw model outputs, for a model whose task this contract does not model.
    """

    object_detection = 'object-detection'
    image_classification = 'image-classification'
    tensor = 'tensor'


class Datatype(StrEnum):
    """
    Element type, in KServe/OIP spelling (FP32, INT64, UINT8, BOOL, BYTES, ...).
    """

    BOOL = 'BOOL'
    UINT8 = 'UINT8'
    UINT16 = 'UINT16'
    UINT32 = 'UINT32'
    UINT64 = 'UINT64'
    INT8 = 'INT8'
    INT16 = 'INT16'
    INT32 = 'INT32'
    INT64 = 'INT64'
    FP16 = 'FP16'
    FP32 = 'FP32'
    FP64 = 'FP64'
    BYTES = 'BYTES'


class Tensor(BaseModel):
    """
    One typed tensor in the KServe/OIP v2 representation: an explicit `datatype` and `shape` over a flat, row-major `data` array. Self-describing — a consumer reconstructs the array with no out-of-band shape knowledge — and used for both raw model inputs and raw model outputs.
    """

    datatype: Datatype
    """
    Element type, in KServe/OIP spelling (FP32, INT64, UINT8, BOOL, BYTES, ...).
    """
    shape: list[int]
    """
    Tensor dimensions, outermost first.
    """
    data: list[Any]
    """
    Elements flattened row-major (C order); length equals the product of `shape`. Numbers for the numeric datatypes.
    """


class TensorInput(RootModel[dict[str, Tensor]]):
    """
    Named input tensors keyed by the model's input feed names — one `Tensor` per model input. Already-numeric input the caller prepared, mapped straight onto the ONNX inputs with no decoding on the component side.
    """

    root: dict[str, Tensor]


class Task1(StrEnum):
    object_detection = 'object-detection'


class Box(BaseModel):
    """
    An axis-aligned box in ORIGINAL input-image pixel coordinates — the decoder projects out of whatever letterboxed or rescaled space the model worked in, so a consumer never needs the preprocessing geometry.
    """

    xmin: float
    ymin: float
    xmax: float
    ymax: float


class Task2(StrEnum):
    image_classification = 'image-classification'


class Classification(BaseModel):
    """
    One candidate class for the whole input.
    """

    label: str
    """
    Human-readable class name, resolved through the model's label map.
    """
    score: float
    """
    Confidence in [0, 1].
    """
    classId: int | None = None
    """
    Raw class index the model emitted, before label resolution.
    """


class Task3(StrEnum):
    tensor = 'tensor'


class TensorResult(BaseModel):
    """
    Raw model outputs, undecoded. The general escape for a model whose task this contract does not model — the caller owns interpreting these.
    """

    task: Literal['tensor']
    tensors: dict[str, Tensor]
    """
    Output tensors keyed by the model's output names, one `Tensor` each.
    """


class ModelMetadata(BaseModel):
    """
    Descriptive metadata for one loaded model.
    """

    name: str
    """
    Name (id) of the model — the value to use as the `model` in an inference path.
    """
    handler: str
    """
    Handler driving the model: `builtin:<name>` or `file:handler.py`.
    """
    task: Task
    modelVersion: str | None = None
    """
    Optional model/bundle version string.
    """


class Health(BaseModel):
    """
    A simple health-probe response.
    """

    status: str
    """
    Probe status (e.g. ok, loading).
    """


class Error(BaseModel):
    """
    A structured error response.
    """

    message: str
    """
    Human-readable error description.
    """


class MLConfig(BaseModel):
    """
    The ML component's boot config: the models this component is issued. Authoritative — the component loads exactly these bundles from its workspace repository, so a declared bundle that is missing or unloadable is a permanent boot failure and an undeclared sub-folder is ignored. A projection of the deployment's device-located ML models, not an authored artifact: the renderer writes it, the component reads it at boot from the contracted config path. A cross-language seam. Not on the HTTP wire; carried here so the renderer (producer) and component (consumer) share one generated shape. Says WHICH models load and what the deployment overrides — never how a model is driven, which stays in the bundle's own manifest.yaml beside the weights.
    """

    models: dict[str, MLModelConfig]
    """
    Models to load, keyed by model id — the bundle sub-folder name in the workspace repository, and the `model` in an inference path.
    """


class Detection(BaseModel):
    """
    One located object.
    """

    label: str
    """
    Human-readable class name, resolved through the model's label map.
    """
    score: float
    """
    Confidence in [0, 1].
    """
    classId: int | None = None
    """
    Raw class index the model emitted, before label resolution. Absent when the decoder has no meaningful index.
    """
    box: Box


class ClassificationResult(BaseModel):
    """
    What the input image depicts, as ranked candidate classes.
    """

    task: Literal['image-classification']
    predictions: list[Classification]
    """
    Candidate classes, ordered by descending score.
    """


class RepositoryMetadata(BaseModel):
    """
    The set of models the component currently has loaded.
    """

    models: list[ModelMetadata]
    """
    Every model loaded into the repository.
    """


class DetectionResult(BaseModel):
    """
    Objects located in the input image. Already filtered and de-duplicated by the model's decoder — a consumer renders or counts these, it does not post-process them further.
    """

    task: Literal['object-detection']
    detections: list[Detection]
    """
    The surviving detections, ordered by descending score.
    """


class InferResult(RootModel[DetectionResult | ClassificationResult | TensorResult]):
    root: DetectionResult | ClassificationResult | TensorResult = Field(
        ..., discriminator='task'
    )
    """
    A task-shaped inference result. Discriminated by `task`, which always equals the producing model's advertised task, so a consumer can decode without knowing the model.
    """
