/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Engine runner state. */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deploy or hot-swap a workflow. */
        post: operations["deploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop the running workflow (idempotent when idle). */
        post: operations["stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Engine runner state.
         * @enum {string}
         */
        State: "idle" | "running";
        StatusResponse: {
            status: components["schemas"]["State"];
        };
        /** @description Error body for /deploy 400/422. Distinct from control-plane ErrorResponse. */
        EngineError: {
            error: string;
        };
        /** @description Engine-served POST /deploy body: a binding-free workflow, the deploy mapping that binds its logical resource ids to this environment, and the resolved external-resource configs those bindings point at. workflow is intentionally NOT required so it generates as a pointer (the handler nil-checks it). */
        DeployRequest: {
            workflow?: components["schemas"]["Workflow"];
            mapping?: components["schemas"]["DeploymentMapping"];
            externalResources?: components["schemas"]["ExternalResources"];
        };
        /** @description Binds a binding-free workflow's logical resource ids to concrete platform resources for one deploy, keyed by workflow resource id. The pool a binding's ref resolves against is determined by the workflow resource's type: hardware channels resolve against the boot DeviceManifest; MQTT channels and custom models against the deploy ExternalResources; RAG memory against the boot-configured backend (the ref is the collection id). */
        DeploymentMapping: {
            [key: string]: components["schemas"]["ResourceBinding"];
        };
        /** @description How one workflow resource binds to the environment. `ref` is the shared platform resource it points at (driver instance id, external resource id, or RAG collection id) — a sharing identity, so many workflow resources may share one ref and the engine builds it once. `index` is the optional per-channel physical sub-address within that resource: GPIO line, or ADC/PWM/DAC channel number. Absent for UART, MQTT, memory and models. */
        ResourceBinding: {
            /** @description Shared platform resource id this binds to. */
            ref: string;
            /** @description Per-channel physical sub-address within the driver (GPIO line / ADC-PWM-DAC channel). Omitted when the resource has no sub-address. */
            index?: number;
        };
        /** @description Deploy-time configs for a workflow's non-device external resources (MQTT transports, custom-model providers, ...), keyed by the platform resource id the DeploymentMapping points at. Replaces the former NetworkManifest. Device-owned configs (drivers) stay in the boot DeviceManifest; this carries only deploy-delivered, swappable configs. */
        ExternalResources: {
            [key: string]: components["schemas"]["ExternalResourceConfig"];
        };
        /** @description Tagged union of deploy-time external-resource configs, discriminated by runtime kind (not by ownership — locality like on-device vs cloud lives inside an arm). New kinds extend this oneOf. */
        ExternalResourceConfig: components["schemas"]["MQTTConnection"] | components["schemas"]["LLMProviderConfig"];
        /** @description Resolved connection to a self-hosted/custom LLM endpoint the llmproxy doesn't ship. The engine registers it as an llmproxy provider for the workflow's custom model; the model's capabilities come from its declared workflow entry, so they are not repeated here. */
        LLMProviderConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "selfhosted";
            /** @description Base URL of the inference endpoint (http:// or https://). */
            url: string;
            /**
             * Format: password
             * @description Optional bearer credential for the endpoint.
             */
            apiKey?: string;
            /** @description Upstream model name the endpoint serves; defaults to the workflow model id when empty. */
            model?: string;
        };
        MQTTConnection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "mqtt";
            brokerUrl: string;
            clientId?: string;
            username?: string;
            /** Format: password */
            password?: string;
            /** @description Topic prefix the engine prepends to workflow-level publish topics ({networkId}/{agentId}/). */
            publishPrefix?: string;
            /** @description Topic prefix the engine prepends to workflow-level subscribe filters ({networkId}/+/). */
            subscribePrefix?: string;
            will?: components["schemas"]["MQTTWill"];
        };
        MQTTWill: {
            topic: string;
            payload: string;
            /** @description MQTT QoS (0,1,2). Cast to byte at the paho call site. */
            qos: number;
            retain: boolean;
        };
        /** @description Hardware resources available on the device, keyed by driver instance ID. Drives runtime driver instantiation on the engine. */
        DeviceManifest: {
            gpios?: {
                [key: string]: components["schemas"]["GPIOConfig"];
            };
            adcs?: {
                [key: string]: components["schemas"]["ADCConfig"];
            };
            dacs?: {
                [key: string]: components["schemas"]["DACConfig"];
            };
            serials?: {
                [key: string]: components["schemas"]["SerialConfig"];
            };
            pwms?: {
                [key: string]: components["schemas"]["PWMConfig"];
            };
        };
        GPIOConfig: {
            /** @description cdev chip name or path, e.g. "gpiochip0" or "/dev/gpiochip0" */
            chip: string;
        };
        ADCConfig: {
            /** @description sysfs path to the IIO device directory, e.g. "/sys/bus/iio/devices/iio:device0" */
            device: string;
        };
        DACConfig: {
            /** @description sysfs path to the IIO device directory, e.g. "/sys/bus/iio/devices/iio:device1" */
            device: string;
        };
        SerialConfig: {
            /** @description Serial device path, e.g. "/dev/ttyUSB0" or "COM3" */
            device: string;
            /** @description Baud rate; falls back to 115200 when zero */
            baud?: number;
        };
        PWMConfig: {
            /** @description sysfs path to the pwmchip directory, e.g. "/sys/class/pwm/pwmchip0" */
            chip: string;
        };
        /** @description Single log event emitted by the engine. The reserved keys (level/action/summary/msg/time) populate dedicated agent_activity columns; any extra top-level keys are bucketed into the details JSONB column on ingest. */
        LogEntry: {
            /** @enum {string} */
            level: "debug" | "info" | "warn" | "error" | "fatal";
            action: string;
            summary: string;
            msg: string;
            /** Format: date-time */
            time: string;
        } & {
            [key: string]: unknown;
        };
        AgentBootCallback: {
            /**
             * Format: uuid
             * @description The deployment the engine booted for backend to register.
             */
            deploymentId?: string;
            /**
             * Format: uri
             * @description Externally reachable HTTP(S) URL of the engine. Optional — Cloud-mode engines behind NAT may omit this; the backend then stores the address as SQL NULL and rejects push deploys for this agent, while bundle deploys and liveness still work.
             * @example http://10.0.1.50:8081
             */
            address?: string;
            /**
             * @description Boot result reported by the engine. 'online' when the manifest loaded cleanly and the engine is ready to accept deploy requests; 'booterror' when something blocked startup (missing driver, invalid manifest, etc.).
             * @enum {string}
             */
            status: "online" | "booterror";
            /** @description The manifest the engine loaded into its driver registry at boot. Set on a successful boot; may be null on booterror if the engine could not even parse the manifest. */
            loadedDeviceManifest?: components["schemas"]["DeviceManifest"];
            /** @description Human-readable failure detail. Set when status='booterror', null otherwise. */
            error?: string | null;
        };
        AgentHeartbeatRequest: {
            /**
             * Format: uri
             * @description Externally reachable HTTP(S) URL of the engine. Optional — Cloud-mode engines behind NAT may omit this; the heartbeat then only refreshes liveness via the AgentKeyAuth middleware without writing the address column.
             * @example http://10.0.1.50:8081/
             */
            address?: string;
        };
        /** @description Body of PUT /agents/memory/{name}. */
        MemoryFileWrite: {
            content: string;
        };
        RagQueryRequest: {
            /** @description Collection to query */
            collectionId: string;
            /** @description Search query text */
            query: string;
            /**
             * @description Number of results to return
             * @default 5
             */
            topK: number;
        };
        RagQueryResult: {
            chunkId: string;
            documentId: string;
            content: string;
            /** Format: double */
            score: number;
        };
        NodePosition: {
            x: number;
            y: number;
        };
        /** @enum {string} */
        SignalType: "digital" | "analog";
        Reference: {
            srcId: string;
            varId: string;
        };
        OutputBinding: {
            /** @description Discard the output if false; route it according to `mode` if true */
            active: boolean;
            /** @enum {string} */
            mode: "emit" | "assign";
            /** @description Variable name (when mode=emit) */
            name?: string;
            /** @description Existing variable to route to (when mode=assign) */
            target?: components["schemas"]["Reference"];
        };
        ReadPinNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ReadPin";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to an IO variable ID */
                pinReference?: string;
                signalType: components["schemas"]["SignalType"];
                output: components["schemas"]["OutputBinding"];
                /** @description Description exposed to the LLM when this node is wired as a tool. Ignored in exec mode. */
                toolDescription?: string;
            };
        };
        /** @enum {string} */
        DataType: "int" | "float" | "bool" | "string";
        Expression: {
            expression: string;
            /** @description A list of referenced variable IDs used in the expression */
            references: components["schemas"]["Reference"][];
            dataType: components["schemas"]["DataType"];
        };
        WritePinNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WritePin";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to an IO variable ID */
                pinReference?: string;
                signalType: components["schemas"]["SignalType"];
                value: components["schemas"]["Expression"];
            };
        };
        OutputDeclaration: {
            /** @enum {string} */
            mode: "emit" | "assign";
            /** @description JSON property name of the declared output */
            name: string;
            dataType: components["schemas"]["DataType"];
            /** @description New variable uid (when mode=emit) */
            uid?: string;
            /** @description Existing variable to route to (when mode=assign) */
            target?: components["schemas"]["Reference"];
        };
        /** @description Reference from an LLM agent node to a declared MemoryFile with an access mode. */
        MemoryRef: {
            /** @description id of the referenced MemoryFile. */
            id: string;
            /**
             * @description r = read-only; rw = read + write.
             * @enum {string}
             */
            mode: "r" | "rw";
        };
        AgentNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Agent";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Name of the agent */
                name?: string;
                model?: string;
                instructions?: string;
                /** @description Maximum number of agent runner turns */
                maxTurns?: number;
                answer: components["schemas"]["OutputBinding"];
                /** @description Ordered list of structured-output declarations. Names must be unique within this list */
                outputDeclarations: components["schemas"]["OutputDeclaration"][];
                /** @description Memory files this agent can access, each with an access mode. */
                memoryRefs: components["schemas"]["MemoryRef"][];
                /** @description Description exposed to the LLM when this node is wired as a tool. Ignored in exec mode. */
                toolDescription?: string;
            };
        };
        IfNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "If";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                condition: components["schemas"]["Expression"];
            };
        };
        SerialReadNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SerialRead";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to an UART ID (the serial port to read from) */
                portReference?: string;
                prompt?: string;
                output: components["schemas"]["OutputBinding"];
            };
        };
        SerialWriteNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SerialWrite";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to a UART channel ID (the serial port to write to) */
                portReference?: string;
                value: components["schemas"]["Expression"];
            };
        };
        RetrieverNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Retriever";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to a declared VectorDatabase memory id */
                memoryReference?: string;
                /** @description Number of results to return */
                topK?: number;
                /** @description Search query expression */
                query: components["schemas"]["Expression"];
                output: components["schemas"]["OutputBinding"];
                /** @description Description exposed to the LLM when this node is wired as a tool. Ignored in exec mode. */
                toolDescription?: string;
            };
        };
        WebFetchNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WebFetch";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description URL expression to fetch (http or https) */
                url: components["schemas"]["Expression"];
                /** @description Maximum characters of extracted text to return. Defaults to 50000 when omitted or non-positive. */
                maxChars?: number;
                output: components["schemas"]["OutputBinding"];
            };
        };
        FunctionCallNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "FunctionCall";
            label?: string;
            position: components["schemas"]["NodePosition"];
            /** @description Id of the function this node calls. The signature is resolved from the workflow's functions table. */
            functionId: string;
            arguments: {
                inputBindings?: {
                    [key: string]: components["schemas"]["Expression"];
                };
                outputBindings?: {
                    [key: string]: components["schemas"]["OutputBinding"];
                };
                /** @description Description exposed to the LLM when this function is wired as a tool. Ignored in exec mode. */
                toolDescription?: string;
            };
        };
        OnFunctionCallNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OnFunctionCall";
            label?: string;
            position: components["schemas"]["NodePosition"];
        };
        DelayNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Delay";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Time in milliseconds to pause execution */
                delayMs?: number;
            };
        };
        TickerNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Ticker";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description How many units between ticks */
                intervalValue?: number;
                /**
                 * @description Time unit for the interval
                 * @enum {string}
                 */
                intervalUnit: "milliseconds" | "seconds" | "minutes" | "hours";
            };
        };
        AlarmNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Alarm";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Time of day to fire (HH:MM, 24h format) */
                time?: string;
                /** @description Days of the week to fire on (empty = every day) */
                days: string[];
            };
        };
        WebSearchToolNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WebSearchTool";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Maximum number of search results to return per call. Defaults to 5 when omitted or non-positive. Capped at 20. */
                maxResults?: number;
            };
        };
        OnStartupNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OnStartup";
            label?: string;
            position: components["schemas"]["NodePosition"];
        };
        OnPinEdgeNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OnPinEdge";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description IO variable ID of the digital pin to watch */
                pinReference?: string;
                /**
                 * @description Edge transition that fires the trigger
                 * @enum {string}
                 */
                edge: "rising" | "falling" | "both";
            };
        };
        OnSerialReceiveNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OnSerialReceive";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to an IO variable ID (the serial port to listen on) */
                portReference?: string;
                output: components["schemas"]["OutputBinding"];
            };
        };
        OnThresholdNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OnThreshold";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Numeric variable to watch for threshold crossings */
                variable?: components["schemas"]["Reference"];
                /** @description Value the variable crosses to fire the trigger */
                threshold?: number;
                /**
                 * @description Crossing direction to fire on (default both)
                 * @enum {string}
                 */
                direction: "rising" | "falling" | "both";
                /** @description Hysteresis band width around threshold; 0 disables (default 0) */
                deadband?: number;
                /** @description Optional binding for the triggering value */
                output: components["schemas"]["OutputBinding"];
            };
        };
        SetVariableNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SetVariable";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                variable?: components["schemas"]["Reference"];
                value: components["schemas"]["Expression"];
            };
        };
        MqttPublishNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MqttPublish";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to an MQTT channel ID (the channel carries the topic; resolved to a broker at deploy time) */
                channelReference?: string;
                dataType: components["schemas"]["DataType"];
                value: components["schemas"]["Expression"];
                /**
                 * @description MQTT Quality of Service level
                 * @enum {integer}
                 */
                qos: 0 | 1 | 2;
                /** @description Whether the broker should retain the message */
                retain: boolean;
            };
        };
        OnMqttMessageNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OnMqttMessage";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to an MQTT channel ID (the channel carries the topic filter; resolved to a broker at deploy time) */
                channelReference?: string;
                dataType: components["schemas"]["DataType"];
                output: components["schemas"]["OutputBinding"];
            };
        };
        Node: components["schemas"]["ReadPinNode"] | components["schemas"]["WritePinNode"] | components["schemas"]["AgentNode"] | components["schemas"]["IfNode"] | components["schemas"]["SerialReadNode"] | components["schemas"]["SerialWriteNode"] | components["schemas"]["RetrieverNode"] | components["schemas"]["WebFetchNode"] | components["schemas"]["FunctionCallNode"] | components["schemas"]["OnFunctionCallNode"] | components["schemas"]["DelayNode"] | components["schemas"]["TickerNode"] | components["schemas"]["AlarmNode"] | components["schemas"]["WebSearchToolNode"] | components["schemas"]["OnStartupNode"] | components["schemas"]["OnPinEdgeNode"] | components["schemas"]["OnSerialReceiveNode"] | components["schemas"]["OnThresholdNode"] | components["schemas"]["SetVariableNode"] | components["schemas"]["MqttPublishNode"] | components["schemas"]["OnMqttMessageNode"];
        /** @enum {string} */
        EdgeType: "control" | "tool" | "agentTask" | "agentChoice" | "agentDelegate";
        Vertex: {
            nodeId: string;
            port: string;
        };
        Edge: {
            id: string;
            type: components["schemas"]["EdgeType"];
            from: components["schemas"]["Vertex"];
            to: components["schemas"]["Vertex"];
            /** @description Prompt expression sent to the agent. Present on `agentTask` (required) and `agentDelegate` (optional). */
            prompt?: components["schemas"]["Expression"];
            /** @description LLM-readable explanation of when the edge should fire. Present on `agentChoice` and `agentDelegate`. */
            description?: string;
        };
        /** @description A named, typed variable with a stable uid that can be referenced throughout the workflow. */
        Variable: {
            /** @description Stable identifier that survives renames */
            uid: string;
            name: string;
            dataType: components["schemas"]["DataType"];
            /** @description Initial value matching the dataType (number, boolean, or string). Only used by declared variables. */
            initialValue?: unknown;
        };
        FunctionInfo: {
            id: string;
            /** Format: int32 */
            version: number;
            name: string;
            arguments: components["schemas"]["Variable"][];
            returns: components["schemas"]["Variable"][];
        };
        Function: {
            functionInfo: components["schemas"]["FunctionInfo"];
            /** @description Maps return variable uid to its Expression */
            outputAssignments: {
                [key: string]: components["schemas"]["Expression"];
            };
            nodes: components["schemas"]["Node"][];
            edges: components["schemas"]["Edge"][];
            declaredVariables: components["schemas"]["Variable"][];
        };
        GPIOINChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "GPIOIN";
            id: string;
            label: string;
            /**
             * @description Pin bias configuration
             * @enum {string}
             */
            bias: "none" | "pullup" | "pulldown";
            /** @description Debounce window in milliseconds */
            debounceMs: number;
        };
        GPIOOUTChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "GPIOOUT";
            id: string;
            label: string;
        };
        ADCChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ADC";
            id: string;
            label: string;
        };
        PWMChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "PWM";
            id: string;
            label: string;
            /** @description PWM frequency in Hz */
            frequency: number;
        };
        DACChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DAC";
            id: string;
            label: string;
        };
        UARTChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "UART";
            id: string;
            label: string;
        };
        MQTTChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MQTT";
            id: string;
            label: string;
            /** @description Topic this channel publishes to / subscribes on. The engine wraps it with the bound broker's prefix at runtime. */
            topic: string;
        };
        Channel: components["schemas"]["GPIOINChannel"] | components["schemas"]["GPIOOUTChannel"] | components["schemas"]["ADCChannel"] | components["schemas"]["PWMChannel"] | components["schemas"]["DACChannel"] | components["schemas"]["UARTChannel"] | components["schemas"]["MQTTChannel"];
        /** @description One .md file that agent nodes can read and write to. */
        MemoryFile: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MemoryFile";
            /** @description Stable identifier that survives renames; referenced from MemoryRef. */
            id: string;
            /** @description Display name. Unique per agent (LLM tool enums use it). */
            label: string;
            description: string;
            content: string;
            /** @description Byte cap; null means unlimited. */
            maxSizeBytes?: number | null;
        };
        /** @description A vector database for retrieval-augmented generation (RAG). */
        VectorDatabase: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "VectorDatabase";
            /** @description Stable identifier; referenced from Retriever nodes. */
            id: string;
            /** @description Display name. */
            label: string;
            description?: string;
        };
        Memory: components["schemas"]["MemoryFile"] | components["schemas"]["VectorDatabase"];
        /** @enum {string} */
        ModelCapability: "chat" | "embedding" | "function_call" | "vision" | "fine_tuning" | "reasoning" | "classification" | "code";
        /** @description A custom or self-hosted language model that agent nodes can reference. */
        LLMModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "LLMModel";
            /** @description Stable identifier; this is the ModelID nodes reference. */
            id: string;
            /** @description Display name. */
            label: string;
            /** @description Capabilities this model supports (used to filter model pickers). */
            capabilities: components["schemas"]["ModelCapability"][];
        };
        Model: components["schemas"]["LLMModel"];
        /** @description Workflow represents the deployment format of a project, passed to agents. */
        Workflow: {
            /**
             * Format: int32
             * @description Monotonic version of the persisted workflow format, bumped when the serialized shape changes.
             */
            schemaVersion: number;
            nodes: components["schemas"]["Node"][];
            edges: components["schemas"]["Edge"][];
            functions: components["schemas"]["Function"][];
            declaredVariables: components["schemas"]["Variable"][];
            channels: components["schemas"]["Channel"][];
            memory: components["schemas"]["Memory"][];
            /** @description Declared custom/self-hosted models; referenced from nodes by id. Static catalog models need no declaration. */
            models: components["schemas"]["Model"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current runner state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    deploy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployRequest"];
            };
        };
        responses: {
            /** @description Workflow deployed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request (e.g. missing workflow). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineError"];
                };
            };
            /** @description Build failure. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineError"];
                };
            };
        };
    };
    stop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runner stopped. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
