/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capture one frame from a configured device, selected by name.
         * @description Reads a single frame from the named device. Unknown name yields 404; a capture failure yields 500.
         */
        get: operations["capture"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness — the process is up.
         * @description Always 200 while the process is alive; use /readyz for config state.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness — the device configuration finished loading.
         * @description 200 once the configuration is loaded; 503 while still loading or empty.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the configured cameras.
         * @description Names every configured camera — the valid /capture name selectors.
         */
        get: operations["metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The set of configured cameras. */
        CameraMetadata: {
            /** @description Every configured camera. */
            devices: components["schemas"]["DeviceMetadata"][];
        };
        /** @description Descriptive metadata for one configured camera. */
        DeviceMetadata: {
            /** @description Name (id) of the camera — the /capture name selector. */
            name: string;
            /** @description Optional human-readable device description. */
            description?: string;
        };
        /** @description The camera component's boot config (cameras.json): the set of cameras one shared camera component owns. The renderer writes it into the component's config file; the component reads it at boot — a cross-language seam. Each /capture request selects a camera by its key here. Not on the HTTP wire; the component's boot input, carried here so the renderer (producer) and component (consumer) share one generated shape. */
        CameraConfig: {
            /** @description Configured cameras keyed by name — the /capture `name` selector. */
            cameras: {
                [key: string]: components["schemas"]["CameraSource"];
            };
        };
        /** @description One camera's capture source in cameras.json. */
        CameraSource: {
            /** @description Capture backend: `v4l2` (a /dev/video* device) or `gstreamer` (a source element, e.g. libcamerasrc). Determines how `device` is interpreted. */
            source: string;
            /** @description The capture source: a /dev/video* path (v4l2) or a GStreamer source fragment (gstreamer). */
            device: string;
            /** @description Leading frames to discard so a sensor's auto-exposure can settle before the returned one. Default 0. */
            warmupFrames?: number;
            /** @description Shell commands (media-ctl/v4l2-ctl) the component replays on every container start, for statically configured CSI/ISP pipelines. */
            setup?: string[];
        };
        /** @description A simple health-probe response. */
        Health: {
            /** @description Probe status (e.g. ok, loading). */
            status: string;
        };
        /** @description A structured error response. */
        Error: {
            /** @description Human-readable error description. */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capture: {
        parameters: {
            query: {
                /** @description Name of the configured device to read (see /metadata). */
                name: string;
                /** @description Optional width hint in pixels; ignored by sources that lack it. */
                width?: number;
                /** @description Optional height hint in pixels; ignored by sources that lack it. */
                height?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encoded captured frame (opaque binary; the concrete Content-Type is set by the server, e.g. image/jpeg for a camera server). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description No device with the requested name is configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The device failed to capture a frame. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The configuration is loaded and capture can be served. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The configuration is not yet loaded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    metadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The component's configured cameras. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraMetadata"];
                };
            };
        };
    };
}
