// Package workflow provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package workflow

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ADCChannelType.
const (
	ADC ADCChannelType = "ADC"
)

// Valid indicates whether the value is a known member of the ADCChannelType enum.
func (e ADCChannelType) Valid() bool {
	switch e {
	case ADC:
		return true
	default:
		return false
	}
}

// Defines values for AgentNodeType.
const (
	Agent AgentNodeType = "Agent"
)

// Valid indicates whether the value is a known member of the AgentNodeType enum.
func (e AgentNodeType) Valid() bool {
	switch e {
	case Agent:
		return true
	default:
		return false
	}
}

// Defines values for AlarmNodeType.
const (
	Alarm AlarmNodeType = "Alarm"
)

// Valid indicates whether the value is a known member of the AlarmNodeType enum.
func (e AlarmNodeType) Valid() bool {
	switch e {
	case Alarm:
		return true
	default:
		return false
	}
}

// Defines values for DACChannelType.
const (
	DAC DACChannelType = "DAC"
)

// Valid indicates whether the value is a known member of the DACChannelType enum.
func (e DACChannelType) Valid() bool {
	switch e {
	case DAC:
		return true
	default:
		return false
	}
}

// Defines values for DataType.
const (
	Bool   DataType = "bool"
	Float  DataType = "float"
	Int    DataType = "int"
	String DataType = "string"
)

// Valid indicates whether the value is a known member of the DataType enum.
func (e DataType) Valid() bool {
	switch e {
	case Bool:
		return true
	case Float:
		return true
	case Int:
		return true
	case String:
		return true
	default:
		return false
	}
}

// Defines values for DelayNodeType.
const (
	Delay DelayNodeType = "Delay"
)

// Valid indicates whether the value is a known member of the DelayNodeType enum.
func (e DelayNodeType) Valid() bool {
	switch e {
	case Delay:
		return true
	default:
		return false
	}
}

// Defines values for EdgeType.
const (
	AgentChoice   EdgeType = "agentChoice"
	AgentDelegate EdgeType = "agentDelegate"
	AgentTask     EdgeType = "agentTask"
	Control       EdgeType = "control"
	Tool          EdgeType = "tool"
)

// Valid indicates whether the value is a known member of the EdgeType enum.
func (e EdgeType) Valid() bool {
	switch e {
	case AgentChoice:
		return true
	case AgentDelegate:
		return true
	case AgentTask:
		return true
	case Control:
		return true
	case Tool:
		return true
	default:
		return false
	}
}

// Defines values for FunctionCallNodeType.
const (
	FunctionCall FunctionCallNodeType = "FunctionCall"
)

// Valid indicates whether the value is a known member of the FunctionCallNodeType enum.
func (e FunctionCallNodeType) Valid() bool {
	switch e {
	case FunctionCall:
		return true
	default:
		return false
	}
}

// Defines values for GPIOINChannelBias.
const (
	None     GPIOINChannelBias = "none"
	Pulldown GPIOINChannelBias = "pulldown"
	Pullup   GPIOINChannelBias = "pullup"
)

// Valid indicates whether the value is a known member of the GPIOINChannelBias enum.
func (e GPIOINChannelBias) Valid() bool {
	switch e {
	case None:
		return true
	case Pulldown:
		return true
	case Pullup:
		return true
	default:
		return false
	}
}

// Defines values for GPIOINChannelType.
const (
	GPIOIN GPIOINChannelType = "GPIOIN"
)

// Valid indicates whether the value is a known member of the GPIOINChannelType enum.
func (e GPIOINChannelType) Valid() bool {
	switch e {
	case GPIOIN:
		return true
	default:
		return false
	}
}

// Defines values for GPIOOUTChannelType.
const (
	GPIOOUT GPIOOUTChannelType = "GPIOOUT"
)

// Valid indicates whether the value is a known member of the GPIOOUTChannelType enum.
func (e GPIOOUTChannelType) Valid() bool {
	switch e {
	case GPIOOUT:
		return true
	default:
		return false
	}
}

// Defines values for IfNodeType.
const (
	If IfNodeType = "If"
)

// Valid indicates whether the value is a known member of the IfNodeType enum.
func (e IfNodeType) Valid() bool {
	switch e {
	case If:
		return true
	default:
		return false
	}
}

// Defines values for MQTTChannelType.
const (
	MQTT MQTTChannelType = "MQTT"
)

// Valid indicates whether the value is a known member of the MQTTChannelType enum.
func (e MQTTChannelType) Valid() bool {
	switch e {
	case MQTT:
		return true
	default:
		return false
	}
}

// Defines values for MemoryRefMode.
const (
	R  MemoryRefMode = "r"
	Rw MemoryRefMode = "rw"
)

// Valid indicates whether the value is a known member of the MemoryRefMode enum.
func (e MemoryRefMode) Valid() bool {
	switch e {
	case R:
		return true
	case Rw:
		return true
	default:
		return false
	}
}

// Defines values for MqttPublishNodeArgumentsQos.
const (
	N0 MqttPublishNodeArgumentsQos = 0
	N1 MqttPublishNodeArgumentsQos = 1
	N2 MqttPublishNodeArgumentsQos = 2
)

// Valid indicates whether the value is a known member of the MqttPublishNodeArgumentsQos enum.
func (e MqttPublishNodeArgumentsQos) Valid() bool {
	switch e {
	case N0:
		return true
	case N1:
		return true
	case N2:
		return true
	default:
		return false
	}
}

// Defines values for MqttPublishNodeType.
const (
	MqttPublish MqttPublishNodeType = "MqttPublish"
)

// Valid indicates whether the value is a known member of the MqttPublishNodeType enum.
func (e MqttPublishNodeType) Valid() bool {
	switch e {
	case MqttPublish:
		return true
	default:
		return false
	}
}

// Defines values for OnFunctionCallNodeType.
const (
	OnFunctionCall OnFunctionCallNodeType = "OnFunctionCall"
)

// Valid indicates whether the value is a known member of the OnFunctionCallNodeType enum.
func (e OnFunctionCallNodeType) Valid() bool {
	switch e {
	case OnFunctionCall:
		return true
	default:
		return false
	}
}

// Defines values for OnMqttMessageNodeType.
const (
	OnMqttMessage OnMqttMessageNodeType = "OnMqttMessage"
)

// Valid indicates whether the value is a known member of the OnMqttMessageNodeType enum.
func (e OnMqttMessageNodeType) Valid() bool {
	switch e {
	case OnMqttMessage:
		return true
	default:
		return false
	}
}

// Defines values for OnPinEdgeNodeArgumentsEdge.
const (
	OnPinEdgeNodeArgumentsEdgeBoth    OnPinEdgeNodeArgumentsEdge = "both"
	OnPinEdgeNodeArgumentsEdgeFalling OnPinEdgeNodeArgumentsEdge = "falling"
	OnPinEdgeNodeArgumentsEdgeRising  OnPinEdgeNodeArgumentsEdge = "rising"
)

// Valid indicates whether the value is a known member of the OnPinEdgeNodeArgumentsEdge enum.
func (e OnPinEdgeNodeArgumentsEdge) Valid() bool {
	switch e {
	case OnPinEdgeNodeArgumentsEdgeBoth:
		return true
	case OnPinEdgeNodeArgumentsEdgeFalling:
		return true
	case OnPinEdgeNodeArgumentsEdgeRising:
		return true
	default:
		return false
	}
}

// Defines values for OnPinEdgeNodeType.
const (
	OnPinEdge OnPinEdgeNodeType = "OnPinEdge"
)

// Valid indicates whether the value is a known member of the OnPinEdgeNodeType enum.
func (e OnPinEdgeNodeType) Valid() bool {
	switch e {
	case OnPinEdge:
		return true
	default:
		return false
	}
}

// Defines values for OnSerialReceiveNodeType.
const (
	OnSerialReceive OnSerialReceiveNodeType = "OnSerialReceive"
)

// Valid indicates whether the value is a known member of the OnSerialReceiveNodeType enum.
func (e OnSerialReceiveNodeType) Valid() bool {
	switch e {
	case OnSerialReceive:
		return true
	default:
		return false
	}
}

// Defines values for OnStartupNodeType.
const (
	OnStartup OnStartupNodeType = "OnStartup"
)

// Valid indicates whether the value is a known member of the OnStartupNodeType enum.
func (e OnStartupNodeType) Valid() bool {
	switch e {
	case OnStartup:
		return true
	default:
		return false
	}
}

// Defines values for OnThresholdNodeArgumentsDirection.
const (
	OnThresholdNodeArgumentsDirectionBoth    OnThresholdNodeArgumentsDirection = "both"
	OnThresholdNodeArgumentsDirectionFalling OnThresholdNodeArgumentsDirection = "falling"
	OnThresholdNodeArgumentsDirectionRising  OnThresholdNodeArgumentsDirection = "rising"
)

// Valid indicates whether the value is a known member of the OnThresholdNodeArgumentsDirection enum.
func (e OnThresholdNodeArgumentsDirection) Valid() bool {
	switch e {
	case OnThresholdNodeArgumentsDirectionBoth:
		return true
	case OnThresholdNodeArgumentsDirectionFalling:
		return true
	case OnThresholdNodeArgumentsDirectionRising:
		return true
	default:
		return false
	}
}

// Defines values for OnThresholdNodeType.
const (
	OnThreshold OnThresholdNodeType = "OnThreshold"
)

// Valid indicates whether the value is a known member of the OnThresholdNodeType enum.
func (e OnThresholdNodeType) Valid() bool {
	switch e {
	case OnThreshold:
		return true
	default:
		return false
	}
}

// Defines values for OutputBindingMode.
const (
	OutputBindingModeAssign OutputBindingMode = "assign"
	OutputBindingModeEmit   OutputBindingMode = "emit"
)

// Valid indicates whether the value is a known member of the OutputBindingMode enum.
func (e OutputBindingMode) Valid() bool {
	switch e {
	case OutputBindingModeAssign:
		return true
	case OutputBindingModeEmit:
		return true
	default:
		return false
	}
}

// Defines values for OutputDeclarationMode.
const (
	OutputDeclarationModeAssign OutputDeclarationMode = "assign"
	OutputDeclarationModeEmit   OutputDeclarationMode = "emit"
)

// Valid indicates whether the value is a known member of the OutputDeclarationMode enum.
func (e OutputDeclarationMode) Valid() bool {
	switch e {
	case OutputDeclarationModeAssign:
		return true
	case OutputDeclarationModeEmit:
		return true
	default:
		return false
	}
}

// Defines values for PWMChannelType.
const (
	PWM PWMChannelType = "PWM"
)

// Valid indicates whether the value is a known member of the PWMChannelType enum.
func (e PWMChannelType) Valid() bool {
	switch e {
	case PWM:
		return true
	default:
		return false
	}
}

// Defines values for ReadPinNodeType.
const (
	ReadPin ReadPinNodeType = "ReadPin"
)

// Valid indicates whether the value is a known member of the ReadPinNodeType enum.
func (e ReadPinNodeType) Valid() bool {
	switch e {
	case ReadPin:
		return true
	default:
		return false
	}
}

// Defines values for RetrieverNodeType.
const (
	Retriever RetrieverNodeType = "Retriever"
)

// Valid indicates whether the value is a known member of the RetrieverNodeType enum.
func (e RetrieverNodeType) Valid() bool {
	switch e {
	case Retriever:
		return true
	default:
		return false
	}
}

// Defines values for SerialReadNodeType.
const (
	SerialRead SerialReadNodeType = "SerialRead"
)

// Valid indicates whether the value is a known member of the SerialReadNodeType enum.
func (e SerialReadNodeType) Valid() bool {
	switch e {
	case SerialRead:
		return true
	default:
		return false
	}
}

// Defines values for SerialWriteNodeType.
const (
	SerialWrite SerialWriteNodeType = "SerialWrite"
)

// Valid indicates whether the value is a known member of the SerialWriteNodeType enum.
func (e SerialWriteNodeType) Valid() bool {
	switch e {
	case SerialWrite:
		return true
	default:
		return false
	}
}

// Defines values for SetVariableNodeType.
const (
	SetVariable SetVariableNodeType = "SetVariable"
)

// Valid indicates whether the value is a known member of the SetVariableNodeType enum.
func (e SetVariableNodeType) Valid() bool {
	switch e {
	case SetVariable:
		return true
	default:
		return false
	}
}

// Defines values for SignalType.
const (
	Analog  SignalType = "analog"
	Digital SignalType = "digital"
)

// Valid indicates whether the value is a known member of the SignalType enum.
func (e SignalType) Valid() bool {
	switch e {
	case Analog:
		return true
	case Digital:
		return true
	default:
		return false
	}
}

// Defines values for TickerNodeArgumentsIntervalUnit.
const (
	Hours        TickerNodeArgumentsIntervalUnit = "hours"
	Milliseconds TickerNodeArgumentsIntervalUnit = "milliseconds"
	Minutes      TickerNodeArgumentsIntervalUnit = "minutes"
	Seconds      TickerNodeArgumentsIntervalUnit = "seconds"
)

// Valid indicates whether the value is a known member of the TickerNodeArgumentsIntervalUnit enum.
func (e TickerNodeArgumentsIntervalUnit) Valid() bool {
	switch e {
	case Hours:
		return true
	case Milliseconds:
		return true
	case Minutes:
		return true
	case Seconds:
		return true
	default:
		return false
	}
}

// Defines values for TickerNodeType.
const (
	Ticker TickerNodeType = "Ticker"
)

// Valid indicates whether the value is a known member of the TickerNodeType enum.
func (e TickerNodeType) Valid() bool {
	switch e {
	case Ticker:
		return true
	default:
		return false
	}
}

// Defines values for UARTChannelType.
const (
	UART UARTChannelType = "UART"
)

// Valid indicates whether the value is a known member of the UARTChannelType enum.
func (e UARTChannelType) Valid() bool {
	switch e {
	case UART:
		return true
	default:
		return false
	}
}

// Defines values for WebFetchNodeType.
const (
	WebFetch WebFetchNodeType = "WebFetch"
)

// Valid indicates whether the value is a known member of the WebFetchNodeType enum.
func (e WebFetchNodeType) Valid() bool {
	switch e {
	case WebFetch:
		return true
	default:
		return false
	}
}

// Defines values for WebSearchToolNodeType.
const (
	WebSearchTool WebSearchToolNodeType = "WebSearchTool"
)

// Valid indicates whether the value is a known member of the WebSearchToolNodeType enum.
func (e WebSearchToolNodeType) Valid() bool {
	switch e {
	case WebSearchTool:
		return true
	default:
		return false
	}
}

// Defines values for WritePinNodeType.
const (
	WritePin WritePinNodeType = "WritePin"
)

// Valid indicates whether the value is a known member of the WritePinNodeType enum.
func (e WritePinNodeType) Valid() bool {
	switch e {
	case WritePin:
		return true
	default:
		return false
	}
}

// ADCChannel defines model for ADCChannel.
type ADCChannel struct {
	// Channel Channel number on the ADC device
	Channel int `json:"channel"`

	// DriverID Driver instance ID from the device manifest
	DriverID string         `json:"driverId"`
	Id       string         `json:"id"`
	Label    string         `json:"label"`
	Type     ADCChannelType `json:"type"`
}

// ADCChannelType defines model for ADCChannel.Type.
type ADCChannelType string

// AgentNode defines model for AgentNode.
type AgentNode struct {
	Arguments struct {
		Answer       OutputBinding `json:"answer"`
		Instructions *string       `json:"instructions,omitempty"`

		// MaxTurns Maximum number of agent runner turns
		MaxTurns *int `json:"maxTurns,omitempty"`

		// MemoryRefs Memory files this agent can access, each with an access mode.
		MemoryRefs []MemoryRef `json:"memoryRefs"`
		Model      string      `json:"model"`

		// Name Name of the agent
		Name string `json:"name"`

		// OutputDeclarations Ordered list of structured-output declarations. Names must be unique within this list
		OutputDeclarations []OutputDeclaration `json:"outputDeclarations"`

		// ToolDescription Description exposed to the LLM when this node is wired as a tool. Ignored in exec mode.
		ToolDescription *string `json:"toolDescription,omitempty"`
	} `json:"arguments"`
	Id       string        `json:"id"`
	Label    *string       `json:"label,omitempty"`
	Position NodePosition  `json:"position"`
	Type     AgentNodeType `json:"type"`
}

// AgentNodeType defines model for AgentNode.Type.
type AgentNodeType string

// AlarmNode defines model for AlarmNode.
type AlarmNode struct {
	Arguments struct {
		// Days Days of the week to fire on (empty = every day)
		Days *[]string `json:"days,omitempty"`

		// Time Time of day to fire (HH:MM, 24h format)
		Time string `json:"time"`
	} `json:"arguments"`
	Id       string        `json:"id"`
	Label    *string       `json:"label,omitempty"`
	Position NodePosition  `json:"position"`
	Type     AlarmNodeType `json:"type"`
}

// AlarmNodeType defines model for AlarmNode.Type.
type AlarmNodeType string

// Channel defines model for Channel.
type Channel struct {
	union json.RawMessage
}

// DACChannel defines model for DACChannel.
type DACChannel struct {
	// Channel Channel number on the DAC device
	Channel int `json:"channel"`

	// DriverID Driver instance ID from the device manifest
	DriverID string         `json:"driverId"`
	Id       string         `json:"id"`
	Label    string         `json:"label"`
	Type     DACChannelType `json:"type"`
}

// DACChannelType defines model for DACChannel.Type.
type DACChannelType string

// DataType defines model for DataType.
type DataType string

// DelayNode defines model for DelayNode.
type DelayNode struct {
	Arguments struct {
		// DelayMs Time in milliseconds to pause execution
		DelayMs int `json:"delayMs"`
	} `json:"arguments"`
	Id       string        `json:"id"`
	Label    *string       `json:"label,omitempty"`
	Position NodePosition  `json:"position"`
	Type     DelayNodeType `json:"type"`
}

// DelayNodeType defines model for DelayNode.Type.
type DelayNodeType string

// Edge defines model for Edge.
type Edge struct {
	// Description LLM-readable explanation of when the edge should fire. Present on `agentChoice` and `agentDelegate`.
	Description *string     `json:"description,omitempty"`
	From        Vertex      `json:"from"`
	Prompt      *Expression `json:"prompt,omitempty"`
	To          Vertex      `json:"to"`
	Type        EdgeType    `json:"type"`
}

// EdgeType defines model for EdgeType.
type EdgeType string

// Expression defines model for Expression.
type Expression struct {
	DataType   DataType `json:"dataType"`
	Expression string   `json:"expression"`

	// References A list of referenced variable IDs used in the expression
	References []Reference `json:"references"`
}

// Function defines model for Function.
type Function struct {
	DeclaredVariables []Variable   `json:"declaredVariables"`
	Edges             []Edge       `json:"edges"`
	FunctionInfo      FunctionInfo `json:"functionInfo"`
	Nodes             []Node       `json:"nodes"`

	// OutputAssignments Maps return variable uid to its Expression
	OutputAssignments map[string]Expression `json:"outputAssignments"`
}

// FunctionCallNode defines model for FunctionCallNode.
type FunctionCallNode struct {
	Arguments struct {
		InputBindings  map[string]Expression    `json:"inputBindings"`
		OutputBindings map[string]OutputBinding `json:"outputBindings"`

		// ToolDescription Description exposed to the LLM when this function is wired as a tool. Ignored in exec mode.
		ToolDescription *string `json:"toolDescription,omitempty"`
	} `json:"arguments"`
	FunctionInfo FunctionInfo         `json:"functionInfo"`
	Id           string               `json:"id"`
	Label        *string              `json:"label,omitempty"`
	Position     NodePosition         `json:"position"`
	Type         FunctionCallNodeType `json:"type"`
}

// FunctionCallNodeType defines model for FunctionCallNode.Type.
type FunctionCallNodeType string

// FunctionInfo defines model for FunctionInfo.
type FunctionInfo struct {
	Arguments []Variable `json:"arguments"`
	Id        string     `json:"id"`
	Name      string     `json:"name"`
	Returns   []Variable `json:"returns"`
	Version   int32      `json:"version"`
}

// GPIOINChannel defines model for GPIOINChannel.
type GPIOINChannel struct {
	// Bias Pin bias configuration
	Bias GPIOINChannelBias `json:"bias"`

	// DebounceMs Debounce window in milliseconds
	DebounceMs int `json:"debounceMs"`

	// DriverID Driver instance ID from the device manifest
	DriverID string `json:"driverId"`
	Id       string `json:"id"`
	Label    string `json:"label"`

	// Line Line number on the GPIO chip
	Line int               `json:"line"`
	Type GPIOINChannelType `json:"type"`
}

// GPIOINChannelBias Pin bias configuration
type GPIOINChannelBias string

// GPIOINChannelType defines model for GPIOINChannel.Type.
type GPIOINChannelType string

// GPIOOUTChannel defines model for GPIOOUTChannel.
type GPIOOUTChannel struct {
	// DriverID Driver instance ID from the device manifest
	DriverID string `json:"driverId"`
	Id       string `json:"id"`
	Label    string `json:"label"`

	// Line Line number on the GPIO chip
	Line int                `json:"line"`
	Type GPIOOUTChannelType `json:"type"`
}

// GPIOOUTChannelType defines model for GPIOOUTChannel.Type.
type GPIOOUTChannelType string

// IfNode defines model for IfNode.
type IfNode struct {
	Arguments struct {
		Condition Expression `json:"condition"`
	} `json:"arguments"`
	Id       string       `json:"id"`
	Label    *string      `json:"label,omitempty"`
	Position NodePosition `json:"position"`
	Type     IfNodeType   `json:"type"`
}

// IfNodeType defines model for IfNode.Type.
type IfNodeType string

// MQTTChannel defines model for MQTTChannel.
type MQTTChannel struct {
	Id    string `json:"id"`
	Label string `json:"label"`

	// NetworkID ID of a network the agent's device must be a member of.
	NetworkID string          `json:"networkId"`
	Type      MQTTChannelType `json:"type"`
}

// MQTTChannelType defines model for MQTTChannel.Type.
type MQTTChannelType string

// MemoryFile One memory file. On a workflow declaration `content` is the seed (existing rows keep their content on redeploy); on a snapshot read it's the current durable content.
type MemoryFile struct {
	Content     string `json:"content"`
	Description string `json:"description"`

	// MaxSizeBytes Byte cap; null means unlimited.
	MaxSizeBytes *int `json:"maxSizeBytes,omitempty"`

	// Name Display name. Unique per agent (LLM tool enums use it).
	Name string `json:"name"`

	// UID Stable identifier that survives renames; referenced from MemoryRef.
	UID string `json:"uid"`
}

// MemoryRef Reference from an LLM agent node to a declared memory file with an access mode.
type MemoryRef struct {
	// Mode r = read-only; rw = read + write.
	Mode MemoryRefMode `json:"mode"`

	// Uid UID of the referenced MemoryFile.
	Uid string `json:"uid"`
}

// MemoryRefMode r = read-only; rw = read + write.
type MemoryRefMode string

// MqttPublishNode defines model for MqttPublishNode.
type MqttPublishNode struct {
	Arguments struct {
		// ChannelReference Reference to an MQTT channel ID (resolved to a network broker at deploy time)
		ChannelReference string   `json:"channelReference"`
		DataType         DataType `json:"dataType"`

		// Qos MQTT Quality of Service level
		Qos MqttPublishNodeArgumentsQos `json:"qos"`

		// Retain Whether the broker should retain the message
		Retain bool `json:"retain"`

		// Topic Workflow-level topic path. Engine wraps with the channel's bound {networkId}/{agentId}/ prefix at runtime.
		Topic string     `json:"topic"`
		Value Expression `json:"value"`
	} `json:"arguments"`
	Id       string              `json:"id"`
	Label    *string             `json:"label,omitempty"`
	Position NodePosition        `json:"position"`
	Type     MqttPublishNodeType `json:"type"`
}

// MqttPublishNodeArgumentsQos MQTT Quality of Service level
type MqttPublishNodeArgumentsQos int

// MqttPublishNodeType defines model for MqttPublishNode.Type.
type MqttPublishNodeType string

// Node defines model for Node.
type Node struct {
	union json.RawMessage
}

// NodePosition defines model for NodePosition.
type NodePosition struct {
	X float32 `json:"x"`
	Y float32 `json:"y"`
}

// OnFunctionCallNode defines model for OnFunctionCallNode.
type OnFunctionCallNode struct {
	Id       string                 `json:"id"`
	Label    *string                `json:"label,omitempty"`
	Position NodePosition           `json:"position"`
	Type     OnFunctionCallNodeType `json:"type"`
}

// OnFunctionCallNodeType defines model for OnFunctionCallNode.Type.
type OnFunctionCallNodeType string

// OnMqttMessageNode defines model for OnMqttMessageNode.
type OnMqttMessageNode struct {
	Arguments struct {
		// ChannelReference Reference to an MQTT channel ID (resolved to a network broker at deploy time)
		ChannelReference string        `json:"channelReference"`
		DataType         DataType      `json:"dataType"`
		Output           OutputBinding `json:"output"`

		// Topic Workflow-level topic filter. Engine wraps with the channel's bound {networkId}/+/ prefix at runtime.
		Topic string `json:"topic"`
	} `json:"arguments"`
	Id       string                `json:"id"`
	Label    *string               `json:"label,omitempty"`
	Position NodePosition          `json:"position"`
	Type     OnMqttMessageNodeType `json:"type"`
}

// OnMqttMessageNodeType defines model for OnMqttMessageNode.Type.
type OnMqttMessageNodeType string

// OnPinEdgeNode defines model for OnPinEdgeNode.
type OnPinEdgeNode struct {
	Arguments struct {
		// Edge Edge transition that fires the trigger
		Edge OnPinEdgeNodeArgumentsEdge `json:"edge"`

		// PinReference IO variable ID of the digital pin to watch
		PinReference string `json:"pinReference"`
	} `json:"arguments"`
	Id       string            `json:"id"`
	Label    *string           `json:"label,omitempty"`
	Position NodePosition      `json:"position"`
	Type     OnPinEdgeNodeType `json:"type"`
}

// OnPinEdgeNodeArgumentsEdge Edge transition that fires the trigger
type OnPinEdgeNodeArgumentsEdge string

// OnPinEdgeNodeType defines model for OnPinEdgeNode.Type.
type OnPinEdgeNodeType string

// OnSerialReceiveNode defines model for OnSerialReceiveNode.
type OnSerialReceiveNode struct {
	Arguments struct {
		Output OutputBinding `json:"output"`

		// PortReference Reference to an IO variable ID (the serial port to listen on)
		PortReference string `json:"portReference"`
	} `json:"arguments"`
	Id       string                  `json:"id"`
	Label    *string                 `json:"label,omitempty"`
	Position NodePosition            `json:"position"`
	Type     OnSerialReceiveNodeType `json:"type"`
}

// OnSerialReceiveNodeType defines model for OnSerialReceiveNode.Type.
type OnSerialReceiveNodeType string

// OnStartupNode defines model for OnStartupNode.
type OnStartupNode struct {
	Id       string            `json:"id"`
	Label    *string           `json:"label,omitempty"`
	Position NodePosition      `json:"position"`
	Type     OnStartupNodeType `json:"type"`
}

// OnStartupNodeType defines model for OnStartupNode.Type.
type OnStartupNodeType string

// OnThresholdNode defines model for OnThresholdNode.
type OnThresholdNode struct {
	Arguments struct {
		// Deadband Hysteresis band width around threshold; 0 disables (default 0)
		Deadband *float32 `json:"deadband,omitempty"`

		// Direction Crossing direction to fire on (default both)
		Direction *OnThresholdNodeArgumentsDirection `json:"direction,omitempty"`
		Output    *OutputBinding                     `json:"output,omitempty"`

		// Threshold Value the variable crosses to fire the trigger
		Threshold float32   `json:"threshold"`
		Variable  Reference `json:"variable"`
	} `json:"arguments"`
	Id       string              `json:"id"`
	Label    *string             `json:"label,omitempty"`
	Position NodePosition        `json:"position"`
	Type     OnThresholdNodeType `json:"type"`
}

// OnThresholdNodeArgumentsDirection Crossing direction to fire on (default both)
type OnThresholdNodeArgumentsDirection string

// OnThresholdNodeType defines model for OnThresholdNode.Type.
type OnThresholdNodeType string

// OutputBinding defines model for OutputBinding.
type OutputBinding struct {
	// Active Discard the output if false; route it according to `mode` if true
	Active bool              `json:"active"`
	Mode   OutputBindingMode `json:"mode"`

	// Name Variable name (when mode=emit)
	Name   *string    `json:"name,omitempty"`
	Target *Reference `json:"target,omitempty"`
}

// OutputBindingMode defines model for OutputBinding.Mode.
type OutputBindingMode string

// OutputDeclaration defines model for OutputDeclaration.
type OutputDeclaration struct {
	DataType DataType              `json:"dataType"`
	Mode     OutputDeclarationMode `json:"mode"`

	// Name JSON property name of the declared output
	Name   string     `json:"name"`
	Target *Reference `json:"target,omitempty"`

	// Uid New variable uid (when mode=emit)
	Uid *string `json:"uid,omitempty"`
}

// OutputDeclarationMode defines model for OutputDeclaration.Mode.
type OutputDeclarationMode string

// PWMChannel defines model for PWMChannel.
type PWMChannel struct {
	// Channel Channel number on the PWM chip
	Channel int `json:"channel"`

	// DriverID Driver instance ID from the device manifest
	DriverID string `json:"driverId"`

	// Frequency PWM frequency in Hz
	Frequency int            `json:"frequency"`
	Id        string         `json:"id"`
	Label     string         `json:"label"`
	Type      PWMChannelType `json:"type"`
}

// PWMChannelType defines model for PWMChannel.Type.
type PWMChannelType string

// ReadPinNode defines model for ReadPinNode.
type ReadPinNode struct {
	Arguments struct {
		Output OutputBinding `json:"output"`

		// PinReference Reference to an IO variable ID
		PinReference string     `json:"pinReference"`
		SignalType   SignalType `json:"signalType"`

		// ToolDescription Description exposed to the LLM when this node is wired as a tool. Ignored in exec mode.
		ToolDescription *string `json:"toolDescription,omitempty"`
	} `json:"arguments"`
	Id       string          `json:"id"`
	Label    *string         `json:"label,omitempty"`
	Position NodePosition    `json:"position"`
	Type     ReadPinNodeType `json:"type"`
}

// ReadPinNodeType defines model for ReadPinNode.Type.
type ReadPinNodeType string

// Reference defines model for Reference.
type Reference struct {
	SrcId string `json:"srcId"`
	VarId string `json:"varId"`
}

// RetrieverNode defines model for RetrieverNode.
type RetrieverNode struct {
	Arguments struct {
		// CollectionID RAG collection ID to query
		CollectionID string        `json:"collectionId"`
		Output       OutputBinding `json:"output"`
		Query        Expression    `json:"query"`

		// ToolDescription Description exposed to the LLM when this node is wired as a tool. Ignored in exec mode.
		ToolDescription *string `json:"toolDescription,omitempty"`

		// TopK Number of results to return
		TopK int `json:"topK"`
	} `json:"arguments"`
	Id       string            `json:"id"`
	Label    *string           `json:"label,omitempty"`
	Position NodePosition      `json:"position"`
	Type     RetrieverNodeType `json:"type"`
}

// RetrieverNodeType defines model for RetrieverNode.Type.
type RetrieverNodeType string

// SerialReadNode defines model for SerialReadNode.
type SerialReadNode struct {
	Arguments struct {
		Output OutputBinding `json:"output"`

		// PortReference Reference to an UART ID (the serial port to read from)
		PortReference string  `json:"portReference"`
		Prompt        *string `json:"prompt,omitempty"`
	} `json:"arguments"`
	Id       string             `json:"id"`
	Label    *string            `json:"label,omitempty"`
	Position NodePosition       `json:"position"`
	Type     SerialReadNodeType `json:"type"`
}

// SerialReadNodeType defines model for SerialReadNode.Type.
type SerialReadNodeType string

// SerialWriteNode defines model for SerialWriteNode.
type SerialWriteNode struct {
	Arguments struct {
		// PortReference Reference to a UART channel ID (the serial port to write to)
		PortReference string     `json:"portReference"`
		Value         Expression `json:"value"`
	} `json:"arguments"`
	Id       string              `json:"id"`
	Label    *string             `json:"label,omitempty"`
	Position NodePosition        `json:"position"`
	Type     SerialWriteNodeType `json:"type"`
}

// SerialWriteNodeType defines model for SerialWriteNode.Type.
type SerialWriteNodeType string

// SetVariableNode defines model for SetVariableNode.
type SetVariableNode struct {
	Arguments struct {
		Value    Expression `json:"value"`
		Variable Reference  `json:"variable"`
	} `json:"arguments"`
	Id       string              `json:"id"`
	Label    *string             `json:"label,omitempty"`
	Position NodePosition        `json:"position"`
	Type     SetVariableNodeType `json:"type"`
}

// SetVariableNodeType defines model for SetVariableNode.Type.
type SetVariableNodeType string

// SignalType defines model for SignalType.
type SignalType string

// TickerNode defines model for TickerNode.
type TickerNode struct {
	Arguments struct {
		// IntervalUnit Time unit for the interval
		IntervalUnit TickerNodeArgumentsIntervalUnit `json:"intervalUnit"`

		// IntervalValue How many units between ticks
		IntervalValue int `json:"intervalValue"`
	} `json:"arguments"`
	Id       string         `json:"id"`
	Label    *string        `json:"label,omitempty"`
	Position NodePosition   `json:"position"`
	Type     TickerNodeType `json:"type"`
}

// TickerNodeArgumentsIntervalUnit Time unit for the interval
type TickerNodeArgumentsIntervalUnit string

// TickerNodeType defines model for TickerNode.Type.
type TickerNodeType string

// UARTChannel defines model for UARTChannel.
type UARTChannel struct {
	// DriverID Driver instance ID from the device manifest
	DriverID string          `json:"driverId"`
	Id       string          `json:"id"`
	Label    string          `json:"label"`
	Type     UARTChannelType `json:"type"`
}

// UARTChannelType defines model for UARTChannel.Type.
type UARTChannelType string

// Variable A named, typed variable with a stable uid that can be referenced throughout the workflow.
type Variable struct {
	DataType DataType `json:"dataType"`

	// InitialValue Initial value matching the dataType (number, boolean, or string). Only used by declared variables.
	InitialValue interface{} `json:"initialValue,omitempty"`
	Name         string      `json:"name"`

	// Uid Stable identifier that survives renames
	Uid string `json:"uid"`
}

// Vertex defines model for Vertex.
type Vertex struct {
	NodeId string `json:"nodeId"`
	Port   string `json:"port"`
}

// WebFetchNode defines model for WebFetchNode.
type WebFetchNode struct {
	Arguments struct {
		// MaxChars Maximum characters of extracted text to return. Defaults to 50000 when omitted or non-positive.
		MaxChars *int          `json:"maxChars,omitempty"`
		Output   OutputBinding `json:"output"`
		Url      Expression    `json:"url"`
	} `json:"arguments"`
	Id       string           `json:"id"`
	Label    *string          `json:"label,omitempty"`
	Position NodePosition     `json:"position"`
	Type     WebFetchNodeType `json:"type"`
}

// WebFetchNodeType defines model for WebFetchNode.Type.
type WebFetchNodeType string

// WebSearchToolNode defines model for WebSearchToolNode.
type WebSearchToolNode struct {
	Arguments *struct {
		// MaxResults Maximum number of search results to return per call. Defaults to 5 when omitted or non-positive. Capped at 20.
		MaxResults *int `json:"maxResults,omitempty"`
	} `json:"arguments,omitempty"`
	Id       string                `json:"id"`
	Label    *string               `json:"label,omitempty"`
	Position NodePosition          `json:"position"`
	Type     WebSearchToolNodeType `json:"type"`
}

// WebSearchToolNodeType defines model for WebSearchToolNode.Type.
type WebSearchToolNodeType string

// Workflow Workflow represents the deployment format of a project, passed to agents.
type Workflow struct {
	Channels          []Channel  `json:"channels"`
	DeclaredVariables []Variable `json:"declaredVariables"`
	Edges             []Edge     `json:"edges"`
	Functions         []Function `json:"functions"`

	// MemoryFiles Declared memory files; referenced from agent nodes by uid.
	MemoryFiles *[]MemoryFile `json:"memoryFiles,omitempty"`
	Nodes       []Node        `json:"nodes"`
}

// WritePinNode defines model for WritePinNode.
type WritePinNode struct {
	Arguments struct {
		// PinReference Reference to an IO variable ID
		PinReference string     `json:"pinReference"`
		SignalType   SignalType `json:"signalType"`
		Value        Expression `json:"value"`
	} `json:"arguments"`
	Id       string           `json:"id"`
	Label    *string          `json:"label,omitempty"`
	Position NodePosition     `json:"position"`
	Type     WritePinNodeType `json:"type"`
}

// WritePinNodeType defines model for WritePinNode.Type.
type WritePinNodeType string

// AsGPIOINChannel returns the union data inside the Channel as a GPIOINChannel
func (t Channel) AsGPIOINChannel() (GPIOINChannel, error) {
	var body GPIOINChannel
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGPIOINChannel overwrites any union data inside the Channel as the provided GPIOINChannel
func (t *Channel) FromGPIOINChannel(v GPIOINChannel) error {
	v.Type = "GPIOIN"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGPIOINChannel performs a merge with any union data inside the Channel, using the provided GPIOINChannel
func (t *Channel) MergeGPIOINChannel(v GPIOINChannel) error {
	v.Type = "GPIOIN"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGPIOOUTChannel returns the union data inside the Channel as a GPIOOUTChannel
func (t Channel) AsGPIOOUTChannel() (GPIOOUTChannel, error) {
	var body GPIOOUTChannel
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGPIOOUTChannel overwrites any union data inside the Channel as the provided GPIOOUTChannel
func (t *Channel) FromGPIOOUTChannel(v GPIOOUTChannel) error {
	v.Type = "GPIOOUT"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGPIOOUTChannel performs a merge with any union data inside the Channel, using the provided GPIOOUTChannel
func (t *Channel) MergeGPIOOUTChannel(v GPIOOUTChannel) error {
	v.Type = "GPIOOUT"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsADCChannel returns the union data inside the Channel as a ADCChannel
func (t Channel) AsADCChannel() (ADCChannel, error) {
	var body ADCChannel
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromADCChannel overwrites any union data inside the Channel as the provided ADCChannel
func (t *Channel) FromADCChannel(v ADCChannel) error {
	v.Type = "ADC"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeADCChannel performs a merge with any union data inside the Channel, using the provided ADCChannel
func (t *Channel) MergeADCChannel(v ADCChannel) error {
	v.Type = "ADC"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPWMChannel returns the union data inside the Channel as a PWMChannel
func (t Channel) AsPWMChannel() (PWMChannel, error) {
	var body PWMChannel
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPWMChannel overwrites any union data inside the Channel as the provided PWMChannel
func (t *Channel) FromPWMChannel(v PWMChannel) error {
	v.Type = "PWM"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePWMChannel performs a merge with any union data inside the Channel, using the provided PWMChannel
func (t *Channel) MergePWMChannel(v PWMChannel) error {
	v.Type = "PWM"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDACChannel returns the union data inside the Channel as a DACChannel
func (t Channel) AsDACChannel() (DACChannel, error) {
	var body DACChannel
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDACChannel overwrites any union data inside the Channel as the provided DACChannel
func (t *Channel) FromDACChannel(v DACChannel) error {
	v.Type = "DAC"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDACChannel performs a merge with any union data inside the Channel, using the provided DACChannel
func (t *Channel) MergeDACChannel(v DACChannel) error {
	v.Type = "DAC"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUARTChannel returns the union data inside the Channel as a UARTChannel
func (t Channel) AsUARTChannel() (UARTChannel, error) {
	var body UARTChannel
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUARTChannel overwrites any union data inside the Channel as the provided UARTChannel
func (t *Channel) FromUARTChannel(v UARTChannel) error {
	v.Type = "UART"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUARTChannel performs a merge with any union data inside the Channel, using the provided UARTChannel
func (t *Channel) MergeUARTChannel(v UARTChannel) error {
	v.Type = "UART"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMQTTChannel returns the union data inside the Channel as a MQTTChannel
func (t Channel) AsMQTTChannel() (MQTTChannel, error) {
	var body MQTTChannel
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMQTTChannel overwrites any union data inside the Channel as the provided MQTTChannel
func (t *Channel) FromMQTTChannel(v MQTTChannel) error {
	v.Type = "MQTT"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMQTTChannel performs a merge with any union data inside the Channel, using the provided MQTTChannel
func (t *Channel) MergeMQTTChannel(v MQTTChannel) error {
	v.Type = "MQTT"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Channel) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Channel) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ADC":
		return t.AsADCChannel()
	case "DAC":
		return t.AsDACChannel()
	case "GPIOIN":
		return t.AsGPIOINChannel()
	case "GPIOOUT":
		return t.AsGPIOOUTChannel()
	case "MQTT":
		return t.AsMQTTChannel()
	case "PWM":
		return t.AsPWMChannel()
	case "UART":
		return t.AsUARTChannel()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Channel) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Channel) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsReadPinNode returns the union data inside the Node as a ReadPinNode
func (t Node) AsReadPinNode() (ReadPinNode, error) {
	var body ReadPinNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReadPinNode overwrites any union data inside the Node as the provided ReadPinNode
func (t *Node) FromReadPinNode(v ReadPinNode) error {
	v.Type = "ReadPin"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeReadPinNode performs a merge with any union data inside the Node, using the provided ReadPinNode
func (t *Node) MergeReadPinNode(v ReadPinNode) error {
	v.Type = "ReadPin"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWritePinNode returns the union data inside the Node as a WritePinNode
func (t Node) AsWritePinNode() (WritePinNode, error) {
	var body WritePinNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWritePinNode overwrites any union data inside the Node as the provided WritePinNode
func (t *Node) FromWritePinNode(v WritePinNode) error {
	v.Type = "WritePin"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWritePinNode performs a merge with any union data inside the Node, using the provided WritePinNode
func (t *Node) MergeWritePinNode(v WritePinNode) error {
	v.Type = "WritePin"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAgentNode returns the union data inside the Node as a AgentNode
func (t Node) AsAgentNode() (AgentNode, error) {
	var body AgentNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentNode overwrites any union data inside the Node as the provided AgentNode
func (t *Node) FromAgentNode(v AgentNode) error {
	v.Type = "Agent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentNode performs a merge with any union data inside the Node, using the provided AgentNode
func (t *Node) MergeAgentNode(v AgentNode) error {
	v.Type = "Agent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsIfNode returns the union data inside the Node as a IfNode
func (t Node) AsIfNode() (IfNode, error) {
	var body IfNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIfNode overwrites any union data inside the Node as the provided IfNode
func (t *Node) FromIfNode(v IfNode) error {
	v.Type = "If"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIfNode performs a merge with any union data inside the Node, using the provided IfNode
func (t *Node) MergeIfNode(v IfNode) error {
	v.Type = "If"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSerialReadNode returns the union data inside the Node as a SerialReadNode
func (t Node) AsSerialReadNode() (SerialReadNode, error) {
	var body SerialReadNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSerialReadNode overwrites any union data inside the Node as the provided SerialReadNode
func (t *Node) FromSerialReadNode(v SerialReadNode) error {
	v.Type = "SerialRead"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSerialReadNode performs a merge with any union data inside the Node, using the provided SerialReadNode
func (t *Node) MergeSerialReadNode(v SerialReadNode) error {
	v.Type = "SerialRead"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSerialWriteNode returns the union data inside the Node as a SerialWriteNode
func (t Node) AsSerialWriteNode() (SerialWriteNode, error) {
	var body SerialWriteNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSerialWriteNode overwrites any union data inside the Node as the provided SerialWriteNode
func (t *Node) FromSerialWriteNode(v SerialWriteNode) error {
	v.Type = "SerialWrite"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSerialWriteNode performs a merge with any union data inside the Node, using the provided SerialWriteNode
func (t *Node) MergeSerialWriteNode(v SerialWriteNode) error {
	v.Type = "SerialWrite"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRetrieverNode returns the union data inside the Node as a RetrieverNode
func (t Node) AsRetrieverNode() (RetrieverNode, error) {
	var body RetrieverNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRetrieverNode overwrites any union data inside the Node as the provided RetrieverNode
func (t *Node) FromRetrieverNode(v RetrieverNode) error {
	v.Type = "Retriever"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRetrieverNode performs a merge with any union data inside the Node, using the provided RetrieverNode
func (t *Node) MergeRetrieverNode(v RetrieverNode) error {
	v.Type = "Retriever"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWebFetchNode returns the union data inside the Node as a WebFetchNode
func (t Node) AsWebFetchNode() (WebFetchNode, error) {
	var body WebFetchNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWebFetchNode overwrites any union data inside the Node as the provided WebFetchNode
func (t *Node) FromWebFetchNode(v WebFetchNode) error {
	v.Type = "WebFetch"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWebFetchNode performs a merge with any union data inside the Node, using the provided WebFetchNode
func (t *Node) MergeWebFetchNode(v WebFetchNode) error {
	v.Type = "WebFetch"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFunctionCallNode returns the union data inside the Node as a FunctionCallNode
func (t Node) AsFunctionCallNode() (FunctionCallNode, error) {
	var body FunctionCallNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFunctionCallNode overwrites any union data inside the Node as the provided FunctionCallNode
func (t *Node) FromFunctionCallNode(v FunctionCallNode) error {
	v.Type = "FunctionCall"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFunctionCallNode performs a merge with any union data inside the Node, using the provided FunctionCallNode
func (t *Node) MergeFunctionCallNode(v FunctionCallNode) error {
	v.Type = "FunctionCall"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOnFunctionCallNode returns the union data inside the Node as a OnFunctionCallNode
func (t Node) AsOnFunctionCallNode() (OnFunctionCallNode, error) {
	var body OnFunctionCallNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOnFunctionCallNode overwrites any union data inside the Node as the provided OnFunctionCallNode
func (t *Node) FromOnFunctionCallNode(v OnFunctionCallNode) error {
	v.Type = "OnFunctionCall"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOnFunctionCallNode performs a merge with any union data inside the Node, using the provided OnFunctionCallNode
func (t *Node) MergeOnFunctionCallNode(v OnFunctionCallNode) error {
	v.Type = "OnFunctionCall"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDelayNode returns the union data inside the Node as a DelayNode
func (t Node) AsDelayNode() (DelayNode, error) {
	var body DelayNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDelayNode overwrites any union data inside the Node as the provided DelayNode
func (t *Node) FromDelayNode(v DelayNode) error {
	v.Type = "Delay"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDelayNode performs a merge with any union data inside the Node, using the provided DelayNode
func (t *Node) MergeDelayNode(v DelayNode) error {
	v.Type = "Delay"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTickerNode returns the union data inside the Node as a TickerNode
func (t Node) AsTickerNode() (TickerNode, error) {
	var body TickerNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTickerNode overwrites any union data inside the Node as the provided TickerNode
func (t *Node) FromTickerNode(v TickerNode) error {
	v.Type = "Ticker"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTickerNode performs a merge with any union data inside the Node, using the provided TickerNode
func (t *Node) MergeTickerNode(v TickerNode) error {
	v.Type = "Ticker"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAlarmNode returns the union data inside the Node as a AlarmNode
func (t Node) AsAlarmNode() (AlarmNode, error) {
	var body AlarmNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAlarmNode overwrites any union data inside the Node as the provided AlarmNode
func (t *Node) FromAlarmNode(v AlarmNode) error {
	v.Type = "Alarm"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAlarmNode performs a merge with any union data inside the Node, using the provided AlarmNode
func (t *Node) MergeAlarmNode(v AlarmNode) error {
	v.Type = "Alarm"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWebSearchToolNode returns the union data inside the Node as a WebSearchToolNode
func (t Node) AsWebSearchToolNode() (WebSearchToolNode, error) {
	var body WebSearchToolNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWebSearchToolNode overwrites any union data inside the Node as the provided WebSearchToolNode
func (t *Node) FromWebSearchToolNode(v WebSearchToolNode) error {
	v.Type = "WebSearchTool"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWebSearchToolNode performs a merge with any union data inside the Node, using the provided WebSearchToolNode
func (t *Node) MergeWebSearchToolNode(v WebSearchToolNode) error {
	v.Type = "WebSearchTool"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOnStartupNode returns the union data inside the Node as a OnStartupNode
func (t Node) AsOnStartupNode() (OnStartupNode, error) {
	var body OnStartupNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOnStartupNode overwrites any union data inside the Node as the provided OnStartupNode
func (t *Node) FromOnStartupNode(v OnStartupNode) error {
	v.Type = "OnStartup"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOnStartupNode performs a merge with any union data inside the Node, using the provided OnStartupNode
func (t *Node) MergeOnStartupNode(v OnStartupNode) error {
	v.Type = "OnStartup"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOnPinEdgeNode returns the union data inside the Node as a OnPinEdgeNode
func (t Node) AsOnPinEdgeNode() (OnPinEdgeNode, error) {
	var body OnPinEdgeNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOnPinEdgeNode overwrites any union data inside the Node as the provided OnPinEdgeNode
func (t *Node) FromOnPinEdgeNode(v OnPinEdgeNode) error {
	v.Type = "OnPinEdge"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOnPinEdgeNode performs a merge with any union data inside the Node, using the provided OnPinEdgeNode
func (t *Node) MergeOnPinEdgeNode(v OnPinEdgeNode) error {
	v.Type = "OnPinEdge"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOnSerialReceiveNode returns the union data inside the Node as a OnSerialReceiveNode
func (t Node) AsOnSerialReceiveNode() (OnSerialReceiveNode, error) {
	var body OnSerialReceiveNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOnSerialReceiveNode overwrites any union data inside the Node as the provided OnSerialReceiveNode
func (t *Node) FromOnSerialReceiveNode(v OnSerialReceiveNode) error {
	v.Type = "OnSerialReceive"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOnSerialReceiveNode performs a merge with any union data inside the Node, using the provided OnSerialReceiveNode
func (t *Node) MergeOnSerialReceiveNode(v OnSerialReceiveNode) error {
	v.Type = "OnSerialReceive"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOnThresholdNode returns the union data inside the Node as a OnThresholdNode
func (t Node) AsOnThresholdNode() (OnThresholdNode, error) {
	var body OnThresholdNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOnThresholdNode overwrites any union data inside the Node as the provided OnThresholdNode
func (t *Node) FromOnThresholdNode(v OnThresholdNode) error {
	v.Type = "OnThreshold"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOnThresholdNode performs a merge with any union data inside the Node, using the provided OnThresholdNode
func (t *Node) MergeOnThresholdNode(v OnThresholdNode) error {
	v.Type = "OnThreshold"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSetVariableNode returns the union data inside the Node as a SetVariableNode
func (t Node) AsSetVariableNode() (SetVariableNode, error) {
	var body SetVariableNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetVariableNode overwrites any union data inside the Node as the provided SetVariableNode
func (t *Node) FromSetVariableNode(v SetVariableNode) error {
	v.Type = "SetVariable"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSetVariableNode performs a merge with any union data inside the Node, using the provided SetVariableNode
func (t *Node) MergeSetVariableNode(v SetVariableNode) error {
	v.Type = "SetVariable"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMqttPublishNode returns the union data inside the Node as a MqttPublishNode
func (t Node) AsMqttPublishNode() (MqttPublishNode, error) {
	var body MqttPublishNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMqttPublishNode overwrites any union data inside the Node as the provided MqttPublishNode
func (t *Node) FromMqttPublishNode(v MqttPublishNode) error {
	v.Type = "MqttPublish"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMqttPublishNode performs a merge with any union data inside the Node, using the provided MqttPublishNode
func (t *Node) MergeMqttPublishNode(v MqttPublishNode) error {
	v.Type = "MqttPublish"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOnMqttMessageNode returns the union data inside the Node as a OnMqttMessageNode
func (t Node) AsOnMqttMessageNode() (OnMqttMessageNode, error) {
	var body OnMqttMessageNode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOnMqttMessageNode overwrites any union data inside the Node as the provided OnMqttMessageNode
func (t *Node) FromOnMqttMessageNode(v OnMqttMessageNode) error {
	v.Type = "OnMqttMessage"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOnMqttMessageNode performs a merge with any union data inside the Node, using the provided OnMqttMessageNode
func (t *Node) MergeOnMqttMessageNode(v OnMqttMessageNode) error {
	v.Type = "OnMqttMessage"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Node) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Node) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "Agent":
		return t.AsAgentNode()
	case "Alarm":
		return t.AsAlarmNode()
	case "Delay":
		return t.AsDelayNode()
	case "FunctionCall":
		return t.AsFunctionCallNode()
	case "If":
		return t.AsIfNode()
	case "MqttPublish":
		return t.AsMqttPublishNode()
	case "OnFunctionCall":
		return t.AsOnFunctionCallNode()
	case "OnMqttMessage":
		return t.AsOnMqttMessageNode()
	case "OnPinEdge":
		return t.AsOnPinEdgeNode()
	case "OnSerialReceive":
		return t.AsOnSerialReceiveNode()
	case "OnStartup":
		return t.AsOnStartupNode()
	case "OnThreshold":
		return t.AsOnThresholdNode()
	case "ReadPin":
		return t.AsReadPinNode()
	case "Retriever":
		return t.AsRetrieverNode()
	case "SerialRead":
		return t.AsSerialReadNode()
	case "SerialWrite":
		return t.AsSerialWriteNode()
	case "SetVariable":
		return t.AsSetVariableNode()
	case "Ticker":
		return t.AsTickerNode()
	case "WebFetch":
		return t.AsWebFetchNode()
	case "WebSearchTool":
		return t.AsWebSearchToolNode()
	case "WritePin":
		return t.AsWritePinNode()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Node) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Node) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
