// Package debugapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package debugapi

import (
	"encoding/json"
	"errors"

	externalRef0 "github.com/ForestHubAI/fh-core/go/api/workflow"
	"github.com/oapi-codegen/runtime"
)

// Defines values for DebugErrorEventType.
const (
	Error DebugErrorEventType = "error"
)

// Valid indicates whether the value is a known member of the DebugErrorEventType enum.
func (e DebugErrorEventType) Valid() bool {
	switch e {
	case Error:
		return true
	default:
		return false
	}
}

// Defines values for DebugMessageEventType.
const (
	Message DebugMessageEventType = "message"
)

// Valid indicates whether the value is a known member of the DebugMessageEventType enum.
func (e DebugMessageEventType) Valid() bool {
	switch e {
	case Message:
		return true
	default:
		return false
	}
}

// Defines values for DebugReadyEventType.
const (
	Ready DebugReadyEventType = "ready"
)

// Valid indicates whether the value is a known member of the DebugReadyEventType enum.
func (e DebugReadyEventType) Valid() bool {
	switch e {
	case Ready:
		return true
	default:
		return false
	}
}

// DebugErrorEvent defines model for DebugErrorEvent.
type DebugErrorEvent struct {
	Message string              `json:"message"`
	Type    DebugErrorEventType `json:"type"`
}

// DebugErrorEventType defines model for DebugErrorEvent.Type.
type DebugErrorEventType string

// DebugEvent defines model for DebugEvent.
type DebugEvent struct {
	union json.RawMessage
}

// DebugExternalState Pre-populated hardware I/O values for the debug binary
type DebugExternalState struct {
	// Gpio Pin number to value map (e.g. {"4": 1, "5": 0})
	Gpio *map[string]int `json:"gpio,omitempty"`

	// Serial Serial input buffer (consumed in order by ReadLine calls)
	Serial *[]string `json:"serial,omitempty"`
}

// DebugMessageEvent defines model for DebugMessageEvent.
type DebugMessageEvent struct {
	Text string                `json:"text"`
	Type DebugMessageEventType `json:"type"`
}

// DebugMessageEventType defines model for DebugMessageEvent.Type.
type DebugMessageEventType string

// DebugReadyEvent defines model for DebugReadyEvent.
type DebugReadyEvent struct {
	// SessionId Session ID for subsequent requests
	SessionId string              `json:"sessionId"`
	Type      DebugReadyEventType `json:"type"`
}

// DebugReadyEventType defines model for DebugReadyEvent.Type.
type DebugReadyEventType string

// DebugRequest defines model for DebugRequest.
type DebugRequest struct {
	// Workflow Workflow represents the deployment format of a project, passed to agents.
	Workflow externalRef0.Workflow `json:"workflow"`
}

// DebugStepRequest defines model for DebugStepRequest.
type DebugStepRequest struct {
	// Context Workflow variable values (the Context struct in the generated C++)
	Context map[string]interface{} `json:"context"`

	// ExternalState Pre-populated hardware I/O values for the debug binary
	ExternalState DebugExternalState `json:"externalState"`

	// NodeId Node to execute. If provided, sets the cursor first (debug from here). If omitted, executes the current cursor node.
	NodeId *string `json:"nodeId,omitempty"`
}

// DebugStepResult defines model for DebugStepResult.
type DebugStepResult struct {
	// Context Updated workflow variable values after execution
	Context      map[string]interface{} `json:"context"`
	ExecutedNode string                 `json:"executedNode"`

	// NextNode Next node to execute. Empty string if execution reached idle.
	NextNode string `json:"nextNode"`
}

// AsDebugReadyEvent returns the union data inside the DebugEvent as a DebugReadyEvent
func (t DebugEvent) AsDebugReadyEvent() (DebugReadyEvent, error) {
	var body DebugReadyEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDebugReadyEvent overwrites any union data inside the DebugEvent as the provided DebugReadyEvent
func (t *DebugEvent) FromDebugReadyEvent(v DebugReadyEvent) error {
	v.Type = "ready"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDebugReadyEvent performs a merge with any union data inside the DebugEvent, using the provided DebugReadyEvent
func (t *DebugEvent) MergeDebugReadyEvent(v DebugReadyEvent) error {
	v.Type = "ready"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDebugMessageEvent returns the union data inside the DebugEvent as a DebugMessageEvent
func (t DebugEvent) AsDebugMessageEvent() (DebugMessageEvent, error) {
	var body DebugMessageEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDebugMessageEvent overwrites any union data inside the DebugEvent as the provided DebugMessageEvent
func (t *DebugEvent) FromDebugMessageEvent(v DebugMessageEvent) error {
	v.Type = "message"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDebugMessageEvent performs a merge with any union data inside the DebugEvent, using the provided DebugMessageEvent
func (t *DebugEvent) MergeDebugMessageEvent(v DebugMessageEvent) error {
	v.Type = "message"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDebugErrorEvent returns the union data inside the DebugEvent as a DebugErrorEvent
func (t DebugEvent) AsDebugErrorEvent() (DebugErrorEvent, error) {
	var body DebugErrorEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDebugErrorEvent overwrites any union data inside the DebugEvent as the provided DebugErrorEvent
func (t *DebugEvent) FromDebugErrorEvent(v DebugErrorEvent) error {
	v.Type = "error"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDebugErrorEvent performs a merge with any union data inside the DebugEvent, using the provided DebugErrorEvent
func (t *DebugEvent) MergeDebugErrorEvent(v DebugErrorEvent) error {
	v.Type = "error"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DebugEvent) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t DebugEvent) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "error":
		return t.AsDebugErrorEvent()
	case "message":
		return t.AsDebugMessageEvent()
	case "ready":
		return t.AsDebugReadyEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t DebugEvent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DebugEvent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
