// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package engine

import (
	"context"

	"github.com/ForestHubAI/edge-agents/go/api/workflowapi"
	"github.com/ForestHubAI/edge-agents/go/llmproxy"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWirable creates a new instance of MockWirable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWirable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWirable {
	mock := &MockWirable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWirable is an autogenerated mock type for the Wirable type
type MockWirable struct {
	mock.Mock
}

type MockWirable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWirable) EXPECT() *MockWirable_Expecter {
	return &MockWirable_Expecter{mock: &_m.Mock}
}

// AddTransition provides a mock function for the type MockWirable
func (_mock *MockWirable) AddTransition(port string, tr Transition) error {
	ret := _mock.Called(port, tr)

	if len(ret) == 0 {
		panic("no return value specified for AddTransition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, Transition) error); ok {
		r0 = returnFunc(port, tr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWirable_AddTransition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTransition'
type MockWirable_AddTransition_Call struct {
	*mock.Call
}

// AddTransition is a helper method to define mock.On call
//   - port string
//   - tr Transition
func (_e *MockWirable_Expecter) AddTransition(port interface{}, tr interface{}) *MockWirable_AddTransition_Call {
	return &MockWirable_AddTransition_Call{Call: _e.mock.On("AddTransition", port, tr)}
}

func (_c *MockWirable_AddTransition_Call) Run(run func(port string, tr Transition)) *MockWirable_AddTransition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 Transition
		if args[1] != nil {
			arg1 = args[1].(Transition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWirable_AddTransition_Call) Return(err error) *MockWirable_AddTransition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWirable_AddTransition_Call) RunAndReturn(run func(port string, tr Transition) error) *MockWirable_AddTransition_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockWirable
func (_mock *MockWirable) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockWirable_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockWirable_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockWirable_Expecter) ID() *MockWirable_ID_Call {
	return &MockWirable_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockWirable_ID_Call) Run(run func()) *MockWirable_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWirable_ID_Call) Return(s string) *MockWirable_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockWirable_ID_Call) RunAndReturn(run func() string) *MockWirable_ID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTrigger creates a new instance of MockTrigger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrigger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrigger {
	mock := &MockTrigger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrigger is an autogenerated mock type for the Trigger type
type MockTrigger struct {
	mock.Mock
}

type MockTrigger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrigger) EXPECT() *MockTrigger_Expecter {
	return &MockTrigger_Expecter{mock: &_m.Mock}
}

// AddTransition provides a mock function for the type MockTrigger
func (_mock *MockTrigger) AddTransition(port string, tr Transition) error {
	ret := _mock.Called(port, tr)

	if len(ret) == 0 {
		panic("no return value specified for AddTransition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, Transition) error); ok {
		r0 = returnFunc(port, tr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTrigger_AddTransition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTransition'
type MockTrigger_AddTransition_Call struct {
	*mock.Call
}

// AddTransition is a helper method to define mock.On call
//   - port string
//   - tr Transition
func (_e *MockTrigger_Expecter) AddTransition(port interface{}, tr interface{}) *MockTrigger_AddTransition_Call {
	return &MockTrigger_AddTransition_Call{Call: _e.mock.On("AddTransition", port, tr)}
}

func (_c *MockTrigger_AddTransition_Call) Run(run func(port string, tr Transition)) *MockTrigger_AddTransition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 Transition
		if args[1] != nil {
			arg1 = args[1].(Transition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrigger_AddTransition_Call) Return(err error) *MockTrigger_AddTransition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTrigger_AddTransition_Call) RunAndReturn(run func(port string, tr Transition) error) *MockTrigger_AddTransition_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockTrigger
func (_mock *MockTrigger) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTrigger_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockTrigger_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockTrigger_Expecter) Close() *MockTrigger_Close_Call {
	return &MockTrigger_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockTrigger_Close_Call) Run(run func()) *MockTrigger_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrigger_Close_Call) Return(err error) *MockTrigger_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTrigger_Close_Call) RunAndReturn(run func() error) *MockTrigger_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockTrigger
func (_mock *MockTrigger) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTrigger_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockTrigger_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockTrigger_Expecter) ID() *MockTrigger_ID_Call {
	return &MockTrigger_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockTrigger_ID_Call) Run(run func()) *MockTrigger_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrigger_ID_Call) Return(s string) *MockTrigger_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTrigger_ID_Call) RunAndReturn(run func() string) *MockTrigger_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockTrigger
func (_mock *MockTrigger) Wait(ctx context.Context) (Event, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (Event, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) Event); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(Event)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrigger_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockTrigger_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTrigger_Expecter) Wait(ctx interface{}) *MockTrigger_Wait_Call {
	return &MockTrigger_Wait_Call{Call: _e.mock.On("Wait", ctx)}
}

func (_c *MockTrigger_Wait_Call) Run(run func(ctx context.Context)) *MockTrigger_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTrigger_Wait_Call) Return(event Event, err error) *MockTrigger_Wait_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockTrigger_Wait_Call) RunAndReturn(run func(ctx context.Context) (Event, error)) *MockTrigger_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExecutable creates a new instance of MockExecutable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutable {
	mock := &MockExecutable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExecutable is an autogenerated mock type for the Executable type
type MockExecutable struct {
	mock.Mock
}

type MockExecutable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutable) EXPECT() *MockExecutable_Expecter {
	return &MockExecutable_Expecter{mock: &_m.Mock}
}

// AddTransition provides a mock function for the type MockExecutable
func (_mock *MockExecutable) AddTransition(port string, tr Transition) error {
	ret := _mock.Called(port, tr)

	if len(ret) == 0 {
		panic("no return value specified for AddTransition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, Transition) error); ok {
		r0 = returnFunc(port, tr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExecutable_AddTransition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTransition'
type MockExecutable_AddTransition_Call struct {
	*mock.Call
}

// AddTransition is a helper method to define mock.On call
//   - port string
//   - tr Transition
func (_e *MockExecutable_Expecter) AddTransition(port interface{}, tr interface{}) *MockExecutable_AddTransition_Call {
	return &MockExecutable_AddTransition_Call{Call: _e.mock.On("AddTransition", port, tr)}
}

func (_c *MockExecutable_AddTransition_Call) Run(run func(port string, tr Transition)) *MockExecutable_AddTransition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 Transition
		if args[1] != nil {
			arg1 = args[1].(Transition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExecutable_AddTransition_Call) Return(err error) *MockExecutable_AddTransition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExecutable_AddTransition_Call) RunAndReturn(run func(port string, tr Transition) error) *MockExecutable_AddTransition_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function for the type MockExecutable
func (_mock *MockExecutable) Execute(ctx context.Context, scope *Scope) (string, error) {
	ret := _mock.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Scope) (string, error)); ok {
		return returnFunc(ctx, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Scope) string); ok {
		r0 = returnFunc(ctx, scope)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *Scope) error); ok {
		r1 = returnFunc(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutable_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockExecutable_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - scope *Scope
func (_e *MockExecutable_Expecter) Execute(ctx interface{}, scope interface{}) *MockExecutable_Execute_Call {
	return &MockExecutable_Execute_Call{Call: _e.mock.On("Execute", ctx, scope)}
}

func (_c *MockExecutable_Execute_Call) Run(run func(ctx context.Context, scope *Scope)) *MockExecutable_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Scope
		if args[1] != nil {
			arg1 = args[1].(*Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExecutable_Execute_Call) Return(nextState string, err error) *MockExecutable_Execute_Call {
	_c.Call.Return(nextState, err)
	return _c
}

func (_c *MockExecutable_Execute_Call) RunAndReturn(run func(ctx context.Context, scope *Scope) (string, error)) *MockExecutable_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockExecutable
func (_mock *MockExecutable) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockExecutable_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockExecutable_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockExecutable_Expecter) ID() *MockExecutable_ID_Call {
	return &MockExecutable_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockExecutable_ID_Call) Run(run func()) *MockExecutable_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExecutable_ID_Call) Return(s string) *MockExecutable_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockExecutable_ID_Call) RunAndReturn(run func() string) *MockExecutable_ID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmitter creates a new instance of MockEmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmitter {
	mock := &MockEmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmitter is an autogenerated mock type for the Emitter type
type MockEmitter struct {
	mock.Mock
}

type MockEmitter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmitter) EXPECT() *MockEmitter_Expecter {
	return &MockEmitter_Expecter{mock: &_m.Mock}
}

// AddTransition provides a mock function for the type MockEmitter
func (_mock *MockEmitter) AddTransition(port string, tr Transition) error {
	ret := _mock.Called(port, tr)

	if len(ret) == 0 {
		panic("no return value specified for AddTransition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, Transition) error); ok {
		r0 = returnFunc(port, tr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmitter_AddTransition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTransition'
type MockEmitter_AddTransition_Call struct {
	*mock.Call
}

// AddTransition is a helper method to define mock.On call
//   - port string
//   - tr Transition
func (_e *MockEmitter_Expecter) AddTransition(port interface{}, tr interface{}) *MockEmitter_AddTransition_Call {
	return &MockEmitter_AddTransition_Call{Call: _e.mock.On("AddTransition", port, tr)}
}

func (_c *MockEmitter_AddTransition_Call) Run(run func(port string, tr Transition)) *MockEmitter_AddTransition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 Transition
		if args[1] != nil {
			arg1 = args[1].(Transition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmitter_AddTransition_Call) Return(err error) *MockEmitter_AddTransition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmitter_AddTransition_Call) RunAndReturn(run func(port string, tr Transition) error) *MockEmitter_AddTransition_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockEmitter
func (_mock *MockEmitter) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEmitter_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockEmitter_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockEmitter_Expecter) ID() *MockEmitter_ID_Call {
	return &MockEmitter_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockEmitter_ID_Call) Run(run func()) *MockEmitter_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEmitter_ID_Call) Return(s string) *MockEmitter_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEmitter_ID_Call) RunAndReturn(run func() string) *MockEmitter_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Outputs provides a mock function for the type MockEmitter
func (_mock *MockEmitter) Outputs() map[string]workflowapi.DataType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Outputs")
	}

	var r0 map[string]workflowapi.DataType
	if returnFunc, ok := ret.Get(0).(func() map[string]workflowapi.DataType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]workflowapi.DataType)
		}
	}
	return r0
}

// MockEmitter_Outputs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Outputs'
type MockEmitter_Outputs_Call struct {
	*mock.Call
}

// Outputs is a helper method to define mock.On call
func (_e *MockEmitter_Expecter) Outputs() *MockEmitter_Outputs_Call {
	return &MockEmitter_Outputs_Call{Call: _e.mock.On("Outputs")}
}

func (_c *MockEmitter_Outputs_Call) Run(run func()) *MockEmitter_Outputs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEmitter_Outputs_Call) Return(stringToDataType map[string]workflowapi.DataType) *MockEmitter_Outputs_Call {
	_c.Call.Return(stringToDataType)
	return _c
}

func (_c *MockEmitter_Outputs_Call) RunAndReturn(run func() map[string]workflowapi.DataType) *MockEmitter_Outputs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHasSetup creates a new instance of MockHasSetup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasSetup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasSetup {
	mock := &MockHasSetup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHasSetup is an autogenerated mock type for the HasSetup type
type MockHasSetup struct {
	mock.Mock
}

type MockHasSetup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasSetup) EXPECT() *MockHasSetup_Expecter {
	return &MockHasSetup_Expecter{mock: &_m.Mock}
}

// Setup provides a mock function for the type MockHasSetup
func (_mock *MockHasSetup) Setup(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHasSetup_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type MockHasSetup_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHasSetup_Expecter) Setup(ctx interface{}) *MockHasSetup_Setup_Call {
	return &MockHasSetup_Setup_Call{Call: _e.mock.On("Setup", ctx)}
}

func (_c *MockHasSetup_Setup_Call) Run(run func(ctx context.Context)) *MockHasSetup_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHasSetup_Setup_Call) Return(err error) *MockHasSetup_Setup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHasSetup_Setup_Call) RunAndReturn(run func(ctx context.Context) error) *MockHasSetup_Setup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockToolProvider creates a new instance of MockToolProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolProvider {
	mock := &MockToolProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolProvider is an autogenerated mock type for the ToolProvider type
type MockToolProvider struct {
	mock.Mock
}

type MockToolProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolProvider) EXPECT() *MockToolProvider_Expecter {
	return &MockToolProvider_Expecter{mock: &_m.Mock}
}

// Tools provides a mock function for the type MockToolProvider
func (_mock *MockToolProvider) Tools() ([]llmproxy.FunctionTool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tools")
	}

	var r0 []llmproxy.FunctionTool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]llmproxy.FunctionTool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []llmproxy.FunctionTool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]llmproxy.FunctionTool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockToolProvider_Tools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tools'
type MockToolProvider_Tools_Call struct {
	*mock.Call
}

// Tools is a helper method to define mock.On call
func (_e *MockToolProvider_Expecter) Tools() *MockToolProvider_Tools_Call {
	return &MockToolProvider_Tools_Call{Call: _e.mock.On("Tools")}
}

func (_c *MockToolProvider_Tools_Call) Run(run func()) *MockToolProvider_Tools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToolProvider_Tools_Call) Return(functionTools []llmproxy.FunctionTool, err error) *MockToolProvider_Tools_Call {
	_c.Call.Return(functionTools, err)
	return _c
}

func (_c *MockToolProvider_Tools_Call) RunAndReturn(run func() ([]llmproxy.FunctionTool, error)) *MockToolProvider_Tools_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLlmClient creates a new instance of MockLlmClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLlmClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLlmClient {
	mock := &MockLlmClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLlmClient is an autogenerated mock type for the LlmClient type
type MockLlmClient struct {
	mock.Mock
}

type MockLlmClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLlmClient) EXPECT() *MockLlmClient_Expecter {
	return &MockLlmClient_Expecter{mock: &_m.Mock}
}

// Chat provides a mock function for the type MockLlmClient
func (_mock *MockLlmClient) Chat(ctx context.Context, req *llmproxy.ChatRequest) (*llmproxy.ChatResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 *llmproxy.ChatResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *llmproxy.ChatRequest) (*llmproxy.ChatResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *llmproxy.ChatRequest) *llmproxy.ChatResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*llmproxy.ChatResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *llmproxy.ChatRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLlmClient_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockLlmClient_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - req *llmproxy.ChatRequest
func (_e *MockLlmClient_Expecter) Chat(ctx interface{}, req interface{}) *MockLlmClient_Chat_Call {
	return &MockLlmClient_Chat_Call{Call: _e.mock.On("Chat", ctx, req)}
}

func (_c *MockLlmClient_Chat_Call) Run(run func(ctx context.Context, req *llmproxy.ChatRequest)) *MockLlmClient_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *llmproxy.ChatRequest
		if args[1] != nil {
			arg1 = args[1].(*llmproxy.ChatRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLlmClient_Chat_Call) Return(chatResponse *llmproxy.ChatResponse, err error) *MockLlmClient_Chat_Call {
	_c.Call.Return(chatResponse, err)
	return _c
}

func (_c *MockLlmClient_Chat_Call) RunAndReturn(run func(ctx context.Context, req *llmproxy.ChatRequest) (*llmproxy.ChatResponse, error)) *MockLlmClient_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRetriever creates a new instance of MockRetriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRetriever(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRetriever {
	mock := &MockRetriever{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRetriever is an autogenerated mock type for the Retriever type
type MockRetriever struct {
	mock.Mock
}

type MockRetriever_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRetriever) EXPECT() *MockRetriever_Expecter {
	return &MockRetriever_Expecter{mock: &_m.Mock}
}

// QueryRAG provides a mock function for the type MockRetriever
func (_mock *MockRetriever) QueryRAG(ctx context.Context, params RAGQueryParams) ([]RAGQueryResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for QueryRAG")
	}

	var r0 []RAGQueryResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, RAGQueryParams) ([]RAGQueryResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, RAGQueryParams) []RAGQueryResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]RAGQueryResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, RAGQueryParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRetriever_QueryRAG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRAG'
type MockRetriever_QueryRAG_Call struct {
	*mock.Call
}

// QueryRAG is a helper method to define mock.On call
//   - ctx context.Context
//   - params RAGQueryParams
func (_e *MockRetriever_Expecter) QueryRAG(ctx interface{}, params interface{}) *MockRetriever_QueryRAG_Call {
	return &MockRetriever_QueryRAG_Call{Call: _e.mock.On("QueryRAG", ctx, params)}
}

func (_c *MockRetriever_QueryRAG_Call) Run(run func(ctx context.Context, params RAGQueryParams)) *MockRetriever_QueryRAG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 RAGQueryParams
		if args[1] != nil {
			arg1 = args[1].(RAGQueryParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRetriever_QueryRAG_Call) Return(rAGQueryResults []RAGQueryResult, err error) *MockRetriever_QueryRAG_Call {
	_c.Call.Return(rAGQueryResults, err)
	return _c
}

func (_c *MockRetriever_QueryRAG_Call) RunAndReturn(run func(ctx context.Context, params RAGQueryParams) ([]RAGQueryResult, error)) *MockRetriever_QueryRAG_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMLClient creates a new instance of MockMLClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMLClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMLClient {
	mock := &MockMLClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMLClient is an autogenerated mock type for the MLClient type
type MockMLClient struct {
	mock.Mock
}

type MockMLClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMLClient) EXPECT() *MockMLClient_Expecter {
	return &MockMLClient_Expecter{mock: &_m.Mock}
}

// BinaryInference provides a mock function for the type MockMLClient
func (_mock *MockMLClient) BinaryInference(ctx context.Context, model string, data []byte) (InferenceResult, error) {
	ret := _mock.Called(ctx, model, data)

	if len(ret) == 0 {
		panic("no return value specified for BinaryInference")
	}

	var r0 InferenceResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (InferenceResult, error)); ok {
		return returnFunc(ctx, model, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) InferenceResult); ok {
		r0 = returnFunc(ctx, model, data)
	} else {
		r0 = ret.Get(0).(InferenceResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, model, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMLClient_BinaryInference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BinaryInference'
type MockMLClient_BinaryInference_Call struct {
	*mock.Call
}

// BinaryInference is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
//   - data []byte
func (_e *MockMLClient_Expecter) BinaryInference(ctx interface{}, model interface{}, data interface{}) *MockMLClient_BinaryInference_Call {
	return &MockMLClient_BinaryInference_Call{Call: _e.mock.On("BinaryInference", ctx, model, data)}
}

func (_c *MockMLClient_BinaryInference_Call) Run(run func(ctx context.Context, model string, data []byte)) *MockMLClient_BinaryInference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMLClient_BinaryInference_Call) Return(inferenceResult InferenceResult, err error) *MockMLClient_BinaryInference_Call {
	_c.Call.Return(inferenceResult, err)
	return _c
}

func (_c *MockMLClient_BinaryInference_Call) RunAndReturn(run func(ctx context.Context, model string, data []byte) (InferenceResult, error)) *MockMLClient_BinaryInference_Call {
	_c.Call.Return(run)
	return _c
}

// TensorInference provides a mock function for the type MockMLClient
func (_mock *MockMLClient) TensorInference(ctx context.Context, model string, tensors map[string]any) (InferenceResult, error) {
	ret := _mock.Called(ctx, model, tensors)

	if len(ret) == 0 {
		panic("no return value specified for TensorInference")
	}

	var r0 InferenceResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) (InferenceResult, error)); ok {
		return returnFunc(ctx, model, tensors)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) InferenceResult); ok {
		r0 = returnFunc(ctx, model, tensors)
	} else {
		r0 = ret.Get(0).(InferenceResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]any) error); ok {
		r1 = returnFunc(ctx, model, tensors)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMLClient_TensorInference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TensorInference'
type MockMLClient_TensorInference_Call struct {
	*mock.Call
}

// TensorInference is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
//   - tensors map[string]any
func (_e *MockMLClient_Expecter) TensorInference(ctx interface{}, model interface{}, tensors interface{}) *MockMLClient_TensorInference_Call {
	return &MockMLClient_TensorInference_Call{Call: _e.mock.On("TensorInference", ctx, model, tensors)}
}

func (_c *MockMLClient_TensorInference_Call) Run(run func(ctx context.Context, model string, tensors map[string]any)) *MockMLClient_TensorInference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMLClient_TensorInference_Call) Return(inferenceResult InferenceResult, err error) *MockMLClient_TensorInference_Call {
	_c.Call.Return(inferenceResult, err)
	return _c
}

func (_c *MockMLClient_TensorInference_Call) RunAndReturn(run func(ctx context.Context, model string, tensors map[string]any) (InferenceResult, error)) *MockMLClient_TensorInference_Call {
	_c.Call.Return(run)
	return _c
}
