// Package deployapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package deployapi

import (
	"time"

	externalRef0 "github.com/ForestHubAI/edge-agents/go/api/engineapi"
)

// Defines values for DeploymentSpecStatus.
const (
	Active   DeploymentSpecStatus = "active"
	Inactive DeploymentSpecStatus = "inactive"
)

// Valid indicates whether the value is a known member of the DeploymentSpecStatus enum.
func (e DeploymentSpecStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Inactive:
		return true
	default:
		return false
	}
}

// ComponentImage Resolved OCI image reference for a component, frozen at packaging time. A renderer pulls repository@digest when a digest is present (reproducible, since tags are mutable) and repository:tag otherwise. The repository carries its registry host, so the same coordinate resolves against the public registry for an OSS component or a private one for a future paid component with no schema change.
type ComponentImage struct {
	// Digest Optional content digest, e.g. "sha256:abc123...". When set, the renderer pulls repository@digest for an immutable, reproducible pull; the tag stays for readability. Recommended for the reconcile/rollback (paid) path, where a moved tag would otherwise break determinism.
	Digest *string `json:"digest,omitempty"`

	// Repository Image repository, registry host included, e.g. "ghcr.io/foresthubai/engine". A bare name (no host) resolves against the local daemon — the air-gap / build-locally case.
	Repository string `json:"repository"`

	// Tag Human-readable version tag, e.g. "1.1.0". Explicit, never "latest" for a real release — a deployment pins exact versions. Used for the pull when no digest is set, and kept for readability when one is.
	Tag string `json:"tag"`
}

// ComponentSet The closed, known set of components a device can run for one deployment. Not a generic component registry or dependency solver — each slot is a named, optional component the packaging step populates from the workflow's needs. A workflow that uses no custom models omits llamaServer; one with no engine workflow omits engine.
type ComponentSet struct {
	// Engine The ForestHub engine container: the workflow runtime plus its in-process driver I/O. deviceGrants and privileged are the resolved container-level hardware access the engine needs — computed once from the workflow's hardware channels against the device manifest and frozen here, so the renderer passes them through verbatim rather than recomputing them.
	Engine *EngineComponent `json:"engine,omitempty"`

	// LlamaServer One llama-server sidecar per on-device custom model the workflow declares. The engine reaches each over the container network by service name. Absent when the workflow declares no on-device models — network models are plain external-resource endpoints in the engine config, not sidecars run here. One image serves every sidecar; the models differ per sidecar.
	LlamaServer *LlamaServerComponent `json:"llamaServer,omitempty"`

	// MqttBroker An MQTT broker container run as part of this deployment. Modeled now but not yet populated by the OSS packaging step, which currently treats brokers as pre-existing external services (an MQTT connection in the engine config's external resources). config is intentionally loose until the broker component lands in the repo.
	MqttBroker *MqttBrokerComponent `json:"mqttBroker,omitempty"`
}

// DeploymentSpec The resolved set of components to run on one device for one deployment, plus its identity and lifecycle status. The spec is resolved and explicit — every decision (which components run, which device nodes the engine is granted) is computed once by the packaging step and frozen here, so a renderer renders it without re-deriving anything. This is the cross-language artifact the OSS CLI and the paid control plane both emit identically, hence its place in the contract.
type DeploymentSpec struct {
	// Components The closed, known set of components a device can run for one deployment. Not a generic component registry or dependency solver — each slot is a named, optional component the packaging step populates from the workflow's needs. A workflow that uses no custom models omits llamaServer; one with no engine workflow omits engine.
	Components ComponentSet `json:"components"`

	// CreatedAt When the packaging step produced this spec. Stamped by the producer; drives deployment history ordering.
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Id Stable identifier for this deployment, used as the rollback/history key. A slug in the OSS path, a uuid in the paid path; left as a free string so neither path is over-constrained.
	Id string `json:"id"`

	// SchemaVersion Spec format version, currently 1. Bumped when the spec shape changes incompatibly.
	SchemaVersion int `json:"schemaVersion"`

	// Status Whether this spec is the one a device should currently be running. The active spec is the reconcile/render target; inactive specs are history or rollback candidates.
	Status DeploymentSpecStatus `json:"status"`
}

// DeploymentSpecStatus Whether this spec is the one a device should currently be running. The active spec is the reconcile/render target; inactive specs are history or rollback candidates.
type DeploymentSpecStatus string

// EngineComponent The ForestHub engine container: the workflow runtime plus its in-process driver I/O. deviceGrants and privileged are the resolved container-level hardware access the engine needs — computed once from the workflow's hardware channels against the device manifest and frozen here, so the renderer passes them through verbatim rather than recomputing them.
type EngineComponent struct {
	// Config The engine's complete boot input, loaded once at startup from a single file — the engine is immutable, with no runtime hot-swap. Bundles the binding-free workflow, the deploy mapping that binds its logical resource ids to this environment, the resolved external-resource configs those bindings point at, and the device manifest (the hardware catalog the mapping resolves against). The deployment-scoped parts and the device-scoped manifest have different owners in the control plane; the renderer merges them into this one blob for the engine. A workflow is required — an engine exists only to run one. The engine still validates it at boot and fails fast if it is missing, since JSON unmarshalling does not enforce required fields.
	Config externalRef0.EngineConfig `json:"config"`

	// DeviceGrants Resolved host device nodes to pass into the engine container, e.g. "/dev/gpiochip0", "/dev/ttyUSB0". One entry per distinct cdev node the workflow's GPIO/serial channels bind. Empty when the workflow uses no cdev hardware; ADC/DAC/PWM have no single node and go through privileged instead.
	DeviceGrants *[]string `json:"deviceGrants,omitempty"`

	// Image Resolved OCI image reference for a component, frozen at packaging time. A renderer pulls repository@digest when a digest is present (reproducible, since tags are mutable) and repository:tag otherwise. The repository carries its registry host, so the same coordinate resolves against the public registry for an OSS component or a private one for a future paid component with no schema change.
	Image ComponentImage `json:"image"`

	// Privileged Run the engine container privileged. Required for ADC/DAC/PWM, which use sysfs paths (/sys/class/pwm, /sys/bus/iio) with no single device node to grant. False when the workflow uses only cdev hardware or none.
	Privileged *bool `json:"privileged,omitempty"`
}

// LlamaModel One on-device model served by a llama-server sidecar.
type LlamaModel struct {
	// CtxSize Context window size to start llama-server with. Renderer-chosen default when omitted.
	CtxSize *int `json:"ctxSize,omitempty"`

	// Id Workflow model id the sidecar serves; the engine's external-resource entry for this model points at this sidecar.
	Id string `json:"id"`

	// ModelFile GGUF filename to load, resolved relative to the renderer's models directory (llama-server loads GGUF only).
	ModelFile string `json:"modelFile"`

	// Port Port the sidecar listens on inside the container network. Defaults to 8080 when omitted.
	Port *int `json:"port,omitempty"`
}

// LlamaServerComponent One llama-server sidecar per on-device custom model the workflow declares. The engine reaches each over the container network by service name. Absent when the workflow declares no on-device models — network models are plain external-resource endpoints in the engine config, not sidecars run here. One image serves every sidecar; the models differ per sidecar.
type LlamaServerComponent struct {
	// Image Resolved OCI image reference for a component, frozen at packaging time. A renderer pulls repository@digest when a digest is present (reproducible, since tags are mutable) and repository:tag otherwise. The repository carries its registry host, so the same coordinate resolves against the public registry for an OSS component or a private one for a future paid component with no schema change.
	Image  ComponentImage `json:"image"`
	Models []LlamaModel   `json:"models"`
}

// MqttBrokerComponent An MQTT broker container run as part of this deployment. Modeled now but not yet populated by the OSS packaging step, which currently treats brokers as pre-existing external services (an MQTT connection in the engine config's external resources). config is intentionally loose until the broker component lands in the repo.
type MqttBrokerComponent struct {
	// Config Broker configuration blob; shape defined when the broker component is added to the repo.
	Config *map[string]interface{} `json:"config,omitempty"`

	// Image Resolved OCI image reference for a component, frozen at packaging time. A renderer pulls repository@digest when a digest is present (reproducible, since tags are mutable) and repository:tag otherwise. The repository carries its registry host, so the same coordinate resolves against the public registry for an OSS component or a private one for a future paid component with no schema change.
	Image ComponentImage `json:"image"`
}
