// Package mqttapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package mqttapi

// MQTTBrokerConfig The MQTT broker component's boot config, read once at startup. Names the roster: the devices allowed to connect. Authoritative — the broker admits only rostered identities. Per-device credentials are delivered out of band in the component secret file, keyed by the same device id, so this config carries no secret.
type MQTTBrokerConfig struct {
	// Roster Device ids permitted to connect to this broker.
	Roster []string `json:"roster"`
}
