// Package llmapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package llmapi

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ContentType.
const (
	Applicationjson ContentType = "application/json"
	Applicationpdf  ContentType = "application/pdf"
	Applicationzip  ContentType = "application/zip"
	Imagejpeg       ContentType = "image/jpeg"
	Imagepng        ContentType = "image/png"
	Textcsv         ContentType = "text/csv"
	Textplain       ContentType = "text/plain"
)

// Valid indicates whether the value is a known member of the ContentType enum.
func (e ContentType) Valid() bool {
	switch e {
	case Applicationjson:
		return true
	case Applicationpdf:
		return true
	case Applicationzip:
		return true
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	case Textcsv:
		return true
	case Textplain:
		return true
	default:
		return false
	}
}

// Defines values for LLMExternalToolType.
const (
	External LLMExternalToolType = "external"
)

// Valid indicates whether the value is a known member of the LLMExternalToolType enum.
func (e LLMExternalToolType) Valid() bool {
	switch e {
	case External:
		return true
	default:
		return false
	}
}

// Defines values for LLMWebSearchToolType.
const (
	WebSearch LLMWebSearchToolType = "web_search"
)

// Valid indicates whether the value is a known member of the LLMWebSearchToolType enum.
func (e LLMWebSearchToolType) Valid() bool {
	switch e {
	case WebSearch:
		return true
	default:
		return false
	}
}

// Defines values for ModelCapability.
const (
	Chat           ModelCapability = "chat"
	Classification ModelCapability = "classification"
	Code           ModelCapability = "code"
	Embedding      ModelCapability = "embedding"
	FineTuning     ModelCapability = "fine_tuning"
	FunctionCall   ModelCapability = "function_call"
	Reasoning      ModelCapability = "reasoning"
	Vision         ModelCapability = "vision"
)

// Valid indicates whether the value is a known member of the ModelCapability enum.
func (e ModelCapability) Valid() bool {
	switch e {
	case Chat:
		return true
	case Classification:
		return true
	case Code:
		return true
	case Embedding:
		return true
	case FineTuning:
		return true
	case FunctionCall:
		return true
	case Reasoning:
		return true
	case Vision:
		return true
	default:
		return false
	}
}

// ChatRequest LLM response generation request.
type ChatRequest struct {
	FileIDs   []string `json:"fileIDs,omitempty"`
	ImageIDs  []string `json:"imageIDs,omitempty"`
	ImageURLs []string `json:"imageURLs,omitempty"`
	Input     LLMInput `json:"input"`

	// Model Model name.
	Model string `json:"model"`

	// Options Model generation options.
	Options            *LLMOptions `json:"options,omitempty"`
	PreviousResponseID string      `json:"previousResponseID,omitempty"`

	// ResponseFormat Structured response format for LLM outputs.
	ResponseFormat *ResponseFormat `json:"responseFormat,omitempty"`

	// SystemPrompt Overrides the model's default system prompt.
	SystemPrompt string    `json:"systemPrompt,omitempty"`
	Tools        []LLMTool `json:"tools,omitempty"`
}

// ChatResponse LLM response.
type ChatResponse struct {
	Citations        []Citation        `json:"citations,omitempty"`
	ResponseID       string            `json:"responseID"`
	Text             string            `json:"text,omitempty"`
	TokensUsed       int               `json:"tokensUsed"`
	ToolCallRequests []ToolCallRequest `json:"toolCallRequests,omitempty"`
}

// Citation A source reference attached to a span of assistant-generated text.
type Citation struct {
	// EndIdx End offset into the assistant message text.
	EndIdx *int `json:"endIdx,omitempty"`

	// Snippet The cited text excerpt from the source.
	Snippet *string `json:"snippet,omitempty"`

	// StartIdx Start offset into the assistant message text.
	StartIdx *int `json:"startIdx,omitempty"`

	// Title The source's title.
	Title *string `json:"title,omitempty"`

	// Url The cited source URL.
	Url string `json:"url"`
}

// ContentType MIME type of a file.
type ContentType string

// FileUpload Uploaded file result.
type FileUpload struct {
	FileID   string `json:"fileID"`
	FileName string `json:"fileName"`
}

// FileUploadRequest File upload request.
type FileUploadRequest struct {
	File     openapi_types.File `json:"file"`
	FileName string             `json:"fileName"`

	// FileType MIME type of a file.
	FileType   ContentType `json:"fileType"`
	ProviderID string      `json:"providerID"`
	Purpose    *string     `json:"purpose,omitempty"`
}

// LLMExternalTool An external tool that can be called by the model.
type LLMExternalTool struct {
	// Description Description of the tool and its purpose.
	Description string `json:"description,omitempty"`

	// Name Name of the tool.
	Name string `json:"name"`

	// Parameters JSON schema describing the tool's parameters.
	Parameters map[string]interface{} `json:"parameters"`
	Type       LLMExternalToolType    `json:"type"`
}

// LLMExternalToolType defines model for LLMExternalTool.Type.
type LLMExternalToolType string

// LLMInput defines model for LLMInput.
type LLMInput struct {
	union json.RawMessage
}

// LLMInput1 defines model for .
type LLMInput1 = []LLMInput_1_Item

// LLMInput_1_Item defines model for LLMInput.1.Item.
type LLMInput_1_Item struct {
	union json.RawMessage
}

// LLMInputString Input string to the model.
type LLMInputString struct {
	// Value The input text.
	Value string `json:"value"`
}

// LLMOptions Model generation options.
type LLMOptions struct {
	FrequencyPenalty *float32 `json:"frequencyPenalty,omitempty"`
	MaxTokens        *int     `json:"maxTokens,omitempty"`
	PresencePenalty  *float32 `json:"presencePenalty,omitempty"`
	Seed             *int     `json:"seed,omitempty"`
	Temperature      *float32 `json:"temperature,omitempty"`
	TopK             *int     `json:"topK,omitempty"`
	TopP             *float32 `json:"topP,omitempty"`
}

// LLMTool defines model for LLMTool.
type LLMTool struct {
	union json.RawMessage
}

// LLMWebSearchTool A built-in web search tool that allows the model to search the web.
type LLMWebSearchTool struct {
	Type LLMWebSearchToolType `json:"type"`
}

// LLMWebSearchToolType defines model for LLMWebSearchTool.Type.
type LLMWebSearchToolType string

// ModelCapability defines model for ModelCapability.
type ModelCapability string

// ModelInfo Information about an available LLM model.
type ModelInfo struct {
	// Capabilities Capabilities supported by the model.
	Capabilities []ModelCapability `json:"capabilities"`

	// EmbeddingDimension Dimension of the model's embedding output (only applicable for embedding-capable models)
	EmbeddingDimension *int `json:"embeddingDimension,omitempty"`

	// Id Unique identifier of the model.
	Id string `json:"id"`

	// Label Human-readable model name.
	Label string `json:"label"`

	// MaxTokens Maximum number of tokens supported by the model.
	MaxTokens *int `json:"maxTokens,omitempty"`

	// Provider Provider that hosts the model.
	Provider string `json:"provider"`

	// TokenModifier Multiplier to apply to input token count when estimating usage for billing purposes (e.g. 1.2 means "20% more tokens than actual input count")
	TokenModifier float32 `json:"tokenModifier"`
}

// ProviderInfo defines model for ProviderInfo.
type ProviderInfo struct {
	// Id Provider identifier (e.g. OpenAI, Anthropic, Local).
	Id string `json:"id"`

	// Models Concrete models (only populated for Local provider).
	Models []ModelInfo `json:"models"`
}

// ResponseFormat Structured response format for LLM outputs.
type ResponseFormat struct {
	Description *string                `json:"description,omitempty"`
	Name        string                 `json:"name"`
	Schema      map[string]interface{} `json:"schema"`
}

// ToolCallRequest Request made by the model to call an external tool.
type ToolCallRequest struct {
	// Arguments Arguments passed to the function tool.
	Arguments json.RawMessage `json:"arguments"`

	// CallId Unique ID of the function tool call request.
	CallId string `json:"callId"`

	// Name Name of the function tool called.
	Name string `json:"name"`
}

// ToolResult Result of an external tool execution.
type ToolResult struct {
	// CallId Unique ID of the external tool call request.
	CallId string `json:"callId"`

	// Name Name of the external tool called.
	Name string `json:"name"`

	// Output Output returned by the external tool.
	Output map[string]interface{} `json:"output"`
}

// AsLLMInputString returns the union data inside the LLMInput as a LLMInputString
func (t LLMInput) AsLLMInputString() (LLMInputString, error) {
	var body LLMInputString
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLLMInputString overwrites any union data inside the LLMInput as the provided LLMInputString
func (t *LLMInput) FromLLMInputString(v LLMInputString) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLLMInputString performs a merge with any union data inside the LLMInput, using the provided LLMInputString
func (t *LLMInput) MergeLLMInputString(v LLMInputString) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLLMInput1 returns the union data inside the LLMInput as a LLMInput1
func (t LLMInput) AsLLMInput1() (LLMInput1, error) {
	var body LLMInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLLMInput1 overwrites any union data inside the LLMInput as the provided LLMInput1
func (t *LLMInput) FromLLMInput1(v LLMInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLLMInput1 performs a merge with any union data inside the LLMInput, using the provided LLMInput1
func (t *LLMInput) MergeLLMInput1(v LLMInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LLMInput) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LLMInput) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsLLMInputString returns the union data inside the LLMInput_1_Item as a LLMInputString
func (t LLMInput_1_Item) AsLLMInputString() (LLMInputString, error) {
	var body LLMInputString
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLLMInputString overwrites any union data inside the LLMInput_1_Item as the provided LLMInputString
func (t *LLMInput_1_Item) FromLLMInputString(v LLMInputString) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLLMInputString performs a merge with any union data inside the LLMInput_1_Item, using the provided LLMInputString
func (t *LLMInput_1_Item) MergeLLMInputString(v LLMInputString) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsToolCallRequest returns the union data inside the LLMInput_1_Item as a ToolCallRequest
func (t LLMInput_1_Item) AsToolCallRequest() (ToolCallRequest, error) {
	var body ToolCallRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromToolCallRequest overwrites any union data inside the LLMInput_1_Item as the provided ToolCallRequest
func (t *LLMInput_1_Item) FromToolCallRequest(v ToolCallRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeToolCallRequest performs a merge with any union data inside the LLMInput_1_Item, using the provided ToolCallRequest
func (t *LLMInput_1_Item) MergeToolCallRequest(v ToolCallRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsToolResult returns the union data inside the LLMInput_1_Item as a ToolResult
func (t LLMInput_1_Item) AsToolResult() (ToolResult, error) {
	var body ToolResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromToolResult overwrites any union data inside the LLMInput_1_Item as the provided ToolResult
func (t *LLMInput_1_Item) FromToolResult(v ToolResult) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeToolResult performs a merge with any union data inside the LLMInput_1_Item, using the provided ToolResult
func (t *LLMInput_1_Item) MergeToolResult(v ToolResult) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LLMInput_1_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LLMInput_1_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsLLMExternalTool returns the union data inside the LLMTool as a LLMExternalTool
func (t LLMTool) AsLLMExternalTool() (LLMExternalTool, error) {
	var body LLMExternalTool
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLLMExternalTool overwrites any union data inside the LLMTool as the provided LLMExternalTool
func (t *LLMTool) FromLLMExternalTool(v LLMExternalTool) error {
	v.Type = "external"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLLMExternalTool performs a merge with any union data inside the LLMTool, using the provided LLMExternalTool
func (t *LLMTool) MergeLLMExternalTool(v LLMExternalTool) error {
	v.Type = "external"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLLMWebSearchTool returns the union data inside the LLMTool as a LLMWebSearchTool
func (t LLMTool) AsLLMWebSearchTool() (LLMWebSearchTool, error) {
	var body LLMWebSearchTool
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLLMWebSearchTool overwrites any union data inside the LLMTool as the provided LLMWebSearchTool
func (t *LLMTool) FromLLMWebSearchTool(v LLMWebSearchTool) error {
	v.Type = "web_search"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLLMWebSearchTool performs a merge with any union data inside the LLMTool, using the provided LLMWebSearchTool
func (t *LLMTool) MergeLLMWebSearchTool(v LLMWebSearchTool) error {
	v.Type = "web_search"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LLMTool) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t LLMTool) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "external":
		return t.AsLLMExternalTool()
	case "web_search":
		return t.AsLLMWebSearchTool()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t LLMTool) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LLMTool) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
