#!/usr/bin/env sh
# ForestHub MQTT broker component — config-bridge entrypoint.
#
# Renders mosquitto's native auth files from the component boot config and secret
# file, then execs mosquitto. Auth (password_file) and ACL (acl_file) are enforced
# entirely offline by mosquitto — no plugin, no backend callback — so the broker
# keeps authorizing local traffic under a cloud partition.
#
# Boot config (JSON at $CONFIG):  {"roster":["dev-a","dev-b"]}
#   roster = device ids allowed to connect (contract/mqtt.yaml MQTTBrokerConfig).
# Secret file (JSON at $SECRETS): {"dev-a":"$7$...","dev-b":"$7$..."}
#   per-device mosquitto PBKDF2 password hash, keyed by the same device id.
set -eu

CONFIG="${FH_CONFIG_FILE:-/etc/foresthub/config.json}"
SECRETS="${FH_SECRETS_FILE:-/etc/foresthub/secrets.json}"
BROKER_CONF="${FH_MOSQUITTO_CONF:-/mosquitto/config/mosquitto.conf}"
PASSWD="/mosquitto/config/passwd"
ACL="/mosquitto/config/acl"

# 78 = sysexits EX_CONFIG (the component ExitConfigError): a PERMANENT boot failure
# the orchestrator must not retry unchanged (bad config / a rostered device with no
# delivered secret).
fail() { echo "mosquitto-entrypoint: $*" >&2; exit 78; }

[ -f "$CONFIG" ]  || fail "boot config not found: $CONFIG"
[ -f "$SECRETS" ] || fail "secret file not found: $SECRETS"
jq -e '(.roster | type) == "array"' "$CONFIG" >/dev/null 2>&1 \
  || fail "boot config has no roster array: $CONFIG"

# Render both auth files in one pass over the roster (see ACL.md for the grammar):
#   - password_file: one `id:hash` line per device (hash from the secret file; a
#     rostered device with no secret is a config error).
#   - acl_file: a per-device `user` block granting subscribe anywhere on this broker
#     (tenant == broker) and publish only under the device's own `{id}/…` prefix
#     (own-prefix rule). Authenticated-user ACLs must live in `user` blocks or
#     `pattern` lines — a global `topic` applies only to anonymous clients, which are
#     off here. Explicit per-device blocks keep the ACL unambiguous and warning-free.
: > "$PASSWD"
printf '# Generated by the mosquitto entrypoint — do not edit. See ACL.md.\n' > "$ACL"
for id in $(jq -r '.roster[]' "$CONFIG"); do
  hash=$(jq -r --arg id "$id" '.[$id] // empty' "$SECRETS")
  [ -n "$hash" ] || fail "no secret delivered for rostered device: $id"
  printf '%s:%s\n' "$id" "$hash" >> "$PASSWD"
  printf 'user %s\ntopic read #\ntopic write %s/#\n' "$id" "$id" >> "$ACL"
done

# password_file must not be world-accessible or mosquitto refuses to load it.
chmod 0600 "$PASSWD" "$ACL"
chown mosquitto:mosquitto "$PASSWD" "$ACL" 2>/dev/null || true

echo "mosquitto-entrypoint: starting broker ($(jq '.roster | length' "$CONFIG") rostered devices) on :1883" >&2
exec mosquitto -c "$BROKER_CONF"
