/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The engine's complete boot input, loaded once at startup. */
        EngineConfig: {
            workflow: components["schemas"]["Workflow"];
            mapping?: components["schemas"]["ResourceMapping"];
            externalResources?: components["schemas"]["ExternalResources"];
            manifest?: components["schemas"]["DeviceManifest"];
        };
        /** @description Binds a binding-free workflow's logical resource ids to concrete platform resources, keyed by workflow resource id. */
        ResourceMapping: {
            [key: string]: components["schemas"]["ResourceAddress"];
        };
        /** @description Where one workflow resource resolves to: the shared platform resource `ref` it maps to, plus an optional sub-address selecting one served unit within it. */
        ResourceAddress: {
            /** @description Shared platform resource id this binds to. */
            ref: string;
            /** @description Per-channel physical sub-address within a driver (GPIO line / ADC-PWM-DAC channel). Driver resources only. */
            index?: number;
            /** @description Model name a shared inference endpoint (self-hosted LLM / ml-inference component) selects on for this binding. Required for endpoint bindings — the endpoint fronts several models and picks one by this name; omitted for driver/mqtt bindings. */
            model?: string;
        };
        /** @description Deploy-time configs for a workflow's non-device external resources (MQTT transports, custom-model providers, ...), keyed by platform resource id. */
        ExternalResources: {
            [key: string]: components["schemas"]["ExternalResourceConfig"];
        };
        /** @description Tagged union of deploy-time external-resource configs, discriminated by runtime kind (not by ownership — locality like on-device vs cloud lives inside an arm). New kinds extend this oneOf. */
        ExternalResourceConfig: components["schemas"]["MQTTConfig"] | components["schemas"]["LLMProviderConfig"] | components["schemas"]["MLInferenceConfig"];
        /** @description One LLM provider instance the engine registers into its single llmproxy; a workflow model reaches it by model id. localLlm: a built-in catalog adapter authenticated with a deploy-delivered API key (secrets.json, keyed by this resource's ref); `provider` names the adapter. backendLlm: that same catalog adapter's models proxied to the backend, no key; `provider` names the adapter. selfhostedLlm: a direct endpoint the llmproxy doesn't ship (`url`; optional bearer via secrets.json by ref), shared by every model bound to it. Each catalog provider is served by exactly one instance (localLlm xor backendLlm) — no catch-all, no shadowing. */
        LLMProviderConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "localLlm" | "backendLlm" | "selfhostedLlm";
            /** @description localLlm / backendLlm only — the built-in catalog adapter this instance serves (e.g. anthropic, openai). */
            provider?: string;
            /** @description selfhostedLlm only — base URL of the inference endpoint (http:// or https://). */
            url?: string;
        };
        /** @description Resolved connection to an ML inference component the engine doesn't ship: a separate service reached by URL that loads a repository of models and serves them over HTTP. The engine names a model on each request; which one is the binding's `model` sub-address (ResourceAddress.model), so many models may share one endpoint. A trusted in-deployment endpoint — no credential. */
        MLInferenceConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ml-inference";
            /** @description Base URL of the inference component (http:// or https://). */
            url: string;
        };
        /** @description Resolved connection metadata for an MQTT broker. */
        MQTTConfig: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "mqtt";
            brokerUrl: string;
            clientId?: string;
            username?: string;
            /** @description Topic prefix for workflow-level publish topics ({networkId}/{agentId}/). */
            publishPrefix?: string;
            /** @description Topic prefix for workflow-level subscribe filters ({networkId}/+/). */
            subscribePrefix?: string;
            will?: components["schemas"]["MQTTWill"];
        };
        MQTTWill: {
            topic: string;
            payload: string;
            /** @description MQTT QoS (0, 1, or 2). */
            qos: number;
            retain: boolean;
        };
        /** @description Hardware resources available on the device, keyed by driver instance ID. */
        DeviceManifest: {
            gpios?: {
                [key: string]: components["schemas"]["GPIOConfig"];
            };
            adcs?: {
                [key: string]: components["schemas"]["ADCConfig"];
            };
            dacs?: {
                [key: string]: components["schemas"]["DACConfig"];
            };
            serials?: {
                [key: string]: components["schemas"]["SerialConfig"];
            };
            pwms?: {
                [key: string]: components["schemas"]["PWMConfig"];
            };
            cameras?: {
                [key: string]: components["schemas"]["CameraSource"];
            };
        };
        GPIOConfig: {
            /** @description cdev chip name or path, e.g. "gpiochip0" or "/dev/gpiochip0" */
            chip: string;
        };
        ADCConfig: {
            /** @description sysfs path to the IIO device directory, e.g. "/sys/bus/iio/devices/iio:device0" */
            device: string;
        };
        DACConfig: {
            /** @description sysfs path to the IIO device directory, e.g. "/sys/bus/iio/devices/iio:device1" */
            device: string;
        };
        SerialConfig: {
            /** @description Serial device path, e.g. "/dev/ttyUSB0" or "COM3" */
            device: string;
            /** @description Baud rate; falls back to 115200 when zero */
            baud?: number;
        };
        PWMConfig: {
            /** @description sysfs path to the pwmchip directory, e.g. "/sys/class/pwm/pwmchip0" */
            chip: string;
        };
        RagQueryRequest: {
            /** @description Collection to query */
            collectionId: string;
            /** @description Search query text */
            query: string;
            /**
             * @description Number of results to return
             * @default 5
             */
            topK: number;
        };
        RagQueryResult: {
            chunkId: string;
            documentId: string;
            content: string;
            /** Format: double */
            score: number;
        };
        NodePosition: {
            x: number;
            y: number;
        };
        /** @enum {string} */
        SignalType: "digital" | "analog";
        Reference: {
            srcId: string;
            varId: string;
        };
        OutputBinding: {
            /** @description Discard the output if false; route it according to `mode` if true */
            active: boolean;
            /** @enum {string} */
            mode: "emit" | "assign";
            /** @description Variable name (when mode=emit) */
            name?: string;
            /** @description Existing variable to route to (when mode=assign) */
            target?: components["schemas"]["Reference"];
        };
        ReadPinNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ReadPin";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to an IO variable ID */
                pinReference?: string;
                signalType: components["schemas"]["SignalType"];
                output: components["schemas"]["OutputBinding"];
                /** @description Description used when this node is exposed as a tool; ignored in exec mode. */
                toolDescription?: string;
            };
        };
        /** @enum {string} */
        DataType: "int" | "float" | "bool" | "string" | "image";
        Expression: {
            expression: string;
            /** @description A list of referenced variable IDs used in the expression */
            references: components["schemas"]["Reference"][];
            dataType: components["schemas"]["DataType"];
        };
        WritePinNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WritePin";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to an IO variable ID */
                pinReference?: string;
                signalType: components["schemas"]["SignalType"];
                value: components["schemas"]["Expression"];
            };
        };
        OutputDeclaration: {
            /** @enum {string} */
            mode: "emit" | "assign";
            /** @description JSON property name of the declared output */
            name: string;
            dataType: components["schemas"]["DataType"];
            /** @description New variable uid (when mode=emit) */
            uid?: string;
            /** @description Existing variable to route to (when mode=assign) */
            target?: components["schemas"]["Reference"];
        };
        /** @description Reference from an LLM agent node to a declared MemoryFile with an access mode. */
        MemoryRef: {
            /** @description id of the referenced MemoryFile. */
            id: string;
            /**
             * @description r = read-only; rw = read + write.
             * @enum {string}
             */
            mode: "r" | "rw";
        };
        AgentNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Agent";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Name of the agent */
                name?: string;
                model?: string;
                instructions?: string;
                /** @description Maximum number of agent runner turns */
                maxTurns?: number;
                answer: components["schemas"]["OutputBinding"];
                /** @description Ordered list of structured-output declarations. Names must be unique within this list */
                outputDeclarations: components["schemas"]["OutputDeclaration"][];
                /** @description Memory files this agent can access, each with an access mode. */
                memoryRefs: components["schemas"]["MemoryRef"][];
                /** @description Description used when this node is exposed as a tool; ignored in exec mode. */
                toolDescription?: string;
            };
        };
        IfNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "If";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                condition: components["schemas"]["Expression"];
            };
        };
        SerialReadNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SerialRead";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to an UART ID (the serial port to read from) */
                portReference?: string;
                prompt?: string;
                output: components["schemas"]["OutputBinding"];
            };
        };
        SerialWriteNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SerialWrite";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to a UART channel ID (the serial port to write to) */
                portReference?: string;
                value: components["schemas"]["Expression"];
            };
        };
        RetrieverNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Retriever";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to a declared VectorDatabase memory id */
                memoryReference?: string;
                /** @description Number of results to return */
                topK?: number;
                /** @description Search query expression */
                query: components["schemas"]["Expression"];
                output: components["schemas"]["OutputBinding"];
                /** @description Description used when this node is exposed as a tool; ignored in exec mode. */
                toolDescription?: string;
            };
        };
        WebFetchNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WebFetch";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description URL expression to fetch (http or https) */
                url: components["schemas"]["Expression"];
                /** @description Maximum characters of extracted text to return. Defaults to 50000 when omitted or non-positive. */
                maxChars?: number;
                output: components["schemas"]["OutputBinding"];
            };
        };
        MLInferenceNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MLInference";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to an MLModel id. */
                model: string;
                /** @description Variable holding the model input. Its type is resolved at runtime and dispatched to the matching handler. */
                input: components["schemas"]["Reference"];
                output: components["schemas"]["OutputBinding"];
            };
        };
        CameraCaptureNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CameraCapture";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to a CAMERA channel id. */
                cameraReference: string;
                /** @description Capture width in pixels for this capture. The source picks its native resolution when omitted, and ignores it when it cannot size. */
                width?: number;
                /** @description Capture height in pixels for this capture. The source picks its native resolution when omitted, and ignores it when it cannot size. */
                height?: number;
                output: components["schemas"]["OutputBinding"];
            };
        };
        FunctionCallNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "FunctionCall";
            label?: string;
            position: components["schemas"]["NodePosition"];
            /** @description Id of the function this node calls. The signature is resolved from the workflow's functions table. */
            functionId: string;
            arguments: {
                inputBindings?: {
                    [key: string]: components["schemas"]["Expression"];
                };
                outputBindings?: {
                    [key: string]: components["schemas"]["OutputBinding"];
                };
                /** @description Description used when this function is exposed as a tool; ignored in exec mode. */
                toolDescription?: string;
            };
        };
        OnFunctionCallNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OnFunctionCall";
            label?: string;
            position: components["schemas"]["NodePosition"];
        };
        DelayNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Delay";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Time in milliseconds to pause execution */
                delayMs?: number;
            };
        };
        TickerNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Ticker";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description How many units between ticks */
                intervalValue?: number;
                /**
                 * @description Time unit for the interval
                 * @enum {string}
                 */
                intervalUnit: "milliseconds" | "seconds" | "minutes" | "hours";
            };
        };
        AlarmNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Alarm";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Time of day to fire (HH:MM, 24h format) */
                time?: string;
                /** @description Days of the week to fire on (empty = every day) */
                days: string[];
            };
        };
        WebSearchToolNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WebSearchTool";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Maximum number of search results to return per call. Defaults to 5 when omitted or non-positive. Capped at 20. */
                maxResults?: number;
            };
        };
        OnStartupNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OnStartup";
            label?: string;
            position: components["schemas"]["NodePosition"];
        };
        OnPinEdgeNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OnPinEdge";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description IO variable ID of the digital pin to watch */
                pinReference?: string;
                /**
                 * @description Edge transition that fires the trigger
                 * @enum {string}
                 */
                edge: "rising" | "falling" | "both";
            };
        };
        OnSerialReceiveNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OnSerialReceive";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to an IO variable ID (the serial port to listen on) */
                portReference?: string;
                output: components["schemas"]["OutputBinding"];
            };
        };
        OnThresholdNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OnThreshold";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Numeric variable to watch for threshold crossings */
                variable?: components["schemas"]["Reference"];
                /** @description Value the variable crosses to fire the trigger */
                threshold?: number;
                /**
                 * @description Crossing direction to fire on (default both)
                 * @enum {string}
                 */
                direction: "rising" | "falling" | "both";
                /** @description Hysteresis band width around threshold; 0 disables (default 0) */
                deadband?: number;
                /** @description Optional binding for the triggering value */
                output: components["schemas"]["OutputBinding"];
            };
        };
        SetVariableNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SetVariable";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                variable?: components["schemas"]["Reference"];
                value: components["schemas"]["Expression"];
            };
        };
        MqttPublishNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MqttPublish";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to an MQTT channel ID (the channel carries the topic; resolved to a broker at deploy time) */
                channelReference?: string;
                dataType: components["schemas"]["DataType"];
                value: components["schemas"]["Expression"];
                /**
                 * @description MQTT Quality of Service level
                 * @enum {integer}
                 */
                qos: 0 | 1 | 2;
                /** @description Whether the broker should retain the message */
                retain: boolean;
            };
        };
        OnMqttMessageNode: {
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OnMqttMessage";
            label?: string;
            position: components["schemas"]["NodePosition"];
            arguments: {
                /** @description Reference to an MQTT channel ID (the channel carries the topic filter; resolved to a broker at deploy time) */
                channelReference?: string;
                dataType: components["schemas"]["DataType"];
                output: components["schemas"]["OutputBinding"];
            };
        };
        Node: components["schemas"]["ReadPinNode"] | components["schemas"]["WritePinNode"] | components["schemas"]["AgentNode"] | components["schemas"]["IfNode"] | components["schemas"]["SerialReadNode"] | components["schemas"]["SerialWriteNode"] | components["schemas"]["RetrieverNode"] | components["schemas"]["WebFetchNode"] | components["schemas"]["MLInferenceNode"] | components["schemas"]["CameraCaptureNode"] | components["schemas"]["FunctionCallNode"] | components["schemas"]["OnFunctionCallNode"] | components["schemas"]["DelayNode"] | components["schemas"]["TickerNode"] | components["schemas"]["AlarmNode"] | components["schemas"]["WebSearchToolNode"] | components["schemas"]["OnStartupNode"] | components["schemas"]["OnPinEdgeNode"] | components["schemas"]["OnSerialReceiveNode"] | components["schemas"]["OnThresholdNode"] | components["schemas"]["SetVariableNode"] | components["schemas"]["MqttPublishNode"] | components["schemas"]["OnMqttMessageNode"];
        /** @enum {string} */
        EdgeType: "control" | "tool" | "agentTask" | "agentChoice" | "agentDelegate";
        Vertex: {
            nodeId: string;
            port: string;
        };
        Edge: {
            id: string;
            type: components["schemas"]["EdgeType"];
            from: components["schemas"]["Vertex"];
            to: components["schemas"]["Vertex"];
            /** @description Prompt expression sent to the agent. Present on `agentTask` (required) and `agentDelegate` (optional). */
            prompt?: components["schemas"]["Expression"];
            /** @description LLM-readable explanation of when the edge should fire. Present on `agentChoice` and `agentDelegate`. */
            description?: string;
        };
        /** @description A named, typed variable with a stable uid that can be referenced throughout the workflow. */
        Variable: {
            /** @description Stable identifier that survives renames */
            uid: string;
            name: string;
            dataType: components["schemas"]["DataType"];
            /** @description Initial value matching the dataType (number, boolean, or string). Only used by declared variables. */
            initialValue?: unknown;
        };
        FunctionInfo: {
            id: string;
            /** Format: int32 */
            version: number;
            name: string;
            arguments: components["schemas"]["Variable"][];
            returns: components["schemas"]["Variable"][];
        };
        Function: {
            functionInfo: components["schemas"]["FunctionInfo"];
            /** @description Maps return variable uid to its Expression */
            outputAssignments: {
                [key: string]: components["schemas"]["Expression"];
            };
            nodes: components["schemas"]["Node"][];
            edges: components["schemas"]["Edge"][];
            declaredVariables: components["schemas"]["Variable"][];
        };
        GPIOINChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "GPIOIN";
            id: string;
            label: string;
            /**
             * @description Pin bias configuration
             * @enum {string}
             */
            bias: "none" | "pullup" | "pulldown";
            /** @description Debounce window in milliseconds */
            debounceMs: number;
        };
        GPIOOUTChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "GPIOOUT";
            id: string;
            label: string;
        };
        ADCChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ADC";
            id: string;
            label: string;
        };
        PWMChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "PWM";
            id: string;
            label: string;
            /** @description PWM frequency in Hz */
            frequency: number;
        };
        DACChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DAC";
            id: string;
            label: string;
        };
        UARTChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "UART";
            id: string;
            label: string;
        };
        MQTTChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MQTT";
            id: string;
            label: string;
            /** @description Topic this channel publishes to / subscribes on. */
            topic: string;
        };
        CAMERAChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CAMERA";
            id: string;
            label: string;
        };
        LOGChannel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "LOG";
            id: string;
            label: string;
            /**
             * @description Severity for messages written to this channel.
             * @enum {string}
             */
            level: "debug" | "info" | "warn" | "error";
            /** @description Optional category label stamped on each line written to this channel. */
            tag?: string;
        };
        Channel: components["schemas"]["GPIOINChannel"] | components["schemas"]["GPIOOUTChannel"] | components["schemas"]["ADCChannel"] | components["schemas"]["PWMChannel"] | components["schemas"]["DACChannel"] | components["schemas"]["UARTChannel"] | components["schemas"]["MQTTChannel"] | components["schemas"]["CAMERAChannel"] | components["schemas"]["LOGChannel"];
        /** @description One .md file that agent nodes can read and write to. */
        MemoryFile: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MemoryFile";
            /** @description Stable identifier that survives renames; referenced from MemoryRef. */
            id: string;
            /** @description Display name. Unique per agent. */
            label: string;
            description: string;
            content: string;
            /** @description Byte cap; null means unlimited. */
            maxSizeBytes?: number | null;
        };
        /** @description A vector database for retrieval-augmented generation (RAG). */
        VectorDatabase: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "VectorDatabase";
            /** @description Stable identifier; referenced from Retriever nodes. */
            id: string;
            /** @description Display name. */
            label: string;
            description?: string;
        };
        Memory: components["schemas"]["MemoryFile"] | components["schemas"]["VectorDatabase"];
        /** @enum {string} */
        ModelCapability: "chat" | "embedding" | "function_call" | "vision" | "fine_tuning" | "reasoning" | "classification" | "code";
        /** @description A custom or self-hosted language model that agent nodes can reference. */
        LLMModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "LLMModel";
            /** @description Stable identifier; this is the ModelID nodes reference. */
            id: string;
            /** @description Display name. */
            label: string;
            /** @description Capabilities this model supports. */
            capabilities: components["schemas"]["ModelCapability"][];
        };
        /** @description A machine-learning model, served by an inference component, that nodes can reference. */
        MLModel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MLModel";
            /** @description Stable identifier; this is the model name nodes reference and the component selects on. */
            id: string;
            /** @description Display name. */
            label: string;
        };
        Model: components["schemas"]["LLMModel"] | components["schemas"]["MLModel"];
        /** @description The deployment format of a workflow project. */
        Workflow: {
            /**
             * Format: int32
             * @description Monotonic version of the persisted workflow format, bumped when the serialized shape changes.
             */
            schemaVersion: number;
            nodes: components["schemas"]["Node"][];
            edges: components["schemas"]["Edge"][];
            functions: components["schemas"]["Function"][];
            declaredVariables: components["schemas"]["Variable"][];
            channels: components["schemas"]["Channel"][];
            memory: components["schemas"]["Memory"][];
            /** @description Declared custom/self-hosted models; referenced from nodes by id. Static catalog models need no declaration. */
            models: components["schemas"]["Model"][];
        };
        /** @description Leading frames to discard so a sensor's auto-exposure can settle before the returned one. Default 0. */
        CameraWarmupFrames: number;
        /** @description Shell commands (media-ctl/v4l2-ctl) the driver component replays on every start, for statically configured capture pipelines. Operator-trusted by design. */
        CameraSetup: string[];
        /** @description A camera reached through a V4L2 device node — a USB/UVC webcam, or a CSI/ISP sensor whose media graph `setup` configures into a streaming node. The access path, not the sensor's form factor, is what picks this kind: a CSI sensor is v4l2 on boards that expose one and libcamera on boards that don't. */
        V4L2Source: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "v4l2";
            /** @description V4L2 device node, e.g. "/dev/video0". */
            device: string;
            warmupFrames?: components["schemas"]["CameraWarmupFrames"];
            setup?: components["schemas"]["CameraSetup"];
        };
        /** @description A camera reached through the platform's libcamera stack, which owns the media graph itself rather than exposing a preconfigured V4L2 node. */
        LibcameraSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "libcamera";
            /** @description Selects one sensor when the platform exposes several; the platform default is used when omitted. */
            cameraName?: string;
            warmupFrames?: components["schemas"]["CameraWarmupFrames"];
            setup?: components["schemas"]["CameraSetup"];
        };
        /** @description An IP camera served over RTSP. The password, when the stream needs one, is read from secrets.json under this camera's manifest key. */
        RtspSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rtsp";
            /** @description Stream URL, e.g. "rtsp://cam.local:554/stream1". Carries no credentials. */
            url: string;
            /** @description Username for streams that authenticate. Not a secret; the password is. */
            user?: string;
            warmupFrames?: components["schemas"]["CameraWarmupFrames"];
        };
        /** @description A camera served over HTTP (MJPEG stream or still endpoint). The password, when the endpoint needs one, is read from secrets.json under this camera's manifest key. */
        HttpSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "http";
            /** @description Stream or snapshot URL, e.g. "http://cam.local/video.mjpg". Carries no credentials. */
            url: string;
            /** @description Username for endpoints that authenticate. Not a secret; the password is. */
            user?: string;
            warmupFrames?: components["schemas"]["CameraWarmupFrames"];
        };
        /** @description Escape hatch for hardware no other kind describes: a capture-source fragment the driver component uses verbatim, in its own pipeline vocabulary. Operator-trusted by design, and the one kind that couples the manifest to a specific driver implementation — prefer a typed kind whenever one fits. */
        RawSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "raw";
            /** @description Capture-source fragment, passed to the driver component as-is and interpreted by it. */
            pipeline: string;
            warmupFrames?: components["schemas"]["CameraWarmupFrames"];
            setup?: components["schemas"]["CameraSetup"];
        };
        /** @description A synthetic camera that needs no hardware and returns a fixed frame. For hostless development and CI. */
        DebugSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "debug";
        };
        /** @description One camera the device owns, addressed by its manifest key. Device-owned hardware like a gpiochip or a serial port, not an environment-supplied endpoint: the engine reaches it through a driver component it issues privately, so no url is configured here. Declares intent (which camera, reached how), never a capture recipe — the driver component owns the pipeline for each kind. Secret-free: a kind with credentials reads them from secrets.json under this camera's manifest key. */
        CameraSource: components["schemas"]["V4L2Source"] | components["schemas"]["LibcameraSource"] | components["schemas"]["RtspSource"] | components["schemas"]["HttpSource"] | components["schemas"]["RawSource"] | components["schemas"]["DebugSource"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
