/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the loaded models.
         * @description Every model the repository loaded at startup — the names valid as the `model` in an inference path, each with its handler, task, and optional version.
         */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Describe one loaded model.
         * @description Metadata for the path-named model — its handler, task, and optional version. The task advertises the result shape an inference will return, so a caller can check it without running one.
         */
        get: operations["modelMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model}/infer/binary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run inference from an opaque encoded input (e.g. an image).
         * @description Feeds the raw request body to the path-named model as an opaque encoded artifact — an image or any blob the model's handler decodes itself. The body is the artifact and nothing else: the model is in the path, so no envelope and no per-request options. An unknown model yields 404; a body the handler cannot decode yields 422; a body over the size limit yields 413.
         */
        post: operations["inferBinary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model}/infer/tensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run inference from named numeric tensors.
         * @description Feeds already-numeric named tensors to the path-named model — for models whose input the caller prepares directly, with no decoding on the component side. An unknown model yields 404; tensors the handler cannot use yield 422.
         */
        post: operations["inferTensors"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness — the process is up.
         * @description Always 200 while the process is alive. Says nothing about whether models are loaded; use /readyz for that.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness — the model repository finished loading.
         * @description 200 only once the repository is loaded and inference can be served; 503 while the repository is still loading or empty.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The ML component's boot config: the models this component is issued. Authoritative — the component loads exactly these bundles from its workspace repository, so a declared bundle that is missing or unloadable is a permanent boot failure and an undeclared sub-folder is ignored. A projection of the deployment's device-located ML models, not an authored artifact: the renderer writes it, the component reads it at boot from the contracted config path. A cross-language seam. Not on the HTTP wire; carried here so the renderer (producer) and component (consumer) share one generated shape. Says WHICH models load and what the deployment overrides — never how a model is driven, which stays in the bundle's own manifest.yaml beside the weights. */
        MLConfig: {
            /** @description Models to load, keyed by model id — the bundle sub-folder name in the workspace repository, and the `model` in an inference path. */
            models: {
                [key: string]: components["schemas"]["MLModelConfig"];
            };
        };
        /** @description Deployment-level settings for one issued model. The bundle itself — weights, handler binding, default params — is staged in the workspace and self-described by its manifest.yaml; only what the deployment decides appears here. Empty is valid and usual: it declares the model must load, nothing more. */
        MLModelConfig: {
            /** @description Deployment overrides merged over the bundle manifest's params. Precedence, lowest to highest: manifest params, these, then a request's params. */
            params?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description What a model does, and therefore the shape of its result. The unit of normalization across implementations: two object-detection models return the same shape whatever their architecture. `tensor` is the general escape — raw model outputs, for a model whose task this contract does not model.
         * @enum {string}
         */
        Task: "object-detection" | "image-classification" | "tensor";
        /** @description One typed tensor in the KServe/OIP v2 representation: an explicit `datatype` and `shape` over a flat, row-major `data` array. Self-describing — a consumer reconstructs the array with no out-of-band shape knowledge — and used for both raw model inputs and raw model outputs. */
        Tensor: {
            /**
             * @description Element type, in KServe/OIP spelling (FP32, INT64, UINT8, BOOL, BYTES, ...).
             * @enum {string}
             */
            datatype: "BOOL" | "UINT8" | "UINT16" | "UINT32" | "UINT64" | "INT8" | "INT16" | "INT32" | "INT64" | "FP16" | "FP32" | "FP64" | "BYTES";
            /** @description Tensor dimensions, outermost first. */
            shape: number[];
            /** @description Elements flattened row-major (C order); length equals the product of `shape`. Numbers for the numeric datatypes. */
            data: unknown[];
        };
        /** @description Named input tensors keyed by the model's input feed names — one `Tensor` per model input. Already-numeric input the caller prepared, mapped straight onto the ONNX inputs with no decoding on the component side. */
        TensorInput: {
            [key: string]: components["schemas"]["Tensor"];
        };
        /** @description A task-shaped inference result. Discriminated by `task`, which always equals the producing model's advertised task, so a consumer can decode without knowing the model. */
        InferResult: components["schemas"]["DetectionResult"] | components["schemas"]["ClassificationResult"] | components["schemas"]["TensorResult"];
        /** @description Objects located in the input image. Already filtered and de-duplicated by the model's decoder — a consumer renders or counts these, it does not post-process them further. */
        DetectionResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            task: "object-detection";
            /** @description The surviving detections, ordered by descending score. */
            detections: components["schemas"]["Detection"][];
        };
        /** @description One located object. */
        Detection: {
            /** @description Human-readable class name, resolved through the model's label map. */
            label: string;
            /** @description Confidence in [0, 1]. */
            score: number;
            /** @description Raw class index the model emitted, before label resolution. Absent when the decoder has no meaningful index. */
            classId?: number;
            box: components["schemas"]["Box"];
        };
        /** @description An axis-aligned box in ORIGINAL input-image pixel coordinates — the decoder projects out of whatever letterboxed or rescaled space the model worked in, so a consumer never needs the preprocessing geometry. */
        Box: {
            xmin: number;
            ymin: number;
            xmax: number;
            ymax: number;
        };
        /** @description What the input image depicts, as ranked candidate classes. */
        ClassificationResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            task: "image-classification";
            /** @description Candidate classes, ordered by descending score. */
            predictions: components["schemas"]["Classification"][];
        };
        /** @description One candidate class for the whole input. */
        Classification: {
            /** @description Human-readable class name, resolved through the model's label map. */
            label: string;
            /** @description Confidence in [0, 1]. */
            score: number;
            /** @description Raw class index the model emitted, before label resolution. */
            classId?: number;
        };
        /** @description Raw model outputs, undecoded. The general escape for a model whose task this contract does not model — the caller owns interpreting these. */
        TensorResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            task: "tensor";
            /** @description Output tensors keyed by the model's output names, one `Tensor` each. */
            tensors: {
                [key: string]: components["schemas"]["Tensor"];
            };
        };
        /** @description The set of models the component currently has loaded. */
        RepositoryMetadata: {
            /** @description Every model loaded into the repository. */
            models: components["schemas"]["ModelMetadata"][];
        };
        /** @description Descriptive metadata for one loaded model. */
        ModelMetadata: {
            /** @description Name (id) of the model — the value to use as the `model` in an inference path. */
            name: string;
            /** @description Handler driving the model: `builtin:<name>` or `file:handler.py`. */
            handler: string;
            task: components["schemas"]["Task"];
            /** @description Optional model/bundle version string. */
            modelVersion?: string;
        };
        /** @description A simple health-probe response. */
        Health: {
            /** @description Probe status (e.g. ok, loading). */
            status: string;
        };
        /** @description A structured error response. */
        Error: {
            /** @description Human-readable error description. */
            message: string;
        };
    };
    responses: {
        /** @description Inference result. */
        Inference: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["InferResult"];
            };
        };
        /** @description No model with the requested name is loaded. */
        UnknownModel: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request body exceeds the component's size limit. */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The input could not be processed by the selected model's handler. */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The handler failed unexpectedly while running inference. */
        HandlerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Name (id) of the loaded model — a loaded bundle (a sub-folder of the models repository). See GET /models for valid names. */
        Model: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The repository's loaded models. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryMetadata"];
                };
            };
        };
    };
    modelMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Name (id) of the loaded model — a loaded bundle (a sub-folder of the models repository). See GET /models for valid names. */
                model: components["parameters"]["Model"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The model's metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelMetadata"];
                };
            };
            404: components["responses"]["UnknownModel"];
        };
    };
    inferBinary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Name (id) of the loaded model — a loaded bundle (a sub-folder of the models repository). See GET /models for valid names. */
                model: components["parameters"]["Model"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            200: components["responses"]["Inference"];
            404: components["responses"]["UnknownModel"];
            413: components["responses"]["TooLarge"];
            422: components["responses"]["Unprocessable"];
            500: components["responses"]["HandlerError"];
        };
    };
    inferTensors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Name (id) of the loaded model — a loaded bundle (a sub-folder of the models repository). See GET /models for valid names. */
                model: components["parameters"]["Model"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TensorInput"];
            };
        };
        responses: {
            200: components["responses"]["Inference"];
            404: components["responses"]["UnknownModel"];
            422: components["responses"]["Unprocessable"];
            500: components["responses"]["HandlerError"];
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The repository is loaded and inference can be served. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The repository is not yet loaded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
