/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/infer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run inference on one loaded model, selected by name.
         * @description Selects the loaded model named by `model`, feeds it the supplied input, and returns the handler-produced result. The handler decides how to read the input (binary blob, numeric tensors, or both). An unknown `model` yields 404; an input the handler cannot process yields 422.
         */
        post: operations["infer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness — the process is up.
         * @description Always 200 while the process is alive. Says nothing about whether models are loaded; use /readyz for that.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness — the model repository finished loading.
         * @description 200 only once the repository is loaded and inference can be served; 503 while the repository is still loading or empty.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the loaded models.
         * @description Describes every model the repository loaded at startup — the names valid as the /infer `model` selector, plus each one's handler and optional version.
         */
        get: operations["metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The ML component's boot config: the models this component is issued. Authoritative — the component loads exactly these bundles from its workspace repository, so a declared bundle that is missing or unloadable is a permanent boot failure and an undeclared sub-folder is ignored. A projection of the deployment's device-located ML models, not an authored artifact: the renderer writes it, the component reads it at boot from the contracted config path. A cross-language seam. Not on the HTTP wire; carried here so the renderer (producer) and component (consumer) share one generated shape. Says WHICH models load and what the deployment overrides — never how a model is driven, which stays in the bundle's own manifest.yaml beside the weights. */
        MLConfig: {
            /** @description Models to load, keyed by model id — the bundle sub-folder name in the workspace repository, and the /infer `model` selector. */
            models: {
                [key: string]: components["schemas"]["MLModelConfig"];
            };
        };
        /** @description Deployment-level settings for one issued model. The bundle itself — weights, handler binding, default params — is staged in the workspace and self-described by its manifest.yaml; only what the deployment decides appears here. Empty is valid and usual: it declares the model must load, nothing more. */
        MLModelConfig: {
            /** @description Deployment overrides merged over the bundle manifest's params. Precedence, lowest to highest: manifest params, these, then a request's params. */
            params?: {
                [key: string]: unknown;
            };
        };
        /** @description A generic inference request. `model` picks which loaded model runs. `binary` carries an opaque binary input (e.g. an encoded image); `tensors` carries named numeric tensors (nested arrays) for non-vision models. Supply whichever the selected model's handler expects — one, the other, or both. */
        InferRequest: {
            /** @description Name (id) of the loaded model to run — must match a loaded bundle (a sub-folder of the models repository). See /metadata for valid names. */
            model: string;
            /**
             * Format: binary
             * @description Opaque binary input (e.g. an encoded image). Read and decoded by the model's handler.
             */
            binary?: string;
            /** @description Named numeric tensors as nested arrays, for models whose input is not a binary blob. The handler maps these onto the model's input feeds. */
            tensors?: {
                [key: string]: unknown;
            };
            /** @description Free-form per-request overrides (e.g. detection thresholds). Merged over the manifest's params by the handler. */
            params?: {
                [key: string]: unknown;
            };
        };
        /** @description A generic inference result. `result` is task-shaped: the model's task decides which variant comes back, so a consumer that knows the task knows the shape. */
        InferResult: {
            /** @description Name of the model that produced this result. */
            model: string;
            result: components["schemas"]["InferenceResult"];
        };
        /**
         * @description What a model does, and therefore the shape of its result. The unit of normalization across implementations: two object-detection models return the same shape whatever their architecture. `tensor` is the general escape — raw model outputs, for a model whose task this contract does not model.
         * @enum {string}
         */
        Task: "object-detection" | "image-classification" | "tensor";
        /** @description A task-shaped inference result. Discriminated by `task`, which always equals the producing model's advertised task, so a consumer can decode without knowing the model. */
        InferenceResult: components["schemas"]["DetectionResult"] | components["schemas"]["ClassificationResult"] | components["schemas"]["TensorResult"];
        /** @description Objects located in the input image. Already filtered and de-duplicated by the model's decoder — a consumer renders or counts these, it does not post-process them further. */
        DetectionResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            task: "object-detection";
            /** @description The surviving detections, ordered by descending score. */
            detections: components["schemas"]["Detection"][];
        };
        /** @description One located object. */
        Detection: {
            /** @description Human-readable class name, resolved through the model's label map. */
            label: string;
            /** @description Confidence in [0, 1]. */
            score: number;
            /** @description Raw class index the model emitted, before label resolution. Absent when the decoder has no meaningful index. */
            classId?: number;
            box: components["schemas"]["Box"];
        };
        /** @description An axis-aligned box in ORIGINAL input-image pixel coordinates — the decoder projects out of whatever letterboxed or rescaled space the model worked in, so a consumer never needs the preprocessing geometry. */
        Box: {
            xmin: number;
            ymin: number;
            xmax: number;
            ymax: number;
        };
        /** @description What the input image depicts, as ranked candidate classes. */
        ClassificationResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            task: "image-classification";
            /** @description Candidate classes, ordered by descending score. */
            predictions: components["schemas"]["Classification"][];
        };
        /** @description One candidate class for the whole input. */
        Classification: {
            /** @description Human-readable class name, resolved through the model's label map. */
            label: string;
            /** @description Confidence in [0, 1]. */
            score: number;
            /** @description Raw class index the model emitted, before label resolution. */
            classId?: number;
        };
        /** @description Raw model outputs, undecoded. The general escape for a model whose task this contract does not model — the caller owns interpreting these. */
        TensorResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            task: "tensor";
            /** @description Output tensors as nested arrays, keyed by the model's output names. */
            tensors: {
                [key: string]: unknown;
            };
        };
        /** @description The set of models the component currently has loaded. */
        RepositoryMetadata: {
            /** @description Every model loaded into the repository. */
            models: components["schemas"]["ModelMetadata"][];
        };
        /** @description Descriptive metadata for one loaded model. */
        ModelMetadata: {
            /** @description Name (id) of the model — the value to pass as the /infer `model` selector. */
            name: string;
            /** @description Handler driving the model: `builtin:<name>` or `file:handler.py`. */
            handler: string;
            task: components["schemas"]["Task"];
            /** @description Optional model/bundle version string. */
            modelVersion?: string;
        };
        /** @description A simple health-probe response. */
        Health: {
            /** @description Probe status (e.g. ok, loading). */
            status: string;
        };
        /** @description A structured error response. */
        Error: {
            /** @description Human-readable error description. */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    infer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["InferRequest"];
            };
        };
        responses: {
            /** @description Inference result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferResult"];
                };
            };
            /** @description No model with the requested name is loaded. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The request body exceeds the component's size limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The input could not be processed by the selected model's handler. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The handler failed unexpectedly while running inference. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The repository is loaded and inference can be served. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The repository is not yet loaded. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    metadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The repository's loaded models. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryMetadata"];
                };
            };
        };
    };
}
