// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 ForestHub. All rights reserved.
// For commercial licensing, contact root@foresthub.ai

package llmproxy

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/ForestHubAI/edge-agents/go/llmproxy/schemautil"
)

// NoArgs is an empty struct type used as type for function tools that take no arguments.
type NoArgs struct{}

// Tool represents a capability that can be used by a model.
// Tools may be executed internally by model providers or externally by the caller.
// This interface is sealed and must not be implemented outside the llmproxy package.
// Callers may only supply tools via the ExternalTool abstraction.
type Tool interface {
	// ToolName returns the name of the tool.
	ToolName() string

	// isTool seals the interface.
	isTool()
}

// ToolCallRequest represents a request made by the model to call an external tool as next step.
type ToolCallRequest struct {
	// The unique ID of the function tool call request generated by the model.
	CallID string `json:"callId"`

	// Name of the external tool called.
	Name string `json:"name"`

	// Arguments that should be passed to the external tool.
	Arguments json.RawMessage `json:"arguments"`
}

func (ToolCallRequest) isInputItem() {}
func (r ToolCallRequest) String() string {
	return fmt.Sprintf("Function tool call: %s with arguments %s", r.Name, string(r.Arguments))
}

// ToolResult represents the result returned by executing an external tool.
type ToolResult struct {
	// The unique ID of the function tool call request generated by the model.
	CallID string `json:"callId"`

	// Name of the external tool called.
	Name string `json:"name"`

	// Output of the external tool.
	Output any `json:"output"`
}

func (ToolResult) isInputItem() {}
func (r ToolResult) String() string {
	if stringer, ok := r.Output.(fmt.Stringer); ok {
		return fmt.Sprintf("Function %s returned: %s", r.Name, stringer.String())
	}
	return fmt.Sprintf("Function %s returned: %v", r.Name, r.Output)
}

// ========== External Tools ========== //

// ExternalTool is a tool whose execution is handled outside of the LLM provider.
// Calls and results are exchanged between the caller and the model as part of the request flow.
type ExternalTool interface {
	Tool
	ToolDescription() string
	ToolParams() map[string]any
}

// ExternalToolBase is the canonical implementation of ExternalTool.
// Users can provide their own external tool implementations via
// embedding this struct, while Tool remains sealed.
type ExternalToolBase struct {
	Name        string         `json:"name"`
	Description string         `json:"description,omitempty"`
	Parameters  map[string]any `json:"parameters"`
}

func (t ExternalToolBase) ToolName() string           { return t.Name }
func (t ExternalToolBase) ToolDescription() string    { return t.Description }
func (t ExternalToolBase) ToolParams() map[string]any { return t.Parameters }
func (ExternalToolBase) isTool()                      {}

// FunctionTool is an external tool that has a callable function handle
// that can be invoked with arguements parsed from JSON.
type FunctionTool struct {
	ExternalToolBase

	// ToolCall calls the tool function with given context and parameters.
	ToolCall func(ctx context.Context, arguments json.RawMessage) (any, error) `json:"-"`
}

// NewFunctionTool constructs a FunctionTool from typed parameters and a handler function.
func NewFunctionTool[T any, R any](name, description string, handler func(ctx context.Context, args T) (R, error)) (FunctionTool, error) {
	schema, err := schemautil.ToStrictJSONSchema[T]()
	if err != nil {
		return FunctionTool{}, fmt.Errorf("failed to generate JSON schema for input type %T: %w", *new(T), err)
	}

	return FunctionTool{
		ExternalToolBase: ExternalToolBase{
			Name:        name,
			Description: description,
			Parameters:  schema,
		},
		ToolCall: func(ctx context.Context, arguments json.RawMessage) (any, error) {
			var args T
			if err := json.Unmarshal([]byte(arguments), &args); err != nil {
				return nil, fmt.Errorf("failed to parse arguments: %w", err)
			}
			return handler(ctx, args)
		},
	}, nil
}

// ========== Internal Tools ========== //

// WebSearch is a marker tool requesting native web search on the provider side.
// Carries no fields: per-provider parameters (allowed domains, max uses, etc.)
// live on each provider's Config. Whether the marker actually triggers a native
// search is decided in each provider's mapping based on its config.
type WebSearch struct{}

func (WebSearch) ToolName() string { return "web_search" }
func (WebSearch) isTool()          {}
