// Package mlapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package mlapi

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ClassificationResultTask.
const (
	ClassificationResultTaskImageClassification ClassificationResultTask = "image-classification"
)

// Valid indicates whether the value is a known member of the ClassificationResultTask enum.
func (e ClassificationResultTask) Valid() bool {
	switch e {
	case ClassificationResultTaskImageClassification:
		return true
	default:
		return false
	}
}

// Defines values for DetectionResultTask.
const (
	ObjectDetection DetectionResultTask = "object-detection"
)

// Valid indicates whether the value is a known member of the DetectionResultTask enum.
func (e DetectionResultTask) Valid() bool {
	switch e {
	case ObjectDetection:
		return true
	default:
		return false
	}
}

// Defines values for Task.
const (
	TaskImageClassification Task = "image-classification"
	TaskObjectDetection     Task = "object-detection"
	TaskTensor              Task = "tensor"
)

// Valid indicates whether the value is a known member of the Task enum.
func (e Task) Valid() bool {
	switch e {
	case TaskImageClassification:
		return true
	case TaskObjectDetection:
		return true
	case TaskTensor:
		return true
	default:
		return false
	}
}

// Defines values for TensorResultTask.
const (
	Tensor TensorResultTask = "tensor"
)

// Valid indicates whether the value is a known member of the TensorResultTask enum.
func (e TensorResultTask) Valid() bool {
	switch e {
	case Tensor:
		return true
	default:
		return false
	}
}

// Box An axis-aligned box in ORIGINAL input-image pixel coordinates — the decoder projects out of whatever letterboxed or rescaled space the model worked in, so a consumer never needs the preprocessing geometry.
type Box struct {
	Xmax float32 `json:"xmax"`
	Xmin float32 `json:"xmin"`
	Ymax float32 `json:"ymax"`
	Ymin float32 `json:"ymin"`
}

// Classification One candidate class for the whole input.
type Classification struct {
	// ClassId Raw class index the model emitted, before label resolution.
	ClassId int `json:"classId,omitempty"`

	// Label Human-readable class name, resolved through the model's label map.
	Label string `json:"label"`

	// Score Confidence in [0, 1].
	Score float32 `json:"score"`
}

// ClassificationResult What the input image depicts, as ranked candidate classes.
type ClassificationResult struct {
	// Predictions Candidate classes, ordered by descending score.
	Predictions []Classification         `json:"predictions"`
	Task        ClassificationResultTask `json:"task"`
}

// ClassificationResultTask defines model for ClassificationResult.Task.
type ClassificationResultTask string

// Detection One located object.
type Detection struct {
	// Box An axis-aligned box in ORIGINAL input-image pixel coordinates — the decoder projects out of whatever letterboxed or rescaled space the model worked in, so a consumer never needs the preprocessing geometry.
	Box Box `json:"box"`

	// ClassId Raw class index the model emitted, before label resolution. Absent when the decoder has no meaningful index.
	ClassId int `json:"classId,omitempty"`

	// Label Human-readable class name, resolved through the model's label map.
	Label string `json:"label"`

	// Score Confidence in [0, 1].
	Score float32 `json:"score"`
}

// DetectionResult Objects located in the input image. Already filtered and de-duplicated by the model's decoder — a consumer renders or counts these, it does not post-process them further.
type DetectionResult struct {
	// Detections The surviving detections, ordered by descending score.
	Detections []Detection         `json:"detections"`
	Task       DetectionResultTask `json:"task"`
}

// DetectionResultTask defines model for DetectionResult.Task.
type DetectionResultTask string

// Error A structured error response.
type Error struct {
	// Message Human-readable error description.
	Message string `json:"message"`
}

// Health A simple health-probe response.
type Health struct {
	// Status Probe status (e.g. ok, loading).
	Status string `json:"status"`
}

// InferRequest A generic inference request. `model` picks which loaded model runs. `binary` carries an opaque binary input (e.g. an encoded image); `tensors` carries named numeric tensors (nested arrays) for non-vision models. Supply whichever the selected model's handler expects — one, the other, or both.
type InferRequest struct {
	// Binary Opaque binary input (e.g. an encoded image). Read and decoded by the model's handler.
	Binary *openapi_types.File `json:"binary,omitempty"`

	// Model Name (id) of the loaded model to run — must match a loaded bundle (a sub-folder of the models repository). See /metadata for valid names.
	Model string `json:"model"`

	// Params Free-form per-request overrides (e.g. detection thresholds). Merged over the manifest's params by the handler.
	Params map[string]interface{} `json:"params,omitempty"`

	// Tensors Named numeric tensors as nested arrays, for models whose input is not a binary blob. The handler maps these onto the model's input feeds.
	Tensors map[string]interface{} `json:"tensors,omitempty"`
}

// InferResult A generic inference result. `result` is task-shaped: the model's task decides which variant comes back, so a consumer that knows the task knows the shape.
type InferResult struct {
	// Model Name of the model that produced this result.
	Model string `json:"model"`

	// Result A task-shaped inference result. Discriminated by `task`, which always equals the producing model's advertised task, so a consumer can decode without knowing the model.
	Result InferenceResult `json:"result"`
}

// InferenceResult A task-shaped inference result. Discriminated by `task`, which always equals the producing model's advertised task, so a consumer can decode without knowing the model.
type InferenceResult struct {
	union json.RawMessage
}

// MLConfig The ML component's boot config: the models this component is issued. Authoritative — the component loads exactly these bundles from its workspace repository, so a declared bundle that is missing or unloadable is a permanent boot failure and an undeclared sub-folder is ignored. A projection of the deployment's device-located ML models, not an authored artifact: the renderer writes it, the component reads it at boot from the contracted config path. A cross-language seam. Not on the HTTP wire; carried here so the renderer (producer) and component (consumer) share one generated shape. Says WHICH models load and what the deployment overrides — never how a model is driven, which stays in the bundle's own manifest.yaml beside the weights.
type MLConfig struct {
	// Models Models to load, keyed by model id — the bundle sub-folder name in the workspace repository, and the /infer `model` selector.
	Models map[string]MLModelConfig `json:"models"`
}

// MLModelConfig Deployment-level settings for one issued model. The bundle itself — weights, handler binding, default params — is staged in the workspace and self-described by its manifest.yaml; only what the deployment decides appears here. Empty is valid and usual: it declares the model must load, nothing more.
type MLModelConfig struct {
	// Params Deployment overrides merged over the bundle manifest's params. Precedence, lowest to highest: manifest params, these, then a request's params.
	Params map[string]interface{} `json:"params,omitempty"`
}

// ModelMetadata Descriptive metadata for one loaded model.
type ModelMetadata struct {
	// Handler Handler driving the model: `builtin:<name>` or `file:handler.py`.
	Handler string `json:"handler"`

	// ModelVersion Optional model/bundle version string.
	ModelVersion string `json:"modelVersion,omitempty"`

	// Name Name (id) of the model — the value to pass as the /infer `model` selector.
	Name string `json:"name"`

	// Task What a model does, and therefore the shape of its result. The unit of normalization across implementations: two object-detection models return the same shape whatever their architecture. `tensor` is the general escape — raw model outputs, for a model whose task this contract does not model.
	Task Task `json:"task"`
}

// RepositoryMetadata The set of models the component currently has loaded.
type RepositoryMetadata struct {
	// Models Every model loaded into the repository.
	Models []ModelMetadata `json:"models"`
}

// Task What a model does, and therefore the shape of its result. The unit of normalization across implementations: two object-detection models return the same shape whatever their architecture. `tensor` is the general escape — raw model outputs, for a model whose task this contract does not model.
type Task string

// TensorResult Raw model outputs, undecoded. The general escape for a model whose task this contract does not model — the caller owns interpreting these.
type TensorResult struct {
	Task TensorResultTask `json:"task"`

	// Tensors Output tensors as nested arrays, keyed by the model's output names.
	Tensors map[string]interface{} `json:"tensors"`
}

// TensorResultTask defines model for TensorResult.Task.
type TensorResultTask string

// InferMultipartRequestBody defines body for Infer for multipart/form-data ContentType.
type InferMultipartRequestBody = InferRequest

// AsDetectionResult returns the union data inside the InferenceResult as a DetectionResult
func (t InferenceResult) AsDetectionResult() (DetectionResult, error) {
	var body DetectionResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDetectionResult overwrites any union data inside the InferenceResult as the provided DetectionResult
func (t *InferenceResult) FromDetectionResult(v DetectionResult) error {
	v.Task = "object-detection"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDetectionResult performs a merge with any union data inside the InferenceResult, using the provided DetectionResult
func (t *InferenceResult) MergeDetectionResult(v DetectionResult) error {
	v.Task = "object-detection"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsClassificationResult returns the union data inside the InferenceResult as a ClassificationResult
func (t InferenceResult) AsClassificationResult() (ClassificationResult, error) {
	var body ClassificationResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromClassificationResult overwrites any union data inside the InferenceResult as the provided ClassificationResult
func (t *InferenceResult) FromClassificationResult(v ClassificationResult) error {
	v.Task = "image-classification"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeClassificationResult performs a merge with any union data inside the InferenceResult, using the provided ClassificationResult
func (t *InferenceResult) MergeClassificationResult(v ClassificationResult) error {
	v.Task = "image-classification"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTensorResult returns the union data inside the InferenceResult as a TensorResult
func (t InferenceResult) AsTensorResult() (TensorResult, error) {
	var body TensorResult
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTensorResult overwrites any union data inside the InferenceResult as the provided TensorResult
func (t *InferenceResult) FromTensorResult(v TensorResult) error {
	v.Task = "tensor"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTensorResult performs a merge with any union data inside the InferenceResult, using the provided TensorResult
func (t *InferenceResult) MergeTensorResult(v TensorResult) error {
	v.Task = "tensor"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t InferenceResult) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"task"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t InferenceResult) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "image-classification":
		return t.AsClassificationResult()
	case "object-detection":
		return t.AsDetectionResult()
	case "tensor":
		return t.AsTensorResult()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t InferenceResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *InferenceResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// Healthz request
	Healthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InferWithBody request with any body
	InferWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Metadata request
	Metadata(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Readyz request
	Readyz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) Healthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InferWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInferRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Metadata(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMetadataRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Readyz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReadyzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewHealthzRequest generates requests for Healthz
func NewHealthzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewInferRequestWithBody generates requests for Infer with any type of body
func NewInferRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/infer")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewMetadataRequest generates requests for Metadata
func NewMetadataRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/metadata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReadyzRequest generates requests for Readyz
func NewReadyzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/readyz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// HealthzWithResponse request
	HealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzResponse, error)

	// InferWithBodyWithResponse request with any body
	InferWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InferResponse, error)

	// MetadataWithResponse request
	MetadataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*MetadataResponse, error)

	// ReadyzWithResponse request
	ReadyzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReadyzResponse, error)
}

type HealthzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Health
}

// Status returns HTTPResponse.Status
func (r HealthzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type InferResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *InferResult
	JSON404      *Error
	JSON413      *Error
	JSON422      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r InferResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InferResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r InferResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type MetadataResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RepositoryMetadata
}

// Status returns HTTPResponse.Status
func (r MetadataResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MetadataResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MetadataResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReadyzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Health
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r ReadyzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReadyzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReadyzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// HealthzWithResponse request returning *HealthzResponse
func (c *ClientWithResponses) HealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzResponse, error) {
	rsp, err := c.Healthz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthzResponse(rsp)
}

// InferWithBodyWithResponse request with arbitrary body returning *InferResponse
func (c *ClientWithResponses) InferWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InferResponse, error) {
	rsp, err := c.InferWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInferResponse(rsp)
}

// MetadataWithResponse request returning *MetadataResponse
func (c *ClientWithResponses) MetadataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*MetadataResponse, error) {
	rsp, err := c.Metadata(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMetadataResponse(rsp)
}

// ReadyzWithResponse request returning *ReadyzResponse
func (c *ClientWithResponses) ReadyzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReadyzResponse, error) {
	rsp, err := c.Readyz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReadyzResponse(rsp)
}

// ParseHealthzResponse parses an HTTP response from a HealthzWithResponse call
func ParseHealthzResponse(rsp *http.Response) (*HealthzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseInferResponse parses an HTTP response from a InferWithResponse call
func ParseInferResponse(rsp *http.Response) (*InferResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InferResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InferResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseMetadataResponse parses an HTTP response from a MetadataWithResponse call
func ParseMetadataResponse(rsp *http.Response) (*MetadataResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MetadataResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RepositoryMetadata
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseReadyzResponse parses an HTTP response from a ReadyzWithResponse call
func ParseReadyzResponse(rsp *http.Response) (*ReadyzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReadyzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}
