// Package engineapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package engineapi

import (
	externalRef0 "github.com/ForestHubAI/edge-agents/go/api/cameraapi"
	externalRef1 "github.com/ForestHubAI/edge-agents/go/api/workflowapi"
)

// Defines values for LLMProviderType.
const (
	BackendLlm    LLMProviderType = "backendLlm"
	DirectLlm     LLMProviderType = "directLlm"
	SelfhostedLlm LLMProviderType = "selfhostedLlm"
)

// Valid indicates whether the value is a known member of the LLMProviderType enum.
func (e LLMProviderType) Valid() bool {
	switch e {
	case BackendLlm:
		return true
	case DirectLlm:
		return true
	case SelfhostedLlm:
		return true
	default:
		return false
	}
}

// ADCConfig An ADC device. Single-shape: the family is the map it sits in (Resources.adcs), so it carries no discriminator.
type ADCConfig struct {
	// Device sysfs path to the IIO device directory, e.g. "/sys/bus/iio/devices/iio:device0"
	Device string `json:"device"`
}

// DACConfig A DAC device. Single-shape: the family is the map it sits in (Resources.dacs), so it carries no discriminator.
type DACConfig struct {
	// Device sysfs path to the IIO device directory, e.g. "/sys/bus/iio/devices/iio:device1"
	Device string `json:"device"`
}

// EngineConfig The engine's complete boot input, loaded once at startup.
type EngineConfig struct {
	// Mapping Binds a binding-free workflow's logical resource ids to concrete platform resources, keyed by workflow resource id.
	Mapping *ResourceMapping `json:"mapping,omitempty"`

	// Resources The frozen set of platform resources the engine materializes 1:1 into live code at boot, keyed by resource id (`ref`) in the respective maps. Resource ids are opaque, deployment-scoped strings; they are never addresses and must be unique across families.
	Resources *Resources `json:"resources,omitempty"`

	// Workflow The deployment format of a workflow project.
	Workflow externalRef1.Workflow `json:"workflow"`
}

// GPIOConfig A GPIO chip. Single-shape: the family is the map it sits in (Resources.gpios), so it carries no discriminator.
type GPIOConfig struct {
	// Chip cdev chip name or path, e.g. "gpiochip0" or "/dev/gpiochip0"
	Chip string `json:"chip"`
}

// LLMProvider One LLM provider instance the engine registers into its single llmproxy; a workflow model reaches it by model id. directLlm: a built-in catalog adapter reached straight at the provider, authenticated with a deploy-delivered API key (secrets.json, keyed by this resource's ref); `provider` names the adapter. backendLlm: that same catalog adapter's models proxied to the backend, no key; `provider` names the adapter. selfhostedLlm: a direct endpoint the llmproxy doesn't ship (`url`; optional bearer via secrets.json by ref), shared by every model bound to it. Each catalog provider is served by exactly one instance (directLlm xor backendLlm) — no catch-all, no shadowing.
type LLMProvider struct {
	// Provider directLlm / backendLlm only — the built-in catalog adapter this instance serves (e.g. anthropic, openai).
	Provider *string         `json:"provider,omitempty"`
	Type     LLMProviderType `json:"type"`

	// Url selfhostedLlm only — base URL of the inference endpoint (http:// or https://).
	Url *string `json:"url,omitempty"`
}

// LLMProviderType defines model for LLMProvider.Type.
type LLMProviderType string

// MLProvider Resolved connection to an ML component the engine doesn't ship: a separate service (onnx, or an operator's own endpoint) reached by URL that loads a repository of models and serves them over HTTP. The engine names a model on each request; which one is the binding's `model` sub-address (ResourceAddress.model), so many models may share one endpoint. A trusted in-deployment endpoint — no credential. Single-shape: the family is the map it sits in (Resources.mlProviders), so it carries no discriminator.
type MLProvider struct {
	// Url Base URL of the ML component (http:// or https://).
	Url string `json:"url"`
}

// MQTTBroker Resolved connection metadata for an MQTT broker. Single-shape: the family is the map it sits in (Resources.mqttBrokers), so it carries no discriminator — a managed and a BYO broker resolve to the same shape.
type MQTTBroker struct {
	BrokerURL string  `json:"brokerUrl"`
	ClientID  *string `json:"clientId,omitempty"`

	// PublishPrefix Topic prefix the engine prepends to every workflow-level publish topic. Opaque to the engine and prepended verbatim; the deploy-time resolver owns the grammar.
	PublishPrefix *string `json:"publishPrefix,omitempty"`

	// SubscribePrefix Topic prefix the engine prepends to every workflow-level subscribe filter. Opaque to the engine and prepended verbatim; the deploy-time resolver owns the grammar.
	SubscribePrefix *string   `json:"subscribePrefix,omitempty"`
	Username        *string   `json:"username,omitempty"`
	Will            *MQTTWill `json:"will,omitempty"`
}

// MQTTWill defines model for MQTTWill.
type MQTTWill struct {
	Payload string `json:"payload"`

	// Qos MQTT QoS (0, 1, or 2).
	Qos    int    `json:"qos"`
	Retain bool   `json:"retain"`
	Topic  string `json:"topic"`
}

// PWMConfig A PWM chip. Single-shape: the family is the map it sits in (Resources.pwms), so it carries no discriminator.
type PWMConfig struct {
	// Chip sysfs path to the pwmchip directory, e.g. "/sys/class/pwm/pwmchip0"
	Chip string `json:"chip"`
}

// RagQueryRequest defines model for RagQueryRequest.
type RagQueryRequest struct {
	// CollectionID Collection to query
	CollectionID string `json:"collectionId"`

	// Query Search query text
	Query string `json:"query"`

	// TopK Number of results to return
	TopK *int `json:"topK,omitempty"`
}

// RagQueryResult defines model for RagQueryResult.
type RagQueryResult struct {
	ChunkID    string  `json:"chunkId"`
	Content    string  `json:"content"`
	DocumentID string  `json:"documentId"`
	Score      float64 `json:"score"`
}

// ResourceAddress Where one workflow resource resolves to: the shared platform resource `ref` it maps to, plus an optional sub-address selecting one served unit within it.
type ResourceAddress struct {
	// Index Per-channel physical sub-address within a driver (GPIO line / ADC-PWM-DAC channel). Driver resources only.
	Index *int `json:"index,omitempty"`

	// Model Model name a shared inference endpoint (self-hosted LLM / ML component) selects on for this binding. Required for endpoint bindings — the endpoint fronts several models and picks one by this name; omitted for driver/mqtt bindings.
	Model *string `json:"model,omitempty"`

	// Ref An opaque, deployment-scoped identity string in Resources this binds to. It is a key, never an address.
	Ref string `json:"ref"`
}

// ResourceMapping Binds a binding-free workflow's logical resource ids to concrete platform resources, keyed by workflow resource id.
type ResourceMapping map[string]ResourceAddress

// Resources The frozen set of platform resources the engine materializes 1:1 into live code at boot, keyed by resource id (`ref`) in the respective maps. Resource ids are opaque, deployment-scoped strings; they are never addresses and must be unique across families.
type Resources struct {
	Adcs         *map[string]ADCConfig                 `json:"adcs,omitempty"`
	Cameras      *map[string]externalRef0.CameraSource `json:"cameras,omitempty"`
	Dacs         *map[string]DACConfig                 `json:"dacs,omitempty"`
	Gpios        *map[string]GPIOConfig                `json:"gpios,omitempty"`
	LlmProviders *map[string]LLMProvider               `json:"llmProviders,omitempty"`
	MlProviders  *map[string]MLProvider                `json:"mlProviders,omitempty"`
	MqttBrokers  *map[string]MQTTBroker                `json:"mqttBrokers,omitempty"`
	Pwms         *map[string]PWMConfig                 `json:"pwms,omitempty"`
	Serials      *map[string]SerialConfig              `json:"serials,omitempty"`
}

// SerialConfig A serial port. Single-shape: the family is the map it sits in (Resources.serials), so it carries no discriminator.
type SerialConfig struct {
	// Baud Baud rate; falls back to 115200 when zero
	Baud *int `json:"baud,omitempty"`

	// Device Serial device path, e.g. "/dev/ttyUSB0" or "COM3"
	Device string `json:"device"`
}
