// Package engineapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package engineapi

import (
	"encoding/json"
	"errors"
	"fmt"
	"time"

	externalRef0 "github.com/ForestHubAI/edge-agents/go/api/workflow"
	"github.com/oapi-codegen/runtime"
)

// Defines values for LLMProviderConfigType.
const (
	Selfhosted LLMProviderConfigType = "selfhosted"
)

// Valid indicates whether the value is a known member of the LLMProviderConfigType enum.
func (e LLMProviderConfigType) Valid() bool {
	switch e {
	case Selfhosted:
		return true
	default:
		return false
	}
}

// Defines values for LogEntryLevel.
const (
	Debug LogEntryLevel = "debug"
	Error LogEntryLevel = "error"
	Fatal LogEntryLevel = "fatal"
	Info  LogEntryLevel = "info"
	Warn  LogEntryLevel = "warn"
)

// Valid indicates whether the value is a known member of the LogEntryLevel enum.
func (e LogEntryLevel) Valid() bool {
	switch e {
	case Debug:
		return true
	case Error:
		return true
	case Fatal:
		return true
	case Info:
		return true
	case Warn:
		return true
	default:
		return false
	}
}

// Defines values for MQTTConnectionType.
const (
	Mqtt MQTTConnectionType = "mqtt"
)

// Valid indicates whether the value is a known member of the MQTTConnectionType enum.
func (e MQTTConnectionType) Valid() bool {
	switch e {
	case Mqtt:
		return true
	default:
		return false
	}
}

// ADCConfig defines model for ADCConfig.
type ADCConfig struct {
	// Device sysfs path to the IIO device directory, e.g. "/sys/bus/iio/devices/iio:device0"
	Device string `json:"device"`
}

// DACConfig defines model for DACConfig.
type DACConfig struct {
	// Device sysfs path to the IIO device directory, e.g. "/sys/bus/iio/devices/iio:device1"
	Device string `json:"device"`
}

// DeploymentMapping Binds a binding-free workflow's logical resource ids to concrete platform resources for one deploy, keyed by workflow resource id. The pool a binding's ref resolves against is determined by the workflow resource's type: hardware channels resolve against the boot DeviceManifest; MQTT channels and custom models against the deploy ExternalResources; RAG memory against the boot-configured backend (the ref is the collection id).
type DeploymentMapping map[string]ResourceBinding

// DeviceManifest Hardware resources available on the device, keyed by driver instance ID. Drives runtime driver instantiation on the engine.
type DeviceManifest struct {
	Adcs    *map[string]ADCConfig    `json:"adcs,omitempty"`
	Dacs    *map[string]DACConfig    `json:"dacs,omitempty"`
	Gpios   *map[string]GPIOConfig   `json:"gpios,omitempty"`
	Pwms    *map[string]PWMConfig    `json:"pwms,omitempty"`
	Serials *map[string]SerialConfig `json:"serials,omitempty"`
}

// EngineConfig The engine's complete boot input, loaded once at startup from a single file — the engine is immutable, with no runtime hot-swap. Bundles the binding-free workflow, the deploy mapping that binds its logical resource ids to this environment, the resolved external-resource configs those bindings point at, and the device manifest (the hardware catalog the mapping resolves against). The deployment-scoped parts and the device-scoped manifest have different owners in the control plane; the renderer merges them into this one blob for the engine. A workflow is required — an engine exists only to run one. The engine still validates it at boot and fails fast if it is missing, since JSON unmarshalling does not enforce required fields.
type EngineConfig struct {
	// ExternalResources Deploy-time configs for a workflow's non-device external resources (MQTT transports, custom-model providers, ...), keyed by the platform resource id the DeploymentMapping points at. Replaces the former NetworkManifest. Device-owned configs (drivers) stay in the boot DeviceManifest; this carries only deploy-delivered, swappable configs.
	ExternalResources *ExternalResources `json:"externalResources,omitempty"`

	// Manifest Hardware resources available on the device, keyed by driver instance ID. Drives runtime driver instantiation on the engine.
	Manifest *DeviceManifest `json:"manifest,omitempty"`

	// Mapping Binds a binding-free workflow's logical resource ids to concrete platform resources for one deploy, keyed by workflow resource id. The pool a binding's ref resolves against is determined by the workflow resource's type: hardware channels resolve against the boot DeviceManifest; MQTT channels and custom models against the deploy ExternalResources; RAG memory against the boot-configured backend (the ref is the collection id).
	Mapping *DeploymentMapping `json:"mapping,omitempty"`

	// Workflow Workflow represents the deployment format of a project, passed to agents.
	Workflow externalRef0.Workflow `json:"workflow"`
}

// ExternalResourceConfig Tagged union of deploy-time external-resource configs, discriminated by runtime kind (not by ownership — locality like on-device vs cloud lives inside an arm). New kinds extend this oneOf.
type ExternalResourceConfig struct {
	union json.RawMessage
}

// ExternalResources Deploy-time configs for a workflow's non-device external resources (MQTT transports, custom-model providers, ...), keyed by the platform resource id the DeploymentMapping points at. Replaces the former NetworkManifest. Device-owned configs (drivers) stay in the boot DeviceManifest; this carries only deploy-delivered, swappable configs.
type ExternalResources map[string]ExternalResourceConfig

// GPIOConfig defines model for GPIOConfig.
type GPIOConfig struct {
	// Chip cdev chip name or path, e.g. "gpiochip0" or "/dev/gpiochip0"
	Chip string `json:"chip"`
}

// LLMProviderConfig Resolved connection to a self-hosted/custom LLM endpoint the llmproxy doesn't ship. The engine registers it as an llmproxy provider for the workflow's custom model; the model's capabilities come from its declared workflow entry, so they are not repeated here.
type LLMProviderConfig struct {
	// ApiKey Optional bearer credential for the endpoint.
	ApiKey *string `json:"apiKey,omitempty"`

	// Model Upstream model name the endpoint serves; defaults to the workflow model id when empty.
	Model *string               `json:"model,omitempty"`
	Type  LLMProviderConfigType `json:"type"`

	// Url Base URL of the inference endpoint (http:// or https://).
	Url string `json:"url"`
}

// LLMProviderConfigType defines model for LLMProviderConfig.Type.
type LLMProviderConfigType string

// LogEntry Single log event emitted by the engine. The reserved keys (level/action/summary/msg/time) populate dedicated agent_activity columns; any extra top-level keys are bucketed into the details JSONB column on ingest.
type LogEntry struct {
	Action               string                 `json:"action"`
	Level                LogEntryLevel          `json:"level"`
	Msg                  string                 `json:"msg"`
	Summary              string                 `json:"summary"`
	Time                 time.Time              `json:"time"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LogEntryLevel defines model for LogEntry.Level.
type LogEntryLevel string

// MQTTConnection defines model for MQTTConnection.
type MQTTConnection struct {
	BrokerURL string  `json:"brokerUrl"`
	ClientID  *string `json:"clientId,omitempty"`
	Password  *string `json:"password,omitempty"`

	// PublishPrefix Topic prefix the engine prepends to workflow-level publish topics ({networkId}/{agentId}/).
	PublishPrefix *string `json:"publishPrefix,omitempty"`

	// SubscribePrefix Topic prefix the engine prepends to workflow-level subscribe filters ({networkId}/+/).
	SubscribePrefix *string            `json:"subscribePrefix,omitempty"`
	Type            MQTTConnectionType `json:"type"`
	Username        *string            `json:"username,omitempty"`
	Will            *MQTTWill          `json:"will,omitempty"`
}

// MQTTConnectionType defines model for MQTTConnection.Type.
type MQTTConnectionType string

// MQTTWill defines model for MQTTWill.
type MQTTWill struct {
	Payload string `json:"payload"`

	// Qos MQTT QoS (0,1,2). Cast to byte at the paho call site.
	Qos    int    `json:"qos"`
	Retain bool   `json:"retain"`
	Topic  string `json:"topic"`
}

// MemoryFileWrite Body of PUT /agents/memory/{name}.
type MemoryFileWrite struct {
	Content string `json:"content"`
}

// PWMConfig defines model for PWMConfig.
type PWMConfig struct {
	// Chip sysfs path to the pwmchip directory, e.g. "/sys/class/pwm/pwmchip0"
	Chip string `json:"chip"`
}

// RagQueryRequest defines model for RagQueryRequest.
type RagQueryRequest struct {
	// CollectionID Collection to query
	CollectionID string `json:"collectionId"`

	// Query Search query text
	Query string `json:"query"`

	// TopK Number of results to return
	TopK *int `json:"topK,omitempty"`
}

// RagQueryResult defines model for RagQueryResult.
type RagQueryResult struct {
	ChunkID    string  `json:"chunkId"`
	Content    string  `json:"content"`
	DocumentID string  `json:"documentId"`
	Score      float64 `json:"score"`
}

// ResourceBinding How one workflow resource binds to the environment. `ref` is the shared platform resource it points at (driver instance id, external resource id, or RAG collection id) — a sharing identity, so many workflow resources may share one ref and the engine builds it once. `index` is the optional per-channel physical sub-address within that resource: GPIO line, or ADC/PWM/DAC channel number. Absent for UART, MQTT, memory and models.
type ResourceBinding struct {
	// Index Per-channel physical sub-address within the driver (GPIO line / ADC-PWM-DAC channel). Omitted when the resource has no sub-address.
	Index *int `json:"index,omitempty"`

	// Ref Shared platform resource id this binds to.
	Ref string `json:"ref"`
}

// SerialConfig defines model for SerialConfig.
type SerialConfig struct {
	// Baud Baud rate; falls back to 115200 when zero
	Baud *int `json:"baud,omitempty"`

	// Device Serial device path, e.g. "/dev/ttyUSB0" or "COM3"
	Device string `json:"device"`
}

// Getter for additional properties for LogEntry. Returns the specified
// element and whether it was found
func (a LogEntry) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LogEntry
func (a *LogEntry) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LogEntry to handle AdditionalProperties
func (a *LogEntry) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["action"]; found {
		err = json.Unmarshal(raw, &a.Action)
		if err != nil {
			return fmt.Errorf("error reading 'action': %w", err)
		}
		delete(object, "action")
	}

	if raw, found := object["level"]; found {
		err = json.Unmarshal(raw, &a.Level)
		if err != nil {
			return fmt.Errorf("error reading 'level': %w", err)
		}
		delete(object, "level")
	}

	if raw, found := object["msg"]; found {
		err = json.Unmarshal(raw, &a.Msg)
		if err != nil {
			return fmt.Errorf("error reading 'msg': %w", err)
		}
		delete(object, "msg")
	}

	if raw, found := object["summary"]; found {
		err = json.Unmarshal(raw, &a.Summary)
		if err != nil {
			return fmt.Errorf("error reading 'summary': %w", err)
		}
		delete(object, "summary")
	}

	if raw, found := object["time"]; found {
		err = json.Unmarshal(raw, &a.Time)
		if err != nil {
			return fmt.Errorf("error reading 'time': %w", err)
		}
		delete(object, "time")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LogEntry to handle AdditionalProperties
func (a LogEntry) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["action"], err = json.Marshal(a.Action)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'action': %w", err)
	}

	object["level"], err = json.Marshal(a.Level)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'level': %w", err)
	}

	object["msg"], err = json.Marshal(a.Msg)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'msg': %w", err)
	}

	object["summary"], err = json.Marshal(a.Summary)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'summary': %w", err)
	}

	object["time"], err = json.Marshal(a.Time)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'time': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsMQTTConnection returns the union data inside the ExternalResourceConfig as a MQTTConnection
func (t ExternalResourceConfig) AsMQTTConnection() (MQTTConnection, error) {
	var body MQTTConnection
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMQTTConnection overwrites any union data inside the ExternalResourceConfig as the provided MQTTConnection
func (t *ExternalResourceConfig) FromMQTTConnection(v MQTTConnection) error {
	v.Type = "mqtt"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMQTTConnection performs a merge with any union data inside the ExternalResourceConfig, using the provided MQTTConnection
func (t *ExternalResourceConfig) MergeMQTTConnection(v MQTTConnection) error {
	v.Type = "mqtt"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLLMProviderConfig returns the union data inside the ExternalResourceConfig as a LLMProviderConfig
func (t ExternalResourceConfig) AsLLMProviderConfig() (LLMProviderConfig, error) {
	var body LLMProviderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLLMProviderConfig overwrites any union data inside the ExternalResourceConfig as the provided LLMProviderConfig
func (t *ExternalResourceConfig) FromLLMProviderConfig(v LLMProviderConfig) error {
	v.Type = "selfhosted"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLLMProviderConfig performs a merge with any union data inside the ExternalResourceConfig, using the provided LLMProviderConfig
func (t *ExternalResourceConfig) MergeLLMProviderConfig(v LLMProviderConfig) error {
	v.Type = "selfhosted"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ExternalResourceConfig) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ExternalResourceConfig) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "mqtt":
		return t.AsMQTTConnection()
	case "selfhosted":
		return t.AsLLMProviderConfig()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ExternalResourceConfig) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ExternalResourceConfig) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
