// Package engineapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package engineapi

import (
	"encoding/json"
	"errors"

	externalRef0 "github.com/ForestHubAI/edge-agents/go/api/workflowapi"
	"github.com/oapi-codegen/runtime"
)

// Defines values for LLMProviderConfigType.
const (
	BackendLlm    LLMProviderConfigType = "backendLlm"
	LocalLlm      LLMProviderConfigType = "localLlm"
	SelfhostedLlm LLMProviderConfigType = "selfhostedLlm"
)

// Valid indicates whether the value is a known member of the LLMProviderConfigType enum.
func (e LLMProviderConfigType) Valid() bool {
	switch e {
	case BackendLlm:
		return true
	case LocalLlm:
		return true
	case SelfhostedLlm:
		return true
	default:
		return false
	}
}

// Defines values for MQTTConnectionType.
const (
	Mqtt MQTTConnectionType = "mqtt"
)

// Valid indicates whether the value is a known member of the MQTTConnectionType enum.
func (e MQTTConnectionType) Valid() bool {
	switch e {
	case Mqtt:
		return true
	default:
		return false
	}
}

// ADCConfig defines model for ADCConfig.
type ADCConfig struct {
	// Device sysfs path to the IIO device directory, e.g. "/sys/bus/iio/devices/iio:device0"
	Device string `json:"device"`
}

// DACConfig defines model for DACConfig.
type DACConfig struct {
	// Device sysfs path to the IIO device directory, e.g. "/sys/bus/iio/devices/iio:device1"
	Device string `json:"device"`
}

// DeviceManifest Hardware resources available on the device, keyed by driver instance ID.
type DeviceManifest struct {
	Adcs    *map[string]ADCConfig    `json:"adcs,omitempty"`
	Dacs    *map[string]DACConfig    `json:"dacs,omitempty"`
	Gpios   *map[string]GPIOConfig   `json:"gpios,omitempty"`
	Pwms    *map[string]PWMConfig    `json:"pwms,omitempty"`
	Serials *map[string]SerialConfig `json:"serials,omitempty"`
}

// EngineConfig The engine's complete boot input, loaded once at startup.
type EngineConfig struct {
	// ExternalResources Deploy-time configs for a workflow's non-device external resources (MQTT transports, custom-model providers, ...), keyed by platform resource id.
	ExternalResources *ExternalResources `json:"externalResources,omitempty"`

	// Manifest Hardware resources available on the device, keyed by driver instance ID.
	Manifest *DeviceManifest `json:"manifest,omitempty"`

	// Mapping Binds a binding-free workflow's logical resource ids to concrete platform resources, keyed by workflow resource id.
	Mapping *ResourceMapping `json:"mapping,omitempty"`

	// Workflow The deployment format of a workflow project.
	Workflow externalRef0.Workflow `json:"workflow"`
}

// EngineSecrets The engine's secret store: a flat map of secret id -> opaque secret value.
type EngineSecrets map[string]string

// ExternalResourceConfig Tagged union of deploy-time external-resource configs, discriminated by runtime kind (not by ownership — locality like on-device vs cloud lives inside an arm). New kinds extend this oneOf.
type ExternalResourceConfig struct {
	union json.RawMessage
}

// ExternalResources Deploy-time configs for a workflow's non-device external resources (MQTT transports, custom-model providers, ...), keyed by platform resource id.
type ExternalResources map[string]ExternalResourceConfig

// GPIOConfig defines model for GPIOConfig.
type GPIOConfig struct {
	// Chip cdev chip name or path, e.g. "gpiochip0" or "/dev/gpiochip0"
	Chip string `json:"chip"`
}

// LLMProviderConfig One LLM provider instance the engine registers into its single llmproxy; a workflow model reaches it by model id. localLlm: a built-in catalog adapter authenticated with a deploy-delivered API key (secrets.json, keyed by this resource's ref); `provider` names the adapter. backendLlm: that same catalog adapter's models proxied to the backend, no key; `provider` names the adapter. selfhostedLlm: a direct endpoint the llmproxy doesn't ship (`url`; optional bearer via secrets.json by ref), shared by every model bound to it. Each catalog provider is served by exactly one instance (localLlm xor backendLlm) — no catch-all, no shadowing.
type LLMProviderConfig struct {
	// Provider localLlm / backendLlm only — the built-in catalog adapter this instance serves (e.g. anthropic, openai).
	Provider *string               `json:"provider,omitempty"`
	Type     LLMProviderConfigType `json:"type"`

	// Url selfhostedLlm only — base URL of the inference endpoint (http:// or https://).
	Url *string `json:"url,omitempty"`
}

// LLMProviderConfigType defines model for LLMProviderConfig.Type.
type LLMProviderConfigType string

// MQTTConnection Resolved connection metadata for an MQTT broker.
type MQTTConnection struct {
	BrokerURL string  `json:"brokerUrl"`
	ClientID  *string `json:"clientId,omitempty"`

	// PublishPrefix Topic prefix for workflow-level publish topics ({networkId}/{agentId}/).
	PublishPrefix *string `json:"publishPrefix,omitempty"`

	// SubscribePrefix Topic prefix for workflow-level subscribe filters ({networkId}/+/).
	SubscribePrefix *string            `json:"subscribePrefix,omitempty"`
	Type            MQTTConnectionType `json:"type"`
	Username        *string            `json:"username,omitempty"`
	Will            *MQTTWill          `json:"will,omitempty"`
}

// MQTTConnectionType defines model for MQTTConnection.Type.
type MQTTConnectionType string

// MQTTWill defines model for MQTTWill.
type MQTTWill struct {
	Payload string `json:"payload"`

	// Qos MQTT QoS (0, 1, or 2).
	Qos    int    `json:"qos"`
	Retain bool   `json:"retain"`
	Topic  string `json:"topic"`
}

// PWMConfig defines model for PWMConfig.
type PWMConfig struct {
	// Chip sysfs path to the pwmchip directory, e.g. "/sys/class/pwm/pwmchip0"
	Chip string `json:"chip"`
}

// RagQueryRequest defines model for RagQueryRequest.
type RagQueryRequest struct {
	// CollectionID Collection to query
	CollectionID string `json:"collectionId"`

	// Query Search query text
	Query string `json:"query"`

	// TopK Number of results to return
	TopK *int `json:"topK,omitempty"`
}

// RagQueryResult defines model for RagQueryResult.
type RagQueryResult struct {
	ChunkID    string  `json:"chunkId"`
	Content    string  `json:"content"`
	DocumentID string  `json:"documentId"`
	Score      float64 `json:"score"`
}

// ResourceBinding How one workflow resource binds to the environment: a shared platform resource `ref` with an optional per-channel physical sub-address `index`.
type ResourceBinding struct {
	// Index Per-channel physical sub-address within the driver (GPIO line / ADC-PWM-DAC channel). Omitted when the resource has no sub-address.
	Index *int `json:"index,omitempty"`

	// Ref Shared platform resource id this binds to.
	Ref string `json:"ref"`
}

// ResourceMapping Binds a binding-free workflow's logical resource ids to concrete platform resources, keyed by workflow resource id.
type ResourceMapping map[string]ResourceBinding

// SerialConfig defines model for SerialConfig.
type SerialConfig struct {
	// Baud Baud rate; falls back to 115200 when zero
	Baud *int `json:"baud,omitempty"`

	// Device Serial device path, e.g. "/dev/ttyUSB0" or "COM3"
	Device string `json:"device"`
}

// AsMQTTConnection returns the union data inside the ExternalResourceConfig as a MQTTConnection
func (t ExternalResourceConfig) AsMQTTConnection() (MQTTConnection, error) {
	var body MQTTConnection
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMQTTConnection overwrites any union data inside the ExternalResourceConfig as the provided MQTTConnection
func (t *ExternalResourceConfig) FromMQTTConnection(v MQTTConnection) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMQTTConnection performs a merge with any union data inside the ExternalResourceConfig, using the provided MQTTConnection
func (t *ExternalResourceConfig) MergeMQTTConnection(v MQTTConnection) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLLMProviderConfig returns the union data inside the ExternalResourceConfig as a LLMProviderConfig
func (t ExternalResourceConfig) AsLLMProviderConfig() (LLMProviderConfig, error) {
	var body LLMProviderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLLMProviderConfig overwrites any union data inside the ExternalResourceConfig as the provided LLMProviderConfig
func (t *ExternalResourceConfig) FromLLMProviderConfig(v LLMProviderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLLMProviderConfig performs a merge with any union data inside the ExternalResourceConfig, using the provided LLMProviderConfig
func (t *ExternalResourceConfig) MergeLLMProviderConfig(v LLMProviderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ExternalResourceConfig) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ExternalResourceConfig) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "backendLlm":
		return t.AsLLMProviderConfig()
	case "localLlm":
		return t.AsLLMProviderConfig()
	case "mqtt":
		return t.AsMQTTConnection()
	case "selfhostedLlm":
		return t.AsLLMProviderConfig()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ExternalResourceConfig) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ExternalResourceConfig) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
