// Package engineapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package engineapi

import (
	"encoding/json"
	"errors"
	"fmt"
	"time"

	externalRef0 "github.com/ForestHubAI/fh-core/go/api/workflow"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AgentBootCallbackStatus.
const (
	Booterror AgentBootCallbackStatus = "booterror"
	Online    AgentBootCallbackStatus = "online"
)

// Valid indicates whether the value is a known member of the AgentBootCallbackStatus enum.
func (e AgentBootCallbackStatus) Valid() bool {
	switch e {
	case Booterror:
		return true
	case Online:
		return true
	default:
		return false
	}
}

// Defines values for AgentRuntimeStatusResponseStatus.
const (
	AgentRuntimeStatusResponseStatusIdle    AgentRuntimeStatusResponseStatus = "idle"
	AgentRuntimeStatusResponseStatusRunning AgentRuntimeStatusResponseStatus = "running"
)

// Valid indicates whether the value is a known member of the AgentRuntimeStatusResponseStatus enum.
func (e AgentRuntimeStatusResponseStatus) Valid() bool {
	switch e {
	case AgentRuntimeStatusResponseStatusIdle:
		return true
	case AgentRuntimeStatusResponseStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for LogEntryLevel.
const (
	Debug LogEntryLevel = "debug"
	Error LogEntryLevel = "error"
	Fatal LogEntryLevel = "fatal"
	Info  LogEntryLevel = "info"
	Warn  LogEntryLevel = "warn"
)

// Valid indicates whether the value is a known member of the LogEntryLevel enum.
func (e LogEntryLevel) Valid() bool {
	switch e {
	case Debug:
		return true
	case Error:
		return true
	case Fatal:
		return true
	case Info:
		return true
	case Warn:
		return true
	default:
		return false
	}
}

// Defines values for MQTTBYOBCredentialsType.
const (
	MqttByob MQTTBYOBCredentialsType = "mqtt-byob"
)

// Valid indicates whether the value is a known member of the MQTTBYOBCredentialsType enum.
func (e MQTTBYOBCredentialsType) Valid() bool {
	switch e {
	case MqttByob:
		return true
	default:
		return false
	}
}

// Defines values for MQTTNetworkConfigType.
const (
	Mqtt MQTTNetworkConfigType = "mqtt"
)

// Valid indicates whether the value is a known member of the MQTTNetworkConfigType enum.
func (e MQTTNetworkConfigType) Valid() bool {
	switch e {
	case Mqtt:
		return true
	default:
		return false
	}
}

// Defines values for MissingResourceFamily.
const (
	MissingResourceFamilyAdc     MissingResourceFamily = "adc"
	MissingResourceFamilyDac     MissingResourceFamily = "dac"
	MissingResourceFamilyGpio    MissingResourceFamily = "gpio"
	MissingResourceFamilyNetwork MissingResourceFamily = "network"
	MissingResourceFamilyPwm     MissingResourceFamily = "pwm"
	MissingResourceFamilySerial  MissingResourceFamily = "serial"
)

// Valid indicates whether the value is a known member of the MissingResourceFamily enum.
func (e MissingResourceFamily) Valid() bool {
	switch e {
	case MissingResourceFamilyAdc:
		return true
	case MissingResourceFamilyDac:
		return true
	case MissingResourceFamilyGpio:
		return true
	case MissingResourceFamilyNetwork:
		return true
	case MissingResourceFamilyPwm:
		return true
	case MissingResourceFamilySerial:
		return true
	default:
		return false
	}
}

// Defines values for MissingResourceReason.
const (
	DeviceNotMember    MissingResourceReason = "device-not-member"
	InvalidConfig      MissingResourceReason = "invalid-config"
	InvalidCredentials MissingResourceReason = "invalid-credentials"
	MissingBrokerUrl   MissingResourceReason = "missing-broker-url"
	MissingCredentials MissingResourceReason = "missing-credentials"
	NetworkNotFound    MissingResourceReason = "network-not-found"
	NotInManifest      MissingResourceReason = "not-in-manifest"
	WrongProtocol      MissingResourceReason = "wrong-protocol"
)

// Valid indicates whether the value is a known member of the MissingResourceReason enum.
func (e MissingResourceReason) Valid() bool {
	switch e {
	case DeviceNotMember:
		return true
	case InvalidConfig:
		return true
	case InvalidCredentials:
		return true
	case MissingBrokerUrl:
		return true
	case MissingCredentials:
		return true
	case NetworkNotFound:
		return true
	case NotInManifest:
		return true
	case WrongProtocol:
		return true
	default:
		return false
	}
}

// Defines values for NoCredentialsType.
const (
	None NoCredentialsType = "none"
)

// Valid indicates whether the value is a known member of the NoCredentialsType enum.
func (e NoCredentialsType) Valid() bool {
	switch e {
	case None:
		return true
	default:
		return false
	}
}

// Defines values for State.
const (
	StateIdle    State = "idle"
	StateRunning State = "running"
)

// Valid indicates whether the value is a known member of the State enum.
func (e State) Valid() bool {
	switch e {
	case StateIdle:
		return true
	case StateRunning:
		return true
	default:
		return false
	}
}

// ADCConfig defines model for ADCConfig.
type ADCConfig struct {
	// Device sysfs path to the IIO device directory, e.g. "/sys/bus/iio/devices/iio:device0"
	Device string `json:"device"`
}

// AgentBootCallback defines model for AgentBootCallback.
type AgentBootCallback struct {
	// Address Externally reachable HTTP(S) URL of the engine. Optional —
	// Cloud-mode engines behind NAT may omit this; the backend then
	// stores the address as SQL NULL and rejects push deploys for
	// this agent, while bundle deploys and liveness still work.
	Address *string `json:"address,omitempty"`

	// Error Human-readable failure detail. Set when status='booterror', null otherwise.
	Error *string `json:"error,omitempty"`

	// LoadedDeviceManifest Hardware resources available on the device, keyed by driver instance ID.
	// Drives runtime driver instantiation on the engine.
	LoadedDeviceManifest *DeviceManifest `json:"loadedDeviceManifest,omitempty"`

	// Status Boot result reported by the engine. 'online' when the manifest
	// loaded cleanly and the engine is ready to accept deploy requests;
	// 'booterror' when something blocked startup (missing driver,
	// invalid manifest, etc.).
	Status AgentBootCallbackStatus `json:"status"`
}

// AgentBootCallbackStatus Boot result reported by the engine. 'online' when the manifest
// loaded cleanly and the engine is ready to accept deploy requests;
// 'booterror' when something blocked startup (missing driver,
// invalid manifest, etc.).
type AgentBootCallbackStatus string

// AgentHeartbeatRequest defines model for AgentHeartbeatRequest.
type AgentHeartbeatRequest struct {
	// Address Externally reachable HTTP(S) URL of the engine. Optional —
	// Cloud-mode engines behind NAT may omit this; the heartbeat
	// then only refreshes liveness via the AgentKeyAuth middleware
	// without writing the address column.
	Address *string `json:"address,omitempty"`
}

// AgentRuntimeStatusResponse defines model for AgentRuntimeStatusResponse.
type AgentRuntimeStatusResponse struct {
	Status AgentRuntimeStatusResponseStatus `json:"status"`
}

// AgentRuntimeStatusResponseStatus defines model for AgentRuntimeStatusResponse.Status.
type AgentRuntimeStatusResponseStatus string

// DACConfig defines model for DACConfig.
type DACConfig struct {
	// Device sysfs path to the IIO device directory, e.g. "/sys/bus/iio/devices/iio:device1"
	Device string `json:"device"`
}

// DeployRequest Engine-served POST /deploy body: a resolved workflow plus the network manifest. Distinct from the backend control-plane DeployRequestBody (DeploymentConfig/RedeployRequest). workflow is intentionally NOT required so it generates as a pointer (the handler nil-checks it).
type DeployRequest struct {
	// NetworkManifest Resolved MQTT transports keyed by network ID, handed to the engine on deploy.
	NetworkManifest *NetworkManifest `json:"networkManifest,omitempty"`

	// Workflow Workflow represents the deployment format of a project, passed to agents.
	Workflow *externalRef0.Workflow `json:"workflow,omitempty"`
}

// DeployRequestBody Body for /agents/{agentId}/deploy and /agents/{agentId}/deployments.
// DeploymentConfig is a fresh deploy (workflow + projectId); RedeployRequest
// reactivates a historical deployment by ID.
type DeployRequestBody struct {
	union json.RawMessage
}

// DeploymentConfig Snapshot of what's deployed to an agent
type DeploymentConfig struct {
	ProjectId string `json:"projectId"`

	// Workflow Workflow represents the deployment format of a project, passed to agents.
	Workflow externalRef0.Workflow `json:"workflow"`
}

// DeviceManifest Hardware resources available on the device, keyed by driver instance ID.
// Drives runtime driver instantiation on the engine.
type DeviceManifest struct {
	Adcs    *map[string]ADCConfig    `json:"adcs,omitempty"`
	Dacs    *map[string]DACConfig    `json:"dacs,omitempty"`
	Gpios   *map[string]GPIOConfig   `json:"gpios,omitempty"`
	Pwms    *map[string]PWMConfig    `json:"pwms,omitempty"`
	Serials *map[string]SerialConfig `json:"serials,omitempty"`
}

// DeviceResources defines model for DeviceResources.
type DeviceResources struct {
	// Manifest Hardware resources available on the device, keyed by driver instance ID.
	// Drives runtime driver instantiation on the engine.
	Manifest DeviceManifest `json:"manifest"`
	Networks []Network      `json:"networks"`
}

// EngineError Error body for /deploy 400/422. Distinct from control-plane ErrorResponse.
type EngineError struct {
	Error string `json:"error"`
}

// EngineTarballResponse defines model for EngineTarballResponse.
type EngineTarballResponse struct {
	// ExpiresAt RFC3339 timestamp when the signed URL stops being honored by GCS.
	ExpiresAt time.Time `json:"expiresAt"`

	// Sha256 Hex-encoded SHA256 of the tarball.
	Sha256 string `json:"sha256"`

	// Url V4 GCS Signed URL, valid for the duration encoded in expiresAt.
	Url string `json:"url"`

	// Version Engine image version that this tarball delivers.
	Version string `json:"version"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// GPIOConfig defines model for GPIOConfig.
type GPIOConfig struct {
	// Chip cdev chip name or path, e.g. "gpiochip0" or "/dev/gpiochip0"
	Chip string `json:"chip"`
}

// HealthzResponse defines model for HealthzResponse.
type HealthzResponse struct {
	// Status Engine runner state.
	Status State `json:"status"`
}

// LogEntry Single log event emitted by the engine. The reserved keys
// (level/action/summary/msg/time) populate dedicated agent_activity
// columns; any extra top-level keys are bucketed into the details
// JSONB column on ingest.
type LogEntry struct {
	Action               string                 `json:"action"`
	Level                LogEntryLevel          `json:"level"`
	Msg                  string                 `json:"msg"`
	Summary              string                 `json:"summary"`
	Time                 time.Time              `json:"time"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LogEntryLevel defines model for LogEntry.Level.
type LogEntryLevel string

// MQTTBYOBCredentials Credentials for an external (customer defined) MQTT broker.
type MQTTBYOBCredentials struct {
	ClientID *string                 `json:"clientId,omitempty"`
	Password string                  `json:"password"`
	Type     MQTTBYOBCredentialsType `json:"type"`
	Username string                  `json:"username"`
}

// MQTTBYOBCredentialsType defines model for MQTTBYOBCredentials.Type.
type MQTTBYOBCredentialsType string

// MQTTConnection defines model for MQTTConnection.
type MQTTConnection struct {
	BrokerURL string  `json:"brokerUrl"`
	ClientID  *string `json:"clientId,omitempty"`
	Password  *string `json:"password,omitempty"`

	// PublishPrefix Topic prefix the engine prepends to workflow-level publish topics ({networkId}/{agentId}/).
	PublishPrefix *string `json:"publishPrefix,omitempty"`

	// SubscribePrefix Topic prefix the engine prepends to workflow-level subscribe filters ({networkId}/+/).
	SubscribePrefix *string   `json:"subscribePrefix,omitempty"`
	Username        *string   `json:"username,omitempty"`
	Will            *MQTTWill `json:"will,omitempty"`
}

// MQTTNetworkConfig Connection config stored on a network row whose protocol is mqtt.
type MQTTNetworkConfig struct {
	// BrokerURL MQTT broker URL (mqtt:// or mqtts://). Required regardless of ACL ownership.
	BrokerURL string `json:"brokerUrl"`

	// ManagedACL Wether the broker uses the ForestHub provided MQTT broker with internal ACL management
	ManagedACL bool                  `json:"managedACL"`
	Type       MQTTNetworkConfigType `json:"type"`
}

// MQTTNetworkConfigType defines model for MQTTNetworkConfig.Type.
type MQTTNetworkConfigType string

// MQTTWill defines model for MQTTWill.
type MQTTWill struct {
	Payload string `json:"payload"`

	// Qos MQTT QoS (0,1,2). Cast to byte at the paho call site.
	Qos    int    `json:"qos"`
	Retain bool   `json:"retain"`
	Topic  string `json:"topic"`
}

// MembershipCredentials Tagged union of credentials shapes a device can carry for one network membership.
type MembershipCredentials struct {
	union json.RawMessage
}

// MemoryFileWrite Body of PUT /agents/memory/{name}.
type MemoryFileWrite struct {
	Content string `json:"content"`
}

// MissingResource defines model for MissingResource.
type MissingResource struct {
	// Channels Workflow channel IDs that reference this missing resource.
	Channels *[]string `json:"channels,omitempty"`

	// Family Resource family. Hardware drivers (gpio/adc/dac/pwm/serial) live in DeviceManifest; network covers MQTT transport channels.
	Family MissingResourceFamily `json:"family"`

	// ID Driver instance ID (gpio/adc/dac/pwm/serial) or network UUID (network) the workflow asks for.
	ID     string                `json:"id"`
	Reason MissingResourceReason `json:"reason"`
}

// MissingResourceFamily Resource family. Hardware drivers (gpio/adc/dac/pwm/serial) live in DeviceManifest; network covers MQTT transport channels.
type MissingResourceFamily string

// MissingResourceReason defines model for MissingResource.Reason.
type MissingResourceReason string

// Network defines model for Network.
type Network struct {
	AccountID string `json:"accountId"`

	// AgentCount Number of agents deployed on devices in this network
	AgentCount int `json:"agentCount"`

	// Config Tagged union of network connection configs. The `type` field is the
	// single source of truth for the network's protocol — there is no
	// separate top-level `protocol` field on Network. New protocols extend
	// this oneOf with another arm.
	Config      NetworkConfig `json:"config"`
	CreatedAt   time.Time     `json:"createdAt"`
	Description *string       `json:"description,omitempty"`

	// DeviceCount Number of devices currently in this network
	DeviceCount int       `json:"deviceCount"`
	Id          string    `json:"id"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// NetworkConfig Tagged union of network connection configs. The `type` field is the
// single source of truth for the network's protocol — there is no
// separate top-level `protocol` field on Network. New protocols extend
// this oneOf with another arm.
type NetworkConfig struct {
	union json.RawMessage
}

// NetworkManifest Resolved MQTT transports keyed by network ID, handed to the engine on deploy.
type NetworkManifest struct {
	// MQTTs Network ID -> resolved MQTT connection.
	MQTTs map[string]MQTTConnection `json:"mqtts"`
}

// NoCredentials Sentinel "no credentials needed" arm of MembershipCredentials.
type NoCredentials struct {
	Type NoCredentialsType `json:"type"`
}

// NoCredentialsType defines model for NoCredentials.Type.
type NoCredentialsType string

// PWMConfig defines model for PWMConfig.
type PWMConfig struct {
	// Chip sysfs path to the pwmchip directory, e.g. "/sys/class/pwm/pwmchip0"
	Chip string `json:"chip"`
}

// PreflightErrorResponse 422 response body returned by any deploy-shaped operation
// (/agents/{agentId}/deploy, /agents/{agentId}/deployments,
// /agents/{agentId}/preflight) when the workflow's hardware or network
// requirements cannot be satisfied on the target agent's environment.
// Frontend uses missing[].reason to drive the resource-mapping dialog.
type PreflightErrorResponse struct {
	// Error Human-readable summary of the preflight failure.
	Error   string            `json:"error"`
	Missing []MissingResource `json:"missing"`
}

// RagQueryRequest defines model for RagQueryRequest.
type RagQueryRequest struct {
	// CollectionID Collection to query
	CollectionID string `json:"collectionId"`

	// Query Search query text
	Query string `json:"query"`

	// TopK Number of results to return
	TopK *int `json:"topK,omitempty"`
}

// RagQueryResult defines model for RagQueryResult.
type RagQueryResult struct {
	ChunkID    string  `json:"chunkId"`
	Content    string  `json:"content"`
	DocumentID string  `json:"documentId"`
	Score      float64 `json:"score"`
}

// RedeployRequest Reactivate a historical deployment by ID. Backend loads the workflow
// from agent_deployments.config and flips agents.active_deployment_id;
// no new deployment row is written.
type RedeployRequest struct {
	DeploymentID openapi_types.UUID `json:"deploymentId"`
}

// SerialConfig defines model for SerialConfig.
type SerialConfig struct {
	// Baud Baud rate; falls back to 115200 when zero
	Baud *int `json:"baud,omitempty"`

	// Device Serial device path, e.g. "/dev/ttyUSB0" or "COM3"
	Device string `json:"device"`
}

// State Engine runner state.
type State string

// DeployJSONRequestBody defines body for Deploy for application/json ContentType.
type DeployJSONRequestBody = DeployRequest

// Getter for additional properties for LogEntry. Returns the specified
// element and whether it was found
func (a LogEntry) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LogEntry
func (a *LogEntry) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LogEntry to handle AdditionalProperties
func (a *LogEntry) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["action"]; found {
		err = json.Unmarshal(raw, &a.Action)
		if err != nil {
			return fmt.Errorf("error reading 'action': %w", err)
		}
		delete(object, "action")
	}

	if raw, found := object["level"]; found {
		err = json.Unmarshal(raw, &a.Level)
		if err != nil {
			return fmt.Errorf("error reading 'level': %w", err)
		}
		delete(object, "level")
	}

	if raw, found := object["msg"]; found {
		err = json.Unmarshal(raw, &a.Msg)
		if err != nil {
			return fmt.Errorf("error reading 'msg': %w", err)
		}
		delete(object, "msg")
	}

	if raw, found := object["summary"]; found {
		err = json.Unmarshal(raw, &a.Summary)
		if err != nil {
			return fmt.Errorf("error reading 'summary': %w", err)
		}
		delete(object, "summary")
	}

	if raw, found := object["time"]; found {
		err = json.Unmarshal(raw, &a.Time)
		if err != nil {
			return fmt.Errorf("error reading 'time': %w", err)
		}
		delete(object, "time")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LogEntry to handle AdditionalProperties
func (a LogEntry) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["action"], err = json.Marshal(a.Action)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'action': %w", err)
	}

	object["level"], err = json.Marshal(a.Level)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'level': %w", err)
	}

	object["msg"], err = json.Marshal(a.Msg)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'msg': %w", err)
	}

	object["summary"], err = json.Marshal(a.Summary)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'summary': %w", err)
	}

	object["time"], err = json.Marshal(a.Time)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'time': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsDeploymentConfig returns the union data inside the DeployRequestBody as a DeploymentConfig
func (t DeployRequestBody) AsDeploymentConfig() (DeploymentConfig, error) {
	var body DeploymentConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeploymentConfig overwrites any union data inside the DeployRequestBody as the provided DeploymentConfig
func (t *DeployRequestBody) FromDeploymentConfig(v DeploymentConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeploymentConfig performs a merge with any union data inside the DeployRequestBody, using the provided DeploymentConfig
func (t *DeployRequestBody) MergeDeploymentConfig(v DeploymentConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRedeployRequest returns the union data inside the DeployRequestBody as a RedeployRequest
func (t DeployRequestBody) AsRedeployRequest() (RedeployRequest, error) {
	var body RedeployRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRedeployRequest overwrites any union data inside the DeployRequestBody as the provided RedeployRequest
func (t *DeployRequestBody) FromRedeployRequest(v RedeployRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRedeployRequest performs a merge with any union data inside the DeployRequestBody, using the provided RedeployRequest
func (t *DeployRequestBody) MergeRedeployRequest(v RedeployRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t DeployRequestBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DeployRequestBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsNoCredentials returns the union data inside the MembershipCredentials as a NoCredentials
func (t MembershipCredentials) AsNoCredentials() (NoCredentials, error) {
	var body NoCredentials
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoCredentials overwrites any union data inside the MembershipCredentials as the provided NoCredentials
func (t *MembershipCredentials) FromNoCredentials(v NoCredentials) error {
	v.Type = "none"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNoCredentials performs a merge with any union data inside the MembershipCredentials, using the provided NoCredentials
func (t *MembershipCredentials) MergeNoCredentials(v NoCredentials) error {
	v.Type = "none"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMQTTBYOBCredentials returns the union data inside the MembershipCredentials as a MQTTBYOBCredentials
func (t MembershipCredentials) AsMQTTBYOBCredentials() (MQTTBYOBCredentials, error) {
	var body MQTTBYOBCredentials
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMQTTBYOBCredentials overwrites any union data inside the MembershipCredentials as the provided MQTTBYOBCredentials
func (t *MembershipCredentials) FromMQTTBYOBCredentials(v MQTTBYOBCredentials) error {
	v.Type = "mqtt-byob"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMQTTBYOBCredentials performs a merge with any union data inside the MembershipCredentials, using the provided MQTTBYOBCredentials
func (t *MembershipCredentials) MergeMQTTBYOBCredentials(v MQTTBYOBCredentials) error {
	v.Type = "mqtt-byob"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MembershipCredentials) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t MembershipCredentials) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "mqtt-byob":
		return t.AsMQTTBYOBCredentials()
	case "none":
		return t.AsNoCredentials()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t MembershipCredentials) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MembershipCredentials) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMQTTNetworkConfig returns the union data inside the NetworkConfig as a MQTTNetworkConfig
func (t NetworkConfig) AsMQTTNetworkConfig() (MQTTNetworkConfig, error) {
	var body MQTTNetworkConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMQTTNetworkConfig overwrites any union data inside the NetworkConfig as the provided MQTTNetworkConfig
func (t *NetworkConfig) FromMQTTNetworkConfig(v MQTTNetworkConfig) error {
	v.Type = "mqtt"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMQTTNetworkConfig performs a merge with any union data inside the NetworkConfig, using the provided MQTTNetworkConfig
func (t *NetworkConfig) MergeMQTTNetworkConfig(v MQTTNetworkConfig) error {
	v.Type = "mqtt"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NetworkConfig) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t NetworkConfig) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "mqtt":
		return t.AsMQTTNetworkConfig()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t NetworkConfig) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NetworkConfig) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
