#!/usr/bin/env bash
# ForestHub llama-server component — thin config-bridge entrypoint.
#
# llama-swap needs a YAML config mapping each model id to a launch command; the
# ForestHub boot config arrives as JSON at a fixed path (the device-filesystem
# ConfigFile). This script IS the whole wrapper: translate that JSON into a llama-swap
# config, then exec llama-swap. It ships no logs itself — the component writes to
# stdout and Ranger captures it. The base image already bundles llama-swap +
# llama-server, so nothing is compiled here.
#
# Config shape: contract/llama-server.yaml (LlamaServerConfig).
set -euo pipefail

# Fixed device-filesystem contract paths (edge-agents go/component). Overridable for
# local testing, but the renderer mounts at these defaults.
CONFIG="${FH_CONFIG_FILE:-/etc/foresthub/config.json}"
WORKSPACE="${FH_WORKSPACE:-/var/lib/foresthub/workspace}"
PORT="${FH_LLAMA_PORT:-8080}"
SERVER_BIN="${LLAMA_SERVER_BIN:-llama-server}"
SWAP_BIN="${LLAMA_SWAP_BIN:-llama-swap}"
TTL="${FH_MODEL_TTL:-300}"

SWAP_CONFIG="$(mktemp)"

# 78 = sysexits(3) EX_CONFIG, the component's ExitConfigError: a PERMANENT boot
# failure the orchestrator must not retry unchanged (bad config / missing model file).
fail() { echo "llama-server: $*" >&2; exit 78; }

[ -f "$CONFIG" ] || fail "boot config not found: $CONFIG"
jq -e '(.models | type) == "array" and (.models | length) >= 1' "$CONFIG" >/dev/null 2>&1 \
  || fail "boot config declares no models: $CONFIG"

# Render llama-swap YAML: one entry per model. ${PORT} is llama-swap's OWN macro (the
# per-model port it assigns and proxies) and must reach the YAML literally — hence the
# single-quoted printf format, which bash does not expand.
{
  echo "# generated by the llama-server entrypoint — do not edit"
  echo "models:"
  while IFS=$'\t' read -r id file args; do
    [ -n "$id" ] && [ -n "$file" ] || fail "model entry missing id or file"
    [ -f "$WORKSPACE/$file" ] || fail "model file not staged: $WORKSPACE/$file"
    printf '  "%s":\n' "$id"
    printf '    ttl: %s\n' "$TTL"
    printf '    cmd: >\n'
    printf '      %s --model %s/%s --host 127.0.0.1 --port ${PORT}%s\n' \
      "$SERVER_BIN" "$WORKSPACE" "$file" "${args:+ $args}"
  done < <(jq -r '.models[] | [.id, .file, ((.args // []) | join(" "))] | @tsv' "$CONFIG")
} > "$SWAP_CONFIG"

echo "llama-server: starting llama-swap ($(jq '.models | length' "$CONFIG") models) on :$PORT" >&2
exec "$SWAP_BIN" --config "$SWAP_CONFIG" --listen ":$PORT"
